### ISSUE TITLE
Ideas, Observations

### ISSUE THREAD

**Issue by mike-ward** [gitpitch/gitpitch#1]
Just started using this. Awesome idea. Couple of use issues.

- `#HSLIDE/#VSLIDE` are strange separators. It looks like a header in markdown previews. Suggest something more compact like `--` for horizontal, `++` for vertical (see jdan/cleaver).
- Doesn't recognize setext headers.
- `PITCHME.md` file name is case sensitive.
- In general, you should be able to run a `pitchme.md` file through Pandoc (I use this to reformat markdown files) without destroying the slide show.

I use http://markdownedit.com to edit markdown. It has a handy reformat function (using Pandoc). However, it runs afoul of with some of the gitpitch conventions. (like #hslide, #vslide).

**Comment by gitpitch** [comment]
Thanks @mike-ward, great feedback, much appreciated. I'm working on support for user-defined custom delimiters via PITCHME.yaml. The goal being to make PITCHME.md compatible with any Markdown editor, including your own cool creation, mike-ward/Markdown-Edit. I'll have something for you to try out in a couple of days. I'll update this thread once that support goes live.

**Comment by gitpitch** [comment]
@mike-ward  check out the new support for [Custom Slide Delimiters](https://github.com/gitpitch/gitpitch/wiki/Custom-Slide-Delimiters) for your slideshow presentations. You can now use PITCHME.yaml to set custom delimiters to make GitPitch compatible with any Markdown editor.

**Comment by mike-ward** [comment]
Yep, that works better.

**Comment by gitpitch** [comment]
Glad to hear it. So you also mentioned that GitPitch doesn't recognize setext headers. I created a simple presentation using the following Markdown:

```
Test setext header level one:

Hello World
===========

Test setext header level two:

Hello World
-----------

End of test.
```

And the slide appeared to render just fine as follows:
![setext-header](https://cloud.githubusercontent.com/assets/19169584/18038470/d12e0808-6dc2-11e6-9246-21c85f989470.png)

Can you please point me at a sample GitPitch that demonstrates the problem you encountered with setext headers.

**Comment by mike-ward** [comment]
Seems to be working now for me as well.

By the way, The links to the example slide shows (like Kitchen Sink) don't work for me.

**Comment by gitpitch** [comment]
Are you referring to the links to the example slide shows on the https://gitpitch.com website? Have you tried to click directly on the icon in the centre of the circle above each named example?

**Comment by gitpitch** [comment]
The set of links to the examples on the website have been simplified, to ensure from this point forward they just work. Thanks for pointing out this problem @mike-ward

**Comment by mike-ward** [comment]
The mouse pointer changes to a pointer indicating you can click when hovering over the example regions. It does work if you click on the icon but the feedback from the mouse cursor says I can click elsewhere.

**Comment by gitpitch** [comment]
Refresh/reload the website in your browser and you'll see we now have new simplified style of links to the example slideshows. No icons or regions, just straightforward links. Thanks again for bringing this to my attention.

**Comment by gitpitch** [comment]
@mike-ward I believe the last remaining open item on this thread is the following:

>> you should be able to run a pitchme.md file through Pandoc (I use this to reformat markdown files) without destroying the slide show

Now that you can customize slideshow delimiters can you successfully reformat your PITCHME.md files using Pandoc? Also for the record, can you share the Pandoc command you were using to perform this type of reformatting? Thanks.

**Comment by mike-ward** [comment]
I use Markdown Edit to reformat documents which, uses Pandoc. You can look at the source for the options. Use `Alt-F` on your documents.
