### ISSUE TITLE
Markdown inline code is not noticeable

### ISSUE THREAD

**Issue by toniov** [gitpitch/gitpitch#100]
Markdown `inline code` (text inside backticks ``) looks very similar to unformatted code.

I'm writing my presentations using only Markdown, so they can be reused in other places. Not sure if it's possible now, but if not, It would be nice if we could be able to add style to inline code.

Regards.

**Comment by gitpitch** [comment]
Hi @toniov you can customize the styling of almost any visual element in your presentation using `custom css` as described on the following [GitPitch Wiki page](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS).

For example, to apply a custom background color to your inline code blocks you could do the following:

```
.reveal code {
    background: gray;
}
```

Using this approach you can apply whatever custom styling you want for your own presentations.

**Comment by toniov** [comment]
Thanks for the fast reply!

I tried that but the styling also applies to block code.

I needed to change the [Highlight Setting](https://github.com/gitpitch/gitpitch/wiki/Highlight-Setting) as well, choosing a visual style that goes well with the new background color I set.

**Comment by gitpitch** [comment]
Yes, of course. Sounds like the perfect solution. If you are happy with this solution can you please go ahead and close out this issue.
