### ISSUE TITLE
GitLab subgroups not supported

### ISSUE THREAD

**Issue by vjanoch** [gitpitch/gitpitch#101]
GitPitch seems not to support repositories GitLabs that are within a subgroup. I've forked the gitpitch repo: https://gitlab.com/gitpitch-subgroup-test/subgroup/gitpitch

The GitPitch (https://gitpitch.com/gitpitch-subgroup-test/subgroup/gitpitch) doesn't recognize the repository: "Git repository not found on GitLab"

I assume GitPitch tries to request the branch `gitpitch` of a repo `https://gitpitch.com/gitpitch-subgroup-test/subgroup`.

**Comment by gitpitch** [comment]
Hi @vjanoch your assumption is correct. The structure of a valid GitPitch URI is as follows:

```
https://gitpitch.com/$user/$repo/$branch
``` 

Therefore the GitPitch URI you tested,  https://gitpitch.com/gitpitch-subgroup-test/subgroup/gitpitch, is interpreted by GitPitch as follows:

1. The $user is `gitpitch-subgroup-test`
2. The $repo is `subgroup`
3. And the $branch is `gitpitch`

I'm not familiar with the workings of sub-groups. Is this feature specific to GitLab? Or it is supported in a consistent/common way across Git providers such as GitHub, Bitbucket, etc?

**Comment by vjanoch** [comment]
Thank you very much for answering that fast! I appreciate it very much. 👍 

I'm not sure if other services than GitLab support or plan to support such a feature. The feature has been introduced in GitLab Version 9.0.
See: https://docs.gitlab.com/ce/user/group/subgroups/

In my test case the first part of the url path is not the user, but a group. To create groups in other words to create an one level namespace is possible in many of the services. So the url does not necessarily start with the user. But GitPitch handles that.

Common:
```
https://gitlab.com/$group/$repo
https://github.com/$group/$repo
```

"New" in GitLab
```
https://gitlab.com/$group/$repo
https://gitlab.com/$group/$subgroup/$repo
https://gitlab.com/$group/$subgroup/.../$nth-subgroup/$repo
```

Cheers Vaci

**Comment by gitpitch** [comment]
@vjanoch thanks for the additional information about subgroups. Based on what you have described and what I have just read in the GitLab docs I do not currently see a clean or backward-compatible solution to add support for this feature to GitPitch.

However I will give it some further thought and update this thread with any new thoughts that come to mind.

**Comment by gitpitch** [comment]
At this time, GitPitch will not be adding support for this GitLab-specific feature. Closing issue as will-not-fix. If I revisit this decision at any point I will update this thread.

**Comment by joelmarty** [comment]
I found out a workaround : If you url encode the '/' between group and subgroup it works.
For instance, for the following repo:
```
https://gitlab.com/$group/$subgroup/$repo
```
you can give to gitpitch the url:
```
https://<gitpitch_host>/$group%2F$subgroup/$repo
```
I have tested that with a private gitpitch instance, not sure about the gitpitch.com service.

**Comment by gitpitch** [comment]
Hi @joelmarty thanks for sharing this useful tip. @vjanoch if you are still working with GitLab sub-groups on GitLab.com it would be interesting to find out if Joël's workaround works using gitpitch.com.

**Comment by swdevbali** [comment]
Ugh, this is not good. Subgroup is core to our business on writing courses. Subgroup make it easy for us

**Comment by gitpitch** [comment]
Hi @swdevbali did you try the workraround described by @joelmarty on this thread? If so, did it work?

**Comment by swdevbali** [comment]
Hi,

well not now though. I am using pro atm, and building the doc locally :)
That's good for me for now

Thanks!
