### ISSUE TITLE
Offline download includes 3 versions of reveal.js

### ISSUE THREAD

**Issue by evanwill** [gitpitch/gitpitch#103]
Testing out using <https://gitpitch.com/evanwill/pitch-test/master>, clicking the "Offline" icon downloads a `.zip` package with all assets. However, `PITCHME/assets/reveal.js/` includes `3.3.1`, `3.4.1`, and `3.5.0`. 

Is there any reason to download all three versions? This adds a lot to the download size, in particular `reveal.js/3.3.1` is 27MB unpacked.

**Comment by gitpitch** [comment]
Hi @evanwill thanks for getting in touch. Only a single version of the library is required. Which version depends on whether the `PITCHME.yaml` specifies a preferred `revealjs-version`. If not it's the default version, which is currently 3.5.0.

I need to prune the unused versions of the library from the zip when I generate it. I'll keep this issue open until I get to that. Thanks for reminding me.

**Comment by gitpitch** [comment]
Hi @evanwill I've just implemented some pretty aggressive asset pruning for GitPitch offline bundles that solves the asset size problem you have reported here.

For example, you reported your sample presentation at 27MB unpacked is now just a 2.5MB download and 5MB unpacked.

Thanks for bringing this to my attention. This patch is live on _gitpitch.com_ and thanks to you all GP users can enjoy the benefits.

**Comment by gitpitch** [comment]
Closing issue as resolved.
