### ISSUE TITLE
Vertical slides cannot be skipped if ever visited

### ISSUE THREAD

**Issue by zeljkot** [gitpitch/gitpitch#104]
I am using vertical slides for additional information about the topmost slide. If I press the right arrow on the topmost slide, then the additional slides will be skipped. However, if I ever open one of the additional slides, then they cannot be skipped - left and right arrow moves between the additional slides, even if I open the topmost slide again. Additional slides are useful to adjust the length of a presentation or to quickly move between the topics by using only the topmost slide, so this behavior breaks its purpose.

I would expect that 
- The right arrow always jumps to the next first-row slide.
- Down arrow and space should go to the next vertical slide, and on the last vertical slide to the next horizontal slide
- The left arrow always jumps to the previous first-row slide.
- Up arrow should go to the previous vertical slide, and on the topmost vertical slide to the previous slide (either vertical or horizontal)

Same rules should apply to code highlighting, where each highlight is equivalent of one vertical slide.

Example: https://gitpitch.com/pitchme/slideshow/github/zeljkot/presentations/master?p=swagger#/6

**Comment by gitpitch** [comment]
> However, if I ever open one of the additional slides, then they cannot be skipped...

Hi @zeljkot you can skip over any series of vertical slides (or fragments, including code frags) using the `Shift` key.

### 1. Jump between top-level presentation topics

If you press the `Shift` key plus the `left` or `right` arrow key you can escape from a deep vertical stack (or fragments) and move on to the next (or previous) top-level topic in your presentation.

### 2. Jump to top (or bottom) of a vertical slide stack

If you press the `Shift` key plus the `up` or `down` arrow key you can jump to the top or the bottom of a vertical stack of slides respectively.

This is probably best understood by experiencing it, so I suggest you try it out. You will see that you can quickly move between top-level topics or up and down vertical slide stacks with ease. If you try this, let me know how you get on.

**Comment by zeljkot** [comment]
That helps, but there is an issue with arrow navigation consistency.

**First issue: moving between code blocks**

Open slide 6 from the link and press space.
* Right arrow shows next code highlight
* Left arrow shows the previous slide rather than previous code highlight 

**Seconds issue: moving between horizontal slides**

Refresh the page go to page 6.
* Right arrow open page 7.
* Left arrow opens page 6.

Now press space until you reach page 7.
* Left arrow on page 7 opens code rather than page 6.
* Right arrow on page 6 opens code rather than page 7.

**Comment by gitpitch** [comment]
Hi @zeljkot thanks for the additional feedback. I have been able to reproduce both of the issues you have reported here. When time permits I will investigate further and update this thread with what I find.

**Comment by gitpitch** [comment]
I believe these deck navigation issues were resolved a long time ago. If not, please feel free to reopen this thread. Thanks, David.
