### ISSUE TITLE
UML diagrams

### ISSUE THREAD

**Issue by zeljkot** [gitpitch/gitpitch#105]
Add support for UML diagrams, PlantUML-style. There are similar issues for [Github](https://github.com/gitlabhq/gitlabhq/issues/9550) and [Gitlab](https://gitlab.com/gitlab-org/gitlab-ce/issues/4048). [Mermaid](https://github.com/knsv/mermaid) might be the possible solution.

**Comment by baez90** [comment]
Why not integrating PlantUML itself?
There's a [Maven repository](http://plantuml.com/download) where you can get the PlantUML.jar.

As there's already some parsing for images and a few other special things I think it should be possible to extend that for PlantUML to render `.png` files from inline PlantUML or maybe also included `.plantuml` files?

Rendering it to `.svg` would be a great Pro feature?

**Comment by gitpitch** [comment]
PlantUML support is now available. Available to Pro + Lite [subscribers](https://gitpitch.com/pricing). See the [UML Diagrams](https://gitpitch.com/docs/rich-media-features/uml-diagrams) guide for details.

![gitpitch-plantuml](https://user-images.githubusercontent.com/19169584/53063146-b9c77800-34f5-11e9-9489-d7acc11a80b2.gif)

You can view this sample GitPitch slide deck live [here](https://gitpitch.com/gitpitch/feature-demo/uml-diagrams).
