### ISSUE TITLE
Avoid jumps between nearby code blocks

### ISSUE THREAD

**Issue by zeljkot** [gitpitch/gitpitch#106]
Sometimes when I highlight two code blocks that are near or overlapping, the code in the window "jumps" up or down although both successive blocks can fit into Window. See example here:

https://gitpitch.com/pitchme/slideshow/github/zeljkot/presentations/master?p=swagger#/10/1

The presentation will look smoother if this can be avoided; for example, I could set the first line that should be visible. Scrolling algorithm should take first visible and last highlighted line rather than first and last highlighted line.

**Comment by gitpitch** [comment]
Closing RFE.
