### ISSUE TITLE
Any more information on how Remote Control Navigation is supposed to work?

### ISSUE THREAD

**Issue by jerdog** [gitpitch/gitpitch#107]
I am seeing [this](https://github.com/gitpitch/gitpitch/wiki/Remote-Control-Navigation) but no info on what dependencies there are here... Or how you connect to your presentation to control it.

**Comment by gitpitch** [comment]
Hi @jerdog beyond [activating the setting](https://github.com/gitpitch/gitpitch/wiki/Remote-Control-Navigation) you found in your `PITCHME.yaml` all you should have to do is follow whatever setup/activation instructions come with your specific remote control device: Logitech, Kensington, etc. Often that means just plugging the receiver for your remote control device into the USB port on your laptop or computer.

**Comment by jerdog** [comment]
Ahh ok. It seemed to infer that you could use your phone/tablet as a remote.

On 8 Sep 2017 20:41, "David Russell" <notifications@github.com> wrote:

Hi @jerdog <https://github.com/jerdog> beyond activating the setting
<https://github.com/gitpitch/gitpitch/wiki/Remote-Control-Navigation> you
found in your PITCHME.yaml all you should have to do is follow whatever
setup/activation instructions come with your specific remote control
device: Logitech, Kensington, etc. Often that means just plugging the
receiver for your remote control device into the USB port on your laptop or
computer.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gitpitch/gitpitch/issues/107#issuecomment-328246562>,
or mute the thread

**Comment by gitpitch** [comment]
> Ahh ok. It seemed to infer that you could use your phone/tablet as a remote.

I've added examples of remote control devices (Logitech, Kensington, etc.) to the Wiki to make it clearer what kinds of devices we are talking about.

You still might be able to use your phone or tablet by using a service like [remot.io](http://remot.io). I've never used it myself but it might be worth trying. If you do I'd appreciate it if you can let me know how it goes.
