### ISSUE TITLE
Slide image backrounds do not work

### ISSUE THREAD

**Issue by fladd** [gitpitch/gitpitch#109]
Look here: https://gitpitch.com/fladd/stress-nf

While normal images show, slide background images do not show (although they are in the same location). They do work offline, though.

**Comment by gitpitch** [comment]
Hi @fladd I just looked over your `PITCHME.md` and you do not seem to be using the recommended syntax for slide background images, as documented on the [Wiki here](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background).

Try replacing your syntax that looks like this:

```
+++
<!-- .slide: data-background-image="images/CAN_NF_Studies.png" data-background-size="contain" -->
```

With the recommended GitPitch syntax, for example:

```
+++?image=images/CAN_NF_Studies.png&size=contain
```

This is more concise. And should also work :-) Let me know how it goes.

I also recommend reading the [image sizing and scaling](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#slide-image-sizing--scaling) section of the Wiki so you can get the most out of your images.

**Comment by fladd** [comment]
Thanks for the quick reply. It indeed does work now. I was not aware that the offline version changes the syntax of the Markdown file. I don't think this is documented anywhere.

It would be great to have a better way to work offline though.

**Comment by gitpitch** [comment]
Agreed, there is definitely room-for-improvement in the [Developing Offline / Locally](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally) page on the Wiki.

It does briefly explain differences with regards paths for embedded images. But it does not yet explain the differences for background image syntax.

> It would be great to have a better way to work offline though.

Can you elaborate, what have you in mind?

**Comment by fladd** [comment]
Well, literally anything that does not change the syntax of the markdown files :-)

I like Gitpitch, but I sometimes have presentations that are not (yet) ready for the public. I would like to prepare those offline, present them somewhere from my offline version, then, when it can be shown to public, I would like to push the whole thing to GitHub, without changing anything of the source files.

Right now, it is the other way around. It can only go from GitHub to offline.

**Comment by gitpitch** [comment]
Hi @fladd thanks for this, it's very helpful for me to get this kind of feedback.

Currently online and offline syntax can not be the same. Offline presentations are static sites, there is no processing component. And offline assets clearly can not live at the same location as online assets, hence the differences you have encountered.

I'll need to give this further thought to see how or if changes can be made to improve the offline workflow. I'll update this thread if I make any progress on this.

Just fyi, I typically develop all of my presentations in a feature branch. These feature branches are temporary and removed once the presentation goes live. The branch allows me to develop my presentation content and preview changes online. When I'm ready to go live with the presentation I merge (with squash) the feature branch into the public presentation branch or master.

While not truly private like you get when working offline, temporary feature branches for developing presentation content are an alternate option you may want to consider. See the [clean commit history](https://github.com/gitpitch/gitpitch/wiki/Clean-Commit-History) page for related tips.

**Comment by fladd** [comment]
Thanks for the detailed explanation.

Yes, I would work the same if I could. But some content you just don't want to have publicly available in any form. I was aiming to use GitPitch for "traditional" presentations (those that you give in front of an audience at a conference or meeting). Only after I have given the presentation (or directly before), I want things to be on the internet (if at all).

An offline solution could also mean that users have to install something for it. That would (at least for me) not be a problem. I like the feature set of GitPitch more than the fact that it works with Git I think :-)

**Comment by gitpitch** [comment]
Very interesting feedback @fladd. Given you specific needs (not git) and your preferred workflow (offline) you might want to consider working directly with [reveal.js](https://github.com/hakimel/reveal.js/).

Creating a dedicated offline GitPitch application would be a significant undertaking and as I'm sure you appreciate I already have one of those to devour my time...GitPitch :)

As a workaround has been provided (modify your md syntax), I'm going to close this issue for now And as noted above, if I find a way to support a more streamlined offline-first workflow I'll update the thread.
