### ISSUE TITLE
Parentheses in code presenting annotation

### ISSUE THREAD

**Issue by zeljkot** [gitpitch/gitpitch#110]
Code presenting annotation does not provide a way to put parentheses inside. For example, this does not work:
`@[15-16](skip(5))`
Escaping also does not work:
`@[15-16](skip\(5\))`

**Comment by gitpitch** [comment]
Thanks for reporting this  @zeljkot. I will push a fix for this issue as part of an upcoming GitPitch v2.0 release. Coming soon.

**Comment by gitpitch** [comment]
@zeljkot this issue should be resolved by the latest GitPitch 2.0 release. If you test and verify the fix can you please update or simply close out this issue. Thanks.
