### ISSUE TITLE
Multi-column support like in Remark.js

### ISSUE THREAD

**Issue by chbndrhnns** [gitpitch/gitpitch#111]
I am wondering how difficult it would be to also support [remark.js](https://github.com/gnab/remark)?

**Comment by gitpitch** [comment]
Hi @chbndrhnns thanks for getting in touch. How difficult? From a practical point of view, impossible. But I would like to understand what features you feel remark would give you that are not found in GitPitch today? Perhaps if not the library itself, some of these features could be integrated.

**Comment by chbndrhnns** [comment]
I find the multi-column layouts to be quite easy to define:

```

## What is it and why should I be using it?
--
  | ---
  | layout: false
  | .left-column[
  | ## What is it?
  | ]
  | .right-column[
  | A simple, in-browser, Markdown-driven slideshow tool targeted at people who know their way around HTML and CSS, featuring:
  |  
  | - Markdown formatting, with smart extensions
  |  
  | - Presenter mode, with cloned slideshow view
  |  
  | - Syntax highlighting, supporting a range of languages
  |  
  | - Slide scaling, thus similar appearance on all devices / resolutions .red[*]
  |  
  | - Touch support for smart phones and pads, i.e. swipe to navigate slides
  |  
  | .footnote[.red[*] At least browsers try their best]
  | ]
  | ---
  | .left-column[
  | ## What is it?
  | ## Why use it?
  | ]
  | .right-column[
  | If your ideal slideshow creation workflow contains any of the following steps:
  |  
  | - Just write what's on your mind
  |  
  | - Do some basic styling
  |  
  | - Easily collaborate with others
  |  
  | - Share with and show to everyone
  |  
  | Then remark might be perfect for your next.red[*] slideshow!
  |  
  | .footnote[.red[*] You probably want to convert existing slideshows as well]
  | ]
```

Maybe I am just missing how to achieve similar things with reveal.js and gitpitch?

**Comment by gitpitch** [comment]
Agreed, multi-column layout is a nice feature. GitPitch does not support this out-of-the-box today although you could probably achieve this layout using [custom css](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS).

I'll soon be releasing GitPitch v2.0 and once that release is out the door I'll be turning my attention to new features. Multi-column layouts is on the candidate list. I'll update this thread if it makes it off the list and into a release.

**Comment by tbfe-de** [comment]
I have not (yet) used `reveal`-based gitpitch but I seriously consider to switch over from `remarkjs`, which I have used a lot in the past years for writing presentations (mostly for teaching C++ and Tcl/Tk).

**Two-Column-Layout is also essential to me**, as I use it more often than just occasionally. If I switch to gitpitch I need to find ways to convert the bulk of existing pages automatically. (98..99% would be OK, I would accept to do some very special cases manually).

So I recently looked for how this two-column stuff might be done in `reveal` and found this:

https://stackoverflow.com/questions/30861845/how-to-use-two-column-layout-with-reveal-js 

It seems as if it would not be too hard to get the two column layout.

I usually try to avoid mixing html-markup with markdown, as I like my markdown files to be "readable" in the absence of special rendering. But in this particular case it seems acceptable to me as for `reveal` I had to use

```
<div class="xyz">
...
</div>
```
compared to `remarkjs`, which (only) requires to write

```
.xyz[
...
]
```

It might be an idea to support the above `remarkjs`-specific short-hand for `<div>`s with a special CSS-class in gitpitch 2.0 as an extension, but for two-column-layout the transition to `reveal`-based gitpitch seems easy enough to be done automatically.

**Comment by chbndrhnns** [comment]
Is there a progress on multi-column layouts or is this something that might get shipped with the major upgrade you are planning?

**Comment by gitpitch** [comment]
No progress to report at this time. This RFE remains on the candidate-feature list but it is unlikely to get any of my time until after GitPitch 3.0 is released early in the new year.

**Comment by gitpitch** [comment]
Just a further quick bump on this thread. I've just pushed a small update to the GitPitch Hello World presentation where I make use of a *two-column layout* using basic markup and some very simple custom CSS. I mentioned this was possible earlier in this thread. Now you can see the effect live [here](https://gitpitch.com/gitpitch/gitpitch#/8). And here's a screenshot:

<img width="1436" alt="screen shot 2017-12-14 at 5 13 44 pm" src="https://user-images.githubusercontent.com/19169584/33987104-4709eddc-e0f2-11e7-898a-8142af454b3e.png">

I've also been looking over some presentations that have already been published by the GitPitch Community and [here is a link](https://gitpitch.com/MiguelAlho/LearningChallenge2018) to a very nice presentation that makes great use of *two-column layouts* both for text and images.  

I share these links with you now to demonstrate and provide concrete examples of how you can achieve some of the effects you are after today. Due to the way Reveal currently processes markdown (and more importantly, how it processes anything within markup tags) I suspect that providing a pure markdown-only solution within GitPitch is very unlikely. But as the examples above demonstrate, this feature is still easily achieved within GitPitch today.

**Comment by chbndrhnns** [comment]
Looks really good this way.

I changed the issue title to reflect the content.
Here is the link to the commit for further reference:
https://github.com/gitpitch/gitpitch/commit/ff546d494d80ccc91184f1cfc4a0f63d1cf66eed

**Comment by gitpitch** [comment]
A much better title for this thread, thanks @chbndrhnns .

And I'm glad you like the effect. If you look at the PITCHME.md and custom css in the sample presentations you will see that it is very easy to achieve this effect.

**Comment by gitpitch** [comment]
Thread bump. The recent release of GitPitch [snap layouts](https://gitpitch.com/docs/layout-features/snap-position-layouts/) provides *multi-column* and *multi-row* layout support. This new layout system is extremely flexible and it is now *the recommended way to develop custom layouts* for GitPitch slide content on gitpitch.com.

Some sample slides designed using *snap-layouts*:

![layout-features-inspiration-bio](https://user-images.githubusercontent.com/19169584/43449968-ea956c86-94db-11e8-9720-703394751cda.jpg)
![layout-features-inspiration-process](https://user-images.githubusercontent.com/19169584/43449970-eaf75bf8-94db-11e8-99fc-898209809816.gif)
![layout-features-inspiration-timeline](https://user-images.githubusercontent.com/19169584/43449972-eb2e6fe4-94db-11e8-93fa-ce8f098c3ede.jpg)

![layout-features-inspiration-thanks](https://user-images.githubusercontent.com/19169584/43450099-29239068-94dc-11e8-9abe-f30cd2fe0081.jpg)


For further details, samples, and tips see the new [Layout Features](https://gitpitch.com/docs/layout-features) chapter in the docs.
