### ISSUE TITLE
Support sub-directories

### ISSUE THREAD

**Issue by marcelgleis** [gitpitch/gitpitch#113]
I'd like to have a repo with different PITCHME.md files in different sub-directorys.

Does that make sense to you?

**Comment by gitpitch** [comment]
Hi @marcelgleis it does make sense and you can do that today. See the [Single Repo - Multiple Presentations](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing) page on the GitPitch wiki. If you have any further questions just let me know.
