### ISSUE TITLE
Add code revealing

### ISSUE THREAD

**Issue by EvgenyOrekhov** [gitpitch/gitpitch#114]
I would like to see a feature that would allow me to write one code snippet and reveal more and more of its lines.

To achieve that right now I have to write multiple code snippets with duplicate code, for example: https://github.com/EvgenyOrekhov/talks/blob/master/why-so-functional/PITCHME.md#v20.

**Comment by gitpitch** [comment]
Hi @EvgenyOrekhov you can use the GitPitch [code presenting](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting) feature to gradually reveal more-and-more code in a single slide. 

Specifically to your sample presentation: for example, based on your current slides 5/1 through 5/7 you could replace all of those slides with a single slide with the following code-block and code-presenting markers:

```
$sum = 0; $count = 0;
foreach ($employees as $employee) {
    if ($employee['profession'] === 'programmer') {
        foreach ($employee['skills'] as $skill) {
            if (
                isset($skill['name'])
                && $skill['name'] === 'bash'
            ) {
                $sum += $skill['experience'];
                $count++;
            }
        }
    }
}
$result = $count ? $sum / $count : 0;

@[1]
@[1,2, 14]
@[1-3, 13-14]
@[1-4, 12-14]
@[1-5, 11-14]
@[1-14]
@[1-15]
```

You can apply this same approach throughout your presentation anywhere that you want to gradually reveal more and more code on a single slide. Try it out and let me know how it goes.

Btw, have you checked out the GitPitch blog, the [Let Your Code Do The Talking](https://hackernoon.com/let-your-code-do-the-talking-983906a3a587) blog post? If you view the sample presentation and also the sample `PITCHME.md` for the presentation it may also help.

**Comment by gitpitch** [comment]
Note @EvgenyOrekhov I've just updated the code-presenting markers in the example provided above to correctly match the code block used in your example presentation.

**Comment by EvgenyOrekhov** [comment]
@gitpitch I'm aware of the code presenting feature and it's great, however I have 2 problems with it in the case of using it for code revealing:

- the whole code is shown before the first step
- the dimmed code is still visible

**Comment by gitpitch** [comment]
Ok, thanks for the additional feedback @EvgenyOrekhov. I assumed (incorrectly) that dimming the code would be adequate for your needs. But you want a fully hidden-then-reveal effect. This is not something GP gives you today. Unless you stick with your original approach of using multiple-slides.

I'm not sure how a hidden-then-reveal effect would best be delivered by GP. I'll give it some thought. But for now, I suggest you stick with your current approach.

**Comment by EvgenyOrekhov** [comment]
@gitpitch Regarding the code dimming, a possible solution would be using a CSS class instead of the "style" attribute for dimming. That way a user could just define custom CSS for that class.

Regarding the first issue, a possible solution would be to start code presenting immediately, without showing the whole code first, and if a user wants to show the whole code first, they could use `@[-]` as the first step. Unfortunately, this solution would break backward compatibility. Maybe you have a better idea?

**Comment by gitpitch** [comment]
Thanks again for your feedback @EvgenyOrekhov. 

Any solution will need to be backward compatible with the current code-presenting behavior so I need to give this some further thought. I will update this thread if I find an approach that can deliver the features you're requesting.

**Comment by gregmajor** [comment]
I realize this has been open for quite some time, but I wanted to upvote the idea that there be some way to progressively reveal/unblur code without showing it all at once first.

**Comment by gitpitch** [comment]
I have just pushed experimental support for *Code Revealing*. 

Code revealing is a variation on standard code presenting. It hides all code on the original slide (so you start with a clean slate) and as you step into your code lines of code are revealed (while all other lines of code are entirely hidden). This behavior mirrors the the original feature request on this thread by @EvgenyOrekhov.

##### How does it work?

Code presenting - as you know it today - remains the default behavior for GitPitch slideshows. To disable *code presenting* and enabled *code revealing* for a slideshow you must activate a new `code-reveal` setting in your `PITCHME.yaml`.

For example:

```
code-reveal :  true
```

That is all you have to do. You follow the exact same steps when building your presentation content - see [code presenting](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting) on the Wiki. When this setting is activated, your presentation will enjoy the new behavior.

As noted, this functionality is still experimental. Please try it out and let me know how it goes. Cheers, David.

**Comment by EvgenyOrekhov** [comment]
@gitpitch Just tried it, here is some feedback:

- I want my code to be visible on the original slide if the slide doesn't have any `@[]` markers
- the special `@[-]` marker for showing all lines doesn't work in code-reveal mode
- now I see that on some slides I want code revealing, and on other slides I want code presenting (in the same presentation)

Allow me to propose a different solution that would permit the use of both code revealing and code presenting in the same presentation. What if instead of using the `code-reveal` option in `PITCHME.yaml` one could use a special marker, `@[]` (the empty marker) for example, on the slides that need code revealing?

An example would be:

````md
+++

```
code code code code
code code code code
code code code code
code code code code
```

@[]
@[1]
@[1-2]
@[1-3]
@[-]
````

`@[]` here would hide the code on the original slide and enable the code revealing mode. The following three markers would reveal the specified lines. `@[-]` would reveal the whole snippet.

If there is no `@[]` marker in the beginning, the slide works in regular code presenting mode.

**Comment by EvgenyOrekhov** [comment]
Thinking about it more, to completely remove the need of copy-pasting code snippets, it would be best to support both code revealing and code presenting *on the same slide*. Perhaps by introducing a new syntax for code revealing markers.

**Comment by gitpitch** [comment]
Thanks for this feedback @EvgenyOrekhov . I'll leave the issue open to see what others have to say as clearly there are many variations on the central ideas of presenting and revealing - and I'm not sure what if any yet make sense or can even be achieved.

**Comment by gitpitch** [comment]
GitPitch now supports multiple flavors of code-revealing to cover the various uses cases discussed on this thread. It can be activated for code on individual slides. This approach is more flexible and seems to make more sense than a global setting.  It also means that code-revealing can be used alongside traditional code-presenting in any deck.

To experience this new feature live, see the following [sample slide deck](https://gitpitch.com/gitpitch/pro-code-revealing).

Code-revealing has been released as a *subscriber-only* feature. For more details, including *syntax* and samples, see the [Pro Code Revealing Guide](https://gitpitch.com/docs/code-features/pro-code-revealing).

**Comment by EvgenyOrekhov** [comment]
@gitpitch ["Code Revealing Sow Mode"](https://gitpitch.com/gitpitch/pro-code-revealing#/4) still behaves like code presenting, it shows all code.

![2019-03-18-173639_960x733_scrot](https://user-images.githubusercontent.com/8045060/54538629-a351f680-49a5-11e9-8a30-97d39cf201ed.png)

I want to be able to reveal code like in this example: https://gitpitch.com/EvgenyOrekhov/talks?p=why-so-functional#/6/1

**Comment by gitpitch** [comment]
> "Code Revealing Slow Mode" still behaves like code presenting, it shows all code.

In what presentation are you seeing the problem, can you share a link?

You may need to clear the cache in your browser to ensure your browser is rendering the slide show using the latest javascript and css assets.

**Comment by EvgenyOrekhov** [comment]
@gitpitch https://gitpitch.com/gitpitch/pro-code-revealing#/4

1. All code is hidden, just what I expect.
2. I press the "down arrow" key on the keyboard.
3. I see all code and the first line is highlighted (like on the above screenshot), which is not what I expect. I expect to see only the first line.
4. I press the "down arrow" key on the keyboard.
5. I see all code and lines 3 and 4 are highlighted, which is not what I expect. I expect to see only lines 1-4.

I cleared the cache, it didn't help.

**Comment by gitpitch** [comment]
Any code line in focus due to a code fragment marker is visible-and-highlighted. Any line not in focus due to a code fragment marker is visible-but-faded. This is what is shown in the screenshot animation. And this is the intended behavior.

To address your point 5, what lines are visible-and-highlighted depends entirely on the code fragment markers in use by the deck. In the sample deck, you see lines 3 and 4 visible-and-highlighted because that is how the sample code fragment markers are defined for this sample deck.

You would have to set your own sequence of appropriate code fragment markers if you wanted to see some different behavior, such as lines 1-through-4 visible-and-highlighted.

**Comment by gitpitch** [comment]
Evgeny, I have updated the docs to clearly demonstrate how you can achieve the effect you are trying to achieve.

Here is an updated screenshot of Code Revealing slow-mode in action:

![code-mode-slow](https://user-images.githubusercontent.com/19169584/54577333-e788d980-4a2d-11e9-9202-6c8750c1b3e2.gif)

To achieve this effect over the original version all I did was adjust the ranges on the code-fragment markers. You can see exactly how those ranges work in the docs. Those updated docs can be found [here](https://gitpitch.com/docs/code-features/pro-code-revealing).

FYI, I have also adjusted the opacity levels to create stronger contrast between code-in-focus and code-out-of-focus. This change is activated whether code-presenting or code-revealing.

**Comment by EvgenyOrekhov** [comment]
@gitpitch I think that will suffice. Thank you!
