### ISSUE TITLE
Hyperlink color in speaker notes

### ISSUE THREAD

**Issue by gabrieljoelc** [gitpitch/gitpitch#115]
Steps to reproduce:
1. Create deck with white theme
1. Add speaker notes that include an URL
1. Run the deck with the `n=true` query string parameter
1. Navigate to the slide with the speaker notes

It's using the
```
.reveal a { #42affa }
```
hyperlink color and it's hard to see on the speaker notes modal.

https://gitpitch.com/gabrieljoelc/herocker/master?grs=github&t=white&n=true

macOS Sierra: 10.12.6 (16G29)
Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by gitpitch** [comment]
@gabrieljoelc thanks for the feedback. I will look into this over the next few days. If you have a link to a sample presentation that demonstrates the issue you've reported can please share that link here. Thanks.

**Comment by gabrieljoelc** [comment]
@gitpitch oops. I forgot to add that. Description updated.

**Comment by gitpitch** [comment]
I've just pushed a patch that improves the rendering contrast for links shown within inline speaker notes. Interestingly, the problem you reported affected a number of GitPitch themes, particularly the `white` and `beige` themes. So thank you again for bringing this to my attention.

@gabrieljoelc  can you please test and verify, then update or close out the issue thread. Thanks.

**Comment by gabrieljoelc** [comment]
I verified white, beige, and black.

Thanks!
