### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by m1guelpf** [gitpitch/gitpitch#119]
Is there a way to use this with private repositories?

In an ideal world, I should be able to append a token to the URL to get access...

**Comment by gitpitch** [comment]
Hi @m1guelpf thanks for getting in touch. Currently GitPitch does not support access to private repos. However, I am currently working on GitPitch 3.0. That release will introduce a number of new features, including subscription-only features that will include support for private repos.

I do not yet have a release date for you but I will update this thread and the [GitPitch blog](https://medium.com/@gitpitch) with further news as it becomes available. You can reach out to me anytime by e-mail if you have any questions. And I would be very interested to learn more about your own use-case for GitPitch and private-repos. Thanks, David.

**Comment by m1guelpf** [comment]
@gitpitch Here are some use cases:

- I have a private repository with the code of my app. I want to host the presentation for the service in that repository.

- I am going to do a talk on a conference, and I want to keep my slides private until the day of the talk.

**Comment by m1guelpf** [comment]
@gitpitch As a temporal workalround, maybe we could accept a token as a GET parameter and use it to connect to the provider.

**Comment by gitpitch** [comment]
Thank you for all of this feedback @m1guelpf, very helpful.

Practically speaking there is no quick workaround we can make to support private repos at this time. But the real work that is required is already underway and I will update this thread as soon as I have news to announce.

**Comment by wojtekkutylacc** [comment]
Thumbs up from me as well, @gitpitch — I work at a school and I would like to be able to use this for our internal training materials (and for materials for students). It's ideal, other than the fact that  repos have to be open... I'll watch this space :)

**Comment by m1guelpf** [comment]
@wojtekkutylacc I have created an alternative called Webslides that allows you to provide any data source, so you can append tokens and that kind of things, you can check it at [slides.zone](https://slides.zone). Please keep in mind that it's still on beta :smile:

**Comment by wojtekkutylacc** [comment]
@m1guelpf interesting, can I see any examples before I register?

**Comment by m1guelpf** [comment]
@wojtekkutylacc I created an example presentation (https://slides.zone/show/example) that gets the source directly from a private slides repository in my account.

**Comment by wojtekkutylacc** [comment]
@m1guelpf nice. I'll look into this. Thanks.

**Comment by gitpitch** [comment]
A quick update on this thread regarding GitPitch private repository support. I've just announced GitPitch Pro. Coming soon. A subscription service that unlocks Git private repos to deliver public, private, and password-protected presentations and much, much, more. Read the following GitPitch [blog post for details](https://medium.com/@gitpitch/gitpitch-pro-coming-soon-bda8c71ca9ea).

**Comment by gitpitch** [comment]
GitPitch support for private Git repos is now available. Full access beta program has begun. Beta details [here](https://medium.com/@gitpitch/your-invitation-to-join-gitpitch-pro-beta-a613008c9c75). Additional details on the new [website](https://gitpitch.com). @wojtekkutylacc

**Comment by Ryuno-Ki** [comment]
So this can be closed?

**Comment by gitpitch** [comment]
The official documentation for private repository support is [available here](https://gitpitch.com/docs/pro-features/security).
