### ISSUE TITLE
Git repo not found on GitHub

### ISSUE THREAD

**Issue by chendachao** [gitpitch/gitpitch#12]
When I open https://gitpitch.com/onetabbeyond/opencpu-spark-executor#, it shows below issue. DO you have any ideas?
![capture](https://cloud.githubusercontent.com/assets/18575321/19111518/8d0493f8-8b32-11e6-88d9-524370e1bef9.PNG)

**Comment by gitpitch** [comment]
Hi @chendachao you have a small typo in the URL. The correct URL for that slideshow is:

[https://gitpitch.com/onetapbeyond/opencpu-spark-executor](https://gitpitch.com/onetapbeyond/opencpu-spark-executor)

Notice, that is `tap` not `tab` in the word `onetapbeyond`.

**Comment by gitpitch** [comment]
@chendachao can I ask, where did you get that broken URL? If the broken URL is used somewhere in documentation about GitPitch can you please let me know so I can fix the link. Thanks.

**Comment by chendachao** [comment]
@gitpitch thanks for correcting me, it's my fault, sorry about that, I type a wrong url from https://github.com/gitpitch/gitpitch's README.md picture by mistake.

BTW I created a PITCHME.md [here](https://github.com/chendachao/git-test/tree/dev), but can't show a slide, am I missed something?

**Comment by gitpitch** [comment]
Hi @chendachao no problem, typos happen to all of us. As for your presentation, it's working fine, try this in your browser:

```
https://gitpitch.com/chendachao/git-test/dev
```

Generally speaking, a GitPitch URL is formed like this:

```
https://gitpitch.com/user-name/repo-name/branch-name
```

So in the case of your presentation, you need to substitute `chendachao`, `git-test`, and `dev` for `user-name`, `repo-name`, and `branch-name` respectively.

**Comment by chendachao** [comment]
@gitpitch it works fine, it's really amazing, thank you so much.

I think you can make it clear in readme.

**Comment by gitpitch** [comment]
@chendachao glad to hear everything is working for you now. Remember to check out the [GitPitch Wiki](https://github.com/gitpitch/gitpitch/wiki) which details how you can work with lots of GitPitch presentation features.

**Comment by chendachao** [comment]
@gitpitch Got it, thank you.
