### ISSUE TITLE
Relative links to images are incompatible with GitHub

### ISSUE THREAD

**Issue by EvgenyOrekhov** [gitpitch/gitpitch#121]
I have a repo with multiple presentations: https://github.com/EvgenyOrekhov/talks

Each presentation has its own `img` directory, e. g.
https://github.com/EvgenyOrekhov/talks/tree/master/can-we-live-without-this

[GitPitch's wiki](https://github.com/gitpitch/gitpitch/wiki/Image-Slides) says I should use links to images that are relative to the **repo**, e. g. I should use

```md
![Edsger W. Dijkstra](can-we-live-without-this/img/dijkstra.jpg)
```

in my `can-we-live-without-this/PITCHME.md` file.

But [GitHub's help](https://help.github.com/articles/about-readmes/#relative-links-and-image-paths-in-readme-files) says I should use links that are relative to the **current file**.

As a result, all relative images work on GitPitch, e. g.
https://gitpitch.com/EvgenyOrekhov/talks?p=can-we-live-without-this#/1

but don't work on GitHub, e. g.
https://github.com/EvgenyOrekhov/talks/blob/master/can-we-live-without-this/PITCHME.md#can-we-live-without-this

I expect relative links to images to work the same way on GitPitch and on GitHub, so a user could watch a presentation on GitHub as well.

**Comment by gitpitch** [comment]
Thanks for this feedback @EvgenyOrekhov I've just looked at the docs you shared and there is definitely an inconsistency between how GitHub and GitPitch handle relative links in their markdown files.

Resolving that inconsistency now is problematic. To do so would run the risk of breaking existing GP presentations that depend on the currently documented behavior. And I see no way for GP to simultaneously handle the legacy behavior and this new GitHub-compatible behavior given `PITCHME.md` uses standard markdown syntax for links.

So I agree that ideally there should be no inconsistency. And it would be nice to be able to watch any presentation+images on GitHub as well. But the priority has to be given to viewing fully-rendered, fully-functional GitPitch presentations.

That said, I remain wide open to resolving this inconsistency if a seamless solution can be found.

**Comment by alexweissman** [comment]
The issue with relative image links also comes up when [developing and testing locally](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally).  The docs seem to assume that we will always be running our project directly from the document root, for example:

`http://localhost/#/1`

However, I run all of my web projects in separate subdirectories of my web server's document root.  For example:

`http://localhost/essential-tools-for-modern-php/#/1`

If I place an image in `assets/md/assets/image1.png`, and then reference it in my `PITCHME.md` as:
```
![My image](assets/image1.png)
```

Then it is rendered in the browser as:

```
<img src="assets/image1.png" alt="My image">
```

This does not resolve correctly since my project's URL is prefixed with `essential-tools-for-modern-php/`.  

Perhaps there should be some sort of configuration option for prefixing asset URLs?

**Comment by nathanallen** [comment]
This seems like a possible use case for the html [`<base>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base).

**Comment by gitpitch** [comment]
Thanks everyone for all the feedback. The original issue will likely never be `solved` in the sense that the problem, while acknowledged in the context of viewing `PITCHME.md` on GitHub/Lab etc. can not be solved without breaking existing presentations. And proper rendering of presentations takes priority over any other type of rendering for all the obvious reasons. 

With regards the shortcomings when [developing and testing locally](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally) again I fully acknowledge these issues and I'm already working on delivering a solution that will make working offline entirely seamless with working online. So the issues raised above will simply no longer exist.

As a side note, using the [clean git history](https://github.com/gitpitch/gitpitch/wiki/Clean-Commit-History) approach to presentation development can be used in some situations as a workaround to these problems today.

Anyway, keep an eye out for more news on new offline solutions in the new year. I'm going to close this specific issue (incompatibility between GitPitch and GitHub rendering) as will-not-fix.
