### ISSUE TITLE
Finer-granularity code fragments

### ISSUE THREAD

**Issue by jacg** [gitpitch/gitpitch#122]
Thank you for this *very* interesting tool.

I need the ability to highlight **portions** of lines of source code. AFAICT this is currently not supported.

Is this something that you think you might support in the future?

**Comment by gitpitch** [comment]
> Is this something that you think you might support in the future?

Hi @jacg thanks for getting in touch and for this very interesting request. Undeniably, a nice feature. But more than a little bit tricky to implement today at least. So the short answer (and probably unsatisfactory answer :) is maybe. 

I'll add it to my list. For know I'll keep this thread open which will allow other users to up-vote the request which will help me gauge the overall level of interested in this feature within the broader GitPitch community. Thanks again for this feedback. David.

**Comment by jacg** [comment]
David,

Thanks for your reply. *Maybe* is a fine answer, especially with the background information that it's *a little tricky to implement today*: that tells me that I shouldn't hold my breath, which is valuable information.

While I wasn't really expecting it, there was at least an outside chance that you might have answered "Oh, yes, that's easy, I'll do it tomorrow ... no wait ... it's *so* easy that I've done it just now. There, it's ready." :-)
