### ISSUE TITLE
JDK 1.9 support

### ISSUE THREAD

**Issue by lexsys27** [gitpitch/gitpitch#124]
Is JDK 1.9 supported for this project?

I have several issues building the project using JDK 1.9 & sbt 0.13 and would like to know if this configuration is supported before posting them.

**Comment by gitpitch** [comment]
Hi @lexsys27 the short answer, no JDK 1.9 is not supported. GitPitch will first need to be upgraded to PlayFramework 2.6. It's on my todo list. And a number of [known issues](https://github.com/playframework/playframework/issues/7879) with that upgrade would still need to be addressed. 

For now you must build using JDK 1.8.

**Comment by gitpitch** [comment]
@lexsys27 quick question, do you mind if I ask how you are currently using GitPitch? I just like to understand why and how people are hosting their own GitPitch servers. Thanks.

**Comment by lexsys27** [comment]
@gitpitch Sure! I deliver onsite trainings on Cloud Foundry technology and would like materials to be available from the local network for multiple students during the training. 

For now I have played with GitPitch for only one day but it looks promising!

**Comment by lexsys27** [comment]
I am not sure for now how the final configuration will look like and doing some prototyping at this moment. GitLab CE is one of possible choices but I look at gogs.io too. Gogs is simpler and maybe better choice if I want to bring separate instance of VCS to the training.

Two other features I am interested in are showing presentations from private GitHub repo and using custom URL.

**Comment by gitpitch** [comment]
Very interesting, re. configuration. Happily GitPitch gives you a lot of flexibility to try out different options as you can use any of the supported Git servers locally: GitHub Enterprise, GitLab CE, Bitbucket Server, Gitbucket, Gitea, or Gogs.

As for showing presentations from private repos, this is something that I am working on right now as part of a new major GitPitch release and I will be making an announcement in the next couple of months. I will update this thread once that news is out.

Finally, I would be interested to understand what exactly you have in mind when you express interest in using custom URLs? Can you describe your use case a little bit so I can better understand what you need?

**Comment by lexsys27** [comment]
By the way, yesterday I have successfully deployed GitPitch to my local server and served presentation from the private repo on GitHub. The PDF exporting feature is not working yet but I am happy with the progress :)

Custom URL has a form of _slides.some-training.company.com_ where _company.com_ is one that delivers the training.

You have built an amazing tool and I have a lot of ideas how to use it!

**Comment by gitpitch** [comment]
Thanks for all of this positive feedback. It's great to hear you are making good progress with your initial GitPitch configuration and testing. Let me know if you remain stuck with the PDF printing config. Definitely best to contact me directly by e-mail if were are going to debug your environment/config.

I have made a note of your custom URL suggestion and will evaluate it when time permits. And I'm wide open to any further ideas you might have so please feel free to get in touch anytime.
