### ISSUE TITLE
Line break before @title breaks code highlighting

### ISSUE THREAD

**Issue by jeantil** [gitpitch/gitpitch#125]
Hi, 

just a heads up that adding a line break between a vertical slide delimiter `+++` and a custom title `@title[custom title]` partially breaks markdown rendering 

* nested lists don't work anymore
* whitespace indentation is stripped from code blocks

this is not a blocker as simply making sure the @title is on the line immediately after the `+++` separator fixes everything but an easy way to waste a couple hours writing nested lists as html and replacing all spaces by non breakable spaces :)

**Comment by gitpitch** [comment]
Hi @jeantil thanks for reporting this issue. Can you provide me with a link to a broken presentation that demonstrates the problem you reported? Note, you can use a commit id/hash on any GitPitch url (in place of the branch name) to point at a specific version of a presentation. So hopefully you should be able to point me back at where all of your troubles began.

**Comment by jeantil** [comment]
hi @gitpitch 

here you go : 
- [gitpitch presentation of the issue (and one more discovered making the presentation)](https://gitpitch.com/jeantil/gitpitch-125/master#/)
- [corresponding PITCHME.md](https://github.com/jeantil/gitpitch-125/blob/master/PITCHME.md)

the new issue I discovered while making this presentation is that it is not possible to make code blocks or code slides representing markdown without resorting to some dirty tricks. see the [last slide](https://gitpitch.com/jeantil/gitpitch-125/master#/7) for a basic example of the issue with rendering. 
Trying to make a code block of markdown which itself contains a code block is even worse :)

**Comment by jeantil** [comment]
This was fixed in the latest update as mentioned by @gitpitch in [this comment](https://github.com/gitpitch/gitpitch/issues/126#issuecomment-343061549)

all markdown now renders properly whether you skip a line between the slide delimiter `---` or `+++` and the `@title`, or not.

**Comment by gitpitch** [comment]
Thanks @jeantil for bringing these issues to my attention, for providing test cases, and for testing and verifying the patches. Much appreciated. David.

**Comment by jeantil** [comment]
Well providing test cases and verifying fixes is the least I could do :) thanks for your software !
