### ISSUE TITLE
Quoting gitpitch extended language or markdown renders incorrectly

### ISSUE THREAD

**Issue by jeantil** [gitpitch/gitpitch#126]
I am creating this issue after I discovered it is not possible to quote gitpitch markdown with extension. 

The following code 

    ---
    @title[can't quote markdown]

    ```markdown
    @title[can't quote markdown]
    ## it has working titles
    ```
    here is the result of a naive attempt at quoting markdown
    
renders like so 
![image](https://user-images.githubusercontent.com/22979/32541190-34e4fce0-c46f-11e7-8612-e4eab958084d.png)
@title is preprocessed and I haven't found a way to prevent it. 

For more complex markdown examples the rendering fails completely. 

Using the same trick i did in this message to quote markdown (using 4 spaces in front of the code instead of using backtick delimiters) doesn't work either (see https://gitpitch.com/jeantil/gitpitch-125/master#/6/2)

Prefixing all the markdown lines with a non breaking space makes it render properly though.

**Comment by gitpitch** [comment]
You can't currently prevent @title being preprocessed. And without your _spacing trick_ GitPitch can not render regular Markdown code blocks. It's a known issue/feature/bug. This is the only know workaround. I should update the Wiki to save you/others time in future.

**Comment by jeantil** [comment]
It's sad because it makes making presentations on gitpitch harder to make, documenting the workaround would definitely be a life saver. 

For information, I first looked it up in the following places in this order 
- https://github.com/gitpitch/gitpitch/wiki/Slide-Markdown
- https://github.com/gitpitch/gitpitch/wiki/Code-Slides

Also I tried using the Code Delimiter Slides to work around the issue but that breaks too and there is no way around it as using non-breaking spaces in actual source code is not very practical... it might be worth a mention in https://github.com/gitpitch/gitpitch/wiki/Code-Presenting

**Comment by gitpitch** [comment]
Agreed. Until today only one other person has contacted me in the past 18 months interested in doing what you are doing, presenting Markdown code within a GitPitch presentation. So this issue just didn't make it to the top of my list. You looked in all the right places. That's exactly where I'll add some notes to make this a much smoother path for future presenters.

I'll update this thread once that doc is in place.

**Comment by gitpitch** [comment]
@jeantil I have just pushed a number of updates with the following changes:

1. Support for clean rendering of raw markdown within slides. See details on the [Wiki here](https://github.com/gitpitch/gitpitch/wiki/Displaying-Markdown-Within-Markdown).

2. Fixes for issues relating to rendering problems due to @title placement on slide.

These updates are now live. Can you please test and verify and then let me know how it goes. Thanks.

**Comment by jeantil** [comment]
Hi @gitpitch, 

I have read the documentation and what you said about what is actually supported versus not supported. 
For the sake of completeness I tested most all the variations I could think of, here are the results.

* Code Delimiter Slides
  - ✅ render [indented code blocks](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/4/1)
  - ✅ render [backtick fenced code blocks](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/4/5) as per documentation (displaying only 2 backticks)
* Static markdown code blocks
  * containing indented code blocks 
     - ✅ renders using an [indented code blocks](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/2/1) (effectively nesting the indented code blocks works fine)
     - ✅ renders using a [backtick code block with a non-breaking space prefix on first line](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/2/2)
     - ❌ renders using a [naive backtick code block](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/2/3). Total failure, leaking in further slides
  * containing backtick fenced code blocks 
    -  ✅ renders using  an [indented code block](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/5/1)
    -  ❌ renders using  a [backtick code block with non-breaking space on all lines](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/5/2) Partial failure, contained in the slide.
    -  ❌ renders using  a [backtick code block with non-breaking space on the first line](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/5/3) Partial failure, contained in the slide.
    -  ❌ renders using  a [naive backtick code block](http://localhost:9000/jeantil/gitpitch-125/126?grs=github&t=white#/5/'). Total failure, leaking in further slides

**Comment by gitpitch** [comment]
Thanks again for this additional feedback. There seems to be a little confusion. Note the **bolded** statement on the new [Displaying Markdown Within Markdown](https://github.com/gitpitch/gitpitch/wiki/Displaying-Markdown-Within-Markdown) Wiki page:

> The **only supported way to render raw markdown code** within a slide is to **use a code delimiter** that points to a markdown file within your repo.

The set of tests you have created to test static markdown code blocks **do not use a code** delimiter and therefore do not fall within the supported feature set.

The only way I can _ensure_ safe rendering of raw markdown is to own the entire rendering process, which is something I can do when code delimiters are being used. 

I strongly advise against using static code blocks to render raw markdown. I have updated the Wiki page with an explicit warning not to use static code blocks when rendering raw markdown.

**Comment by jeantil** [comment]
Don't worry I got that, just wanted to be thourough. But I have indeed converted my presentation to use code delimiter slides and indented code blocks (so I don't have to explain the backticks :) )

**Comment by gitpitch** [comment]
Great. Closing issue as resolved. See new [Displaying Markdown within Markdown](https://github.com/gitpitch/gitpitch/wiki/Displaying-Markdown-Within-Markdown) page on the Wiki for details.
