### ISSUE TITLE
Scala generics in code fence parsed as markdown

### ISSUE THREAD

**Issue by jeantil** [gitpitch/gitpitch#127]
Trying to render 
  
    ```scala
    sealed trait Option[+T]
    case class Some[T](value:T) extends Option[T]
    case object None extends Option[Nothing]
    ```

[renders incorrectly](https://gitpitch.com/jeantil/gitpitch-125/127#/)
```
sealed trait Option[+T]
case class Some<a target="_blank" href="value:T">T</a> extends Option[T]
case object None extends Option[Nothing]
```
I tried various workarounds to no avail.

When using marked.js + highlight.js directly the code renders fine ... see https://github.com/jeantil/gitpitch-125/blob/127/index.html for basic html demo.

**Comment by jeantil** [comment]
Note that adding a space between the generic declaration and the constructor renders fine. like so

    ```scala
    sealed trait Option[+T]
    case class Some[T] (value:T) extends Option[T]
    case object None extends Option[Nothing]
    ```

it's unfortunate that such notation doesn't follow the scala style guide :(

**Comment by gitpitch** [comment]
@jeantil latest updates include patch for the issue reported here. Can you please test and verify. Thanks.

**Comment by jeantil** [comment]
I can confirm this is fixed on my presentations :) thank you
