### ISSUE TITLE
Math formula are garbage rendered in PDF

### ISSUE THREAD

**Issue by SukharevAndrey** [gitpitch/gitpitch#13]
None of math formula are rendered correctly when exported to PDF:
![garbage_math](https://cloud.githubusercontent.com/assets/3942904/19122637/1464eb12-8b34-11e6-9627-781ca140845d.png)
This can be at least reproduced in Google Chrome and Adobe Reader on Windows 10.

**Comment by gitpitch** [comment]
Hi @SukharevAndrey thanks for reporting this issue. I believe the problem may be due numerous embedded videos in the Kitchen Sink presentation. These interfere (causing timeouts) when printing. I believe if you try a regular presentation (without video content) your math formulas will render correctly online, offline and in PDF.

See this sample presentation for details:

[MathJax - Feature Demo](https://gitpitch.com/gitpitch/feature-demo/mathjax)

Can you please let me know if you are still having problems in your own presentations when printing math formulas. Thanks.

**Comment by SukharevAndrey** [comment]
@gitpitch 
It renders, but uses ugly font:
![garbage_2](https://cloud.githubusercontent.com/assets/3942904/19142558/f0ccb4e6-8ba6-11e6-95f1-35ba7b38d26f.png)

**Comment by gitpitch** [comment]
@SukharevAndrey I've been looking into this and I'm seeing differences in the quality of output generated on the GitPitch dev server (OSX) and the GitPitch production server (Ubuntu). On OSX I'm seeing high quality output where these math formulas look like this:

![mathjax-osx](https://cloud.githubusercontent.com/assets/19169584/19145222/3cb8a316-8bd8-11e6-9646-5eae401624b8.png)


This is a work-in-progress. I will update this thread once I know more.

**Comment by gitpitch** [comment]
@SukharevAndrey quick update. Having spent considerable time (1) rebuilding [decktape](https://github.com/astefanutti/decktape) (2) updating system fonts and font caches on a number of Ubuntu staging and  production servers I still can not force the use of the custom mathjax fonts when printing formulas to PDF. But I'm still digging. If I find any way to improve this situation I will notify you by updating this thread.

**Comment by gitpitch** [comment]
Workaround is to [install and run GitPitch server](https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions) on non-Ubuntu server.

**Comment by gitpitch** [comment]
@SukharevAndrey fyi, a new printing option is now available on all GitPitch presentations giving you the ability to try and print directly within the browser. And printing directly within the browser helps solve a number of font related issues including the issue you reported on this thread.

The new print options are presented as follows:

![gitpitch-printing](https://cloud.githubusercontent.com/assets/19169584/23244929/38cc8d5c-f9bb-11e6-93c5-b43c79d41dc6.png)

The `Generate PDF on Server` is the original print support. The `Generate PDF in Browser` is new and is available to you if you are viewing your presentation in Chrome. When you select this print option a new browser window will open. Don't worry if the rendering in the new window looks odd, the applied styling is only to support PDF generation. In the newly opened browser window do the following:

1. Open the in-browser print dialog (CTRL/CMD+P).
1. Change the **Destination** setting to **Save as PDF**.
1. Change the **Layout** to **Landscape**.
1. Change the **Margins** to **None**.
1. Enable the **Background graphics** option.
1. Click **Save**.

Here is a sample GitPitch that demonstrates many uses of MathJax formulas:

```
https://gitpitch.com/gitpitch/feature-demo/mathjax
```

The generated PDF using the new `Generate PDF in Browser` feature for this presentation can be seen here: [feature-demo_mathjax-live.pdf](https://github.com/gitpitch/gitpitch/files/795543/feature-demo_mathjax-live.pdf). You can see that the math fonts are now in use within the PDF.
