### ISSUE TITLE
Wrong jar file version

### ISSUE THREAD

**Issue by lexsys27** [gitpitch/gitpitch#132]
While exporting offline version of the slides from the self-hosted GitPitch server got an error

```
2017-11-14 12:34:00,246 Back-End-Pool [warn] c.g.s.OfflineService -
fetchFixedDependencies: [ prod ] jar not
found=./lib/com.gitpitch.server-1.0-assets.jar 2017-11-14 12:34:00,246
```

Technically it is a warning but results in an empty slide deck  being generated.

The correct version is `2.0`:

```
$ ls lib/com.gitpitch.server-2.0-assets.jar
lib/com.gitpitch.server-2.0-assets.jar
```

Quick workaround

```
cd lib
ln -s com.gitpitch.server-2.0-assets.jar com.gitpitch.server-1.0-assets.jar
```

**Comment by gitpitch** [comment]
Asset jar dependency path has been updated and change has been pushed to master. You can pull latest changes to test and verify.
