### ISSUE TITLE
Serving images from the private repos

### ISSUE THREAD

**Issue by lexsys27** [gitpitch/gitpitch#135]
To insert an image from the private repo I use full path

`https://github.com/lexsys27/gitpitch-temp/raw/master/images/gp.jpg`

This is because relative links doesn't work in this case - they are converted to smth like this

`https://raw.githubusercontent.com/lexsys27/gitpitch-temp/master/images/gp.jpg`

and they need to be converted to this

`https://raw.githubusercontent.com/lexsys27/gitpitch-temp/master/images/gp.jpg?token=XXX`

The link `https://github.com/lexsys27/gitpitch-temp/raw/master/images/gp.jpg` simply redirects to the link with token so serving images from the private repo works.

**Comment by gitpitch** [comment]
See closing comment on related issue #133.
