### ISSUE TITLE
Decktape args support in configuration

### ISSUE THREAD

**Issue by baez90** [gitpitch/gitpitch#137]
Hi,

there's an apparently known [Bug in Decktape](https://github.com/astefanutti/decktape/issues/103) (or actually in puppeteer) resulting in an error while starting decktape because the underlying library is unable to create a sandbox environment for Chrome.

I wanted to build a Docker Container for GitPitch with PDF support but didn't get it working (I tried different base images including Alpine and Ubuntu).
Afterwards I tried to accomplish it on my local system (Arch Linux, Kernel 4.13.12, OpenJDK 8) but had no luck either.

The trick is to pass the argument `--no-sandbox` to the Decktape CLI.

It would be very nice to be able to pass custom arguments to the Decktape CLI with a new config option.
I already had a look at the corresponding code and I don't think that it's a big deal (I could send you a Pull Request the next days if you want) but I wanted to ask what you're thinking about it previously.

Sincerly
Peter

**Comment by gitpitch** [comment]
Hi @baez90 this sounds like a reasonable request. I'll push a patch sometime over the next few days and then update this thread to let you know that it's available for testing.

**Comment by baez90** [comment]
I had a few minutes to create a PR ( #138 ) to save you time :wink:
I'll try it this afternoon.
Please let me know if it's okay for you or if I missed anything (like style guide or anything else, I read the contribution guide but haven't seen anything like that :wink: )

**Comment by baez90** [comment]
@gitpitch works like a charm on my system.

**Comment by gitpitch** [comment]
Thanks for the update. I have looked over the PR and would prefer to see things done a little differently, so I will push my own update (based on yours) sometime tomorrow. Thanks again for prototyping and testing the patch. Glad you're up and running on your local system now.

**Comment by baez90** [comment]
Alright.
Would you mind to trigger me when you've completed the patch?
I'd like to test it afterwards in my container runtime.
Thank you very much for your fast responses!

**Comment by gitpitch** [comment]
Patch supporting optional args passed to decktape now available in master, 7c4b04a6a2cb0f8519dd77c6d61d996dffcf9b9a. @baez90 when time permits can you please test and verify on your local system then update or close this thread as appropriate.

**Comment by baez90** [comment]
Works as expected.
Thank you very much!
