### ISSUE TITLE
Long images run off bottom of screen

### ISSUE THREAD

**Issue by DougInAMug** [gitpitch/gitpitch#141]
The markdown image format `![](path/to/image` when used with 'long' images causes them to run off the screen. Example:

![screenshot from 2017-12-15 01-02-31](https://user-images.githubusercontent.com/13798767/34021898-1f2b88ba-e134-11e7-834d-1a2bedc1fc46.png)

I get around this using the html format and vh units `<img src="path/to/image" style="height:75vh">` I would find it very convenient if the default behavior was something like this. I can't imagine any occasion when it would be desirable to have a feature image 'cropped' by the screen during a presentation, nor have it deformed.

**Comment by gitpitch** [comment]
Hi @DougInAMug thanks for this feedback. As you probably know there is no mechanism in Markdown syntax itself to indicate or enforce image scaling for size or aspect ratio. So your approach of replacing basic markdown image syntax with a HTML `img` tag is one option.

Perhaps a better option for you given you are working with images that do not share a common aspect ratio with your presentation is to make use of GitPitch's special support [slide background images](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background). And specifically, to then make use of GitPitch's [sizing and scaling](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#slide-image-sizing--scaling) support on those images. These features are provided specifically to handle the issues you have described.

See the following [sample presentation](https://gitpitch.com/gitpitch/feature-demo/customize-image-size) to see how this *sizing and scaling* feature can be used to prevent both deformed images and image cropping on slides.
