### ISSUE TITLE
Add rel="noopener" to target="_blank" links

### ISSUE THREAD

**Issue by Ryuno-Ki** [gitpitch/gitpitch#142]
Hi, @gitpitch,
I've just came across reading #30 and want to bring to your attention, that you should add `rel="noopener"` to all those links.

The [original explanation of the vuln](https://dev.to/ben/the-targetblank-vulnerability-by-example) suggests even going as far as adding `rel="noopener noreferrer"`.

Thanks for your work on this :-)

**Comment by gitpitch** [comment]
Hi @Ryuno-Ki thanks for submitting this issue. A new patch 7a62b4ab465e6dc76f8f233e9f3b06aa3dde5295 to resolve this issue has been integrated and is now live on gitpitch.com.

In the interests of protecting users above all else, I've applied the more comprehensive solution, using `rel="noopener noreferrer"`.

If you can test and verify this change we can close this issue. Thanks.

**Comment by Ryuno-Ki** [comment]
Hi,

sorry, I was on vacation.
After moving from [this slide](https://gitpitch.com/gitpitch/templates/brick#/6) to [GitHub](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) and logging `window.opener` I get the expected value of `null`.

So it is verified fixed.

**Comment by gitpitch** [comment]
No problem @Ryuno-Ki I hope you enjoyed your vacation. And thank you for testing and verifying the fix.
