### ISSUE TITLE
Images is using different relative url offline

### ISSUE THREAD

**Issue by KalleDK** [gitpitch/gitpitch#145]
I think that this is a continuation of #96

If I use that relative inline url `![PIC](assets/pic.png)` then it works online - If I donwload the bundle and unzip the PITCHME.md has changed the relative url to `![PIC](assets/md/assets/pic.png)` which works offline, but makes it "useless" to devolop the slide offline unless you want to remember to search and replace.

As in the flow documented here about local images does not seems to work https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally
 
Windows 10 + Python 3

**Comment by KalleDK** [comment]
A workaround is moving the pictures to the root assets folder next to the md folder.

**Comment by gitpitch** [comment]
Hi Kalle, thanks for providing this feedback. The workflow for developing presentations offline is not great today, certainly room for improvement. It is something I will be turning my attention to after the next GP major release ships in the coming months.

I'm glad you found a workaround. For now, you'll need to stick with that. I will update this thread when a more permanent fix is available.

**Comment by gitpitch** [comment]
[GitPitch Desktop](https://gitpitch.com/desktop) is now the recommended tool for developing, previewing, and presenting offline presentations.
