### ISSUE TITLE
More control over next and prev keys

### ISSUE THREAD

**Issue by IEvangelist** [gitpitch/gitpitch#146]
First and foremost, thank you for all of your time, effort and passion that you've given to this amazing project. I love it and use it all the time now, and I continue to tell people about it.

## Request

If we look at the following, we see where `Reveal.js` configures its next and prev keys.
https://github.com/gitpitch/gitpitch/blob/7a62b4ab465e6dc76f8f233e9f3b06aa3dde5295/app/com/gitpitch/views/frags/SlideshowReveal.scala.html#L196-L204

 I would love it if we could control how these keys are configured from the `PITCHME.yaml` as an optional override. It seems like the `ssm` object has access to the materialized YAML based configuration. We could probably add this and use it if it exists, mapping accordingly.

### Remote Control

My remote control issues up (`40`) and down (`38`) commands, instead of left and right. As such, my remote control does not work with this. I can see where being able to configure the `next` and `prev` commands would be a great feature and it is possible that this would no longer be tied to the remote control YAML settings. Ultimately allowing the user to control how what determines the `prev` and `next`... Again, thank you for considering this alteration.

### Proposal

Example alteration:

```html
     @if(ssm.remoteControlEnabled()) { 
     <script> 
         Reveal.configure({ 
             keyboard: { 
                 @ssm.prevOverrideOrDefault(): 'prev', 
                 @ssm.nextOverrideOrDefault(): 'next' 
             } 
         }); 
     </script> 
```
And the corresponding methods would have defaults of `37` and `39`, respectively. But if the YAML provided values, those would be used instead. Allowing me to configure something like this in the YAML.

```yaml
nav-prev: 38;
nav-next: 40;
```

Or whatever key name best describes the intent here.

**Comment by gitpitch** [comment]
Hi @IEvangelist thanks for all of this great feedback and for providing such a clear, detailed feature proposal. This feature request for remote control custom key mappings has been implemented, merged,  and is now live on [gitpitch.com](https://gitpitch.com).

Please see the updated doc on the [Remote Control Navigation](https://github.com/gitpitch/gitpitch/wiki/Remote-Control-Navigation) page in the Wiki for details. Feedback on the doc or feature is appreciated once you've had a chance to test this.

**Comment by IEvangelist** [comment]
Thank you this https://github.com/gitpitch/gitpitch/commit/915a7e8dc116aa9187f2dfb2acc615ac205503a5. I tested it out already and it works like a charm!!
