### ISSUE TITLE
gitpitch command line version or api?

### ISSUE THREAD

**Issue by phanikandula** [gitpitch/gitpitch#147]
Local deploy of gitpitch server works like a charm... Thanks for all the great documentation!

Instead of using browser, is it possible to build a command line version of gitpitch?

Use case: git repo is already cloned to local machine, I just want to run a command and generate offline version of presentation and pdf.

I'll look into OfflineService.java and PrintService.java to understand how it's done. Posting issue here to see if anyone looked into it already. I searched the issues but didn't find anything on this topic.

Also, if there is an API where I could give github repo details and get zip and pdf information in response.. that would be useful too. Maybe building api would be easier than creating command line version. I'll research that option too.

Thanks,
Phani

**Comment by gitpitch** [comment]
Hi Phani,

There are APIs you can call today that will return both PDF and the offline ZIP. For example:

#### Print PDF

```
curl https://localhost:9000/pitchme/print/github/onetapbeyond/lambda-spark-executor/master/white/PITCHME.pdf > PITCHME.pdf
```

Where `github`, `onetapbeyond`, `lambda-spark-executor`, `master`, and `white` are example parameter values for GRS, user, repo branch, and theme respectively.

#### Offline Zip

```
curl https://locahost:9000/pitchme/offline/github/onetapbeyond/lambda-spark-executor/master/white/PITCHME.zip > PITCHME.zip
```

Again, where `github`, `onetapbeyond`, `lambda-spark-executor`, `master`, and `white` are example parameter values for GRS, user, repo branch, and theme respectively.


**Note**, that these APIs are `server-internal` and may not be supported in future releases so use at your own risk :)

I believe for your specific use case, the APIs I've just provided can be used on the command line (or with scripts etc) to generate the content you are after. Understanding that your local GitPitch server will still be communicating with a repo on a hosted GitHub, GitLab, Bitbucket, GitBucket, Gitea, or Gogs server. Not with local disk.

**Comment by phanikandula** [comment]
Thank you. This API should suffice for now.
