### ISSUE TITLE
GitPitch Slideshow print service temporarily unavailable.

### ISSUE THREAD

**Issue by kbeaugrand** [gitpitch/gitpitch#148]
Hi, 

I'm receiving this message when attempting to get PDF version of my slideshow. 

```GitPitch Slideshow print service temporarily unavailable.```

Here is my SlideShow Url : 

https://gitpitch.com/universite-clermont-auvergne/IoT/dev?grs=gitlab&t=white&p=talk-1#/

What's wrong in my slideshow ??

Regards,

**Comment by gitpitch** [comment]
Hi Kevin, I just tried to print your presentation using the link you provided and it printed without any problems. Here is a screenshot of the PDF in my browser:

<img width="1341" alt="iot" src="https://user-images.githubusercontent.com/19169584/35189525-a5c3b21e-fe7e-11e7-97a6-e53dbd3c79af.png">

Perhaps you were experiencing intermittent network problems. I see not indications of any errors in the GitPitch server logs.

**Comment by gitpitch** [comment]
Kevin, one additional tip. I noticed some of the image assets you are using in your `assets/images` directory are named as follows:

<img width="418" alt="iot-imgs" src="https://user-images.githubusercontent.com/19169584/35189569-94ce0648-fe7f-11e7-870d-fc35457d3560.png">

These image files all have a space in their filenames, for example `Iot World.png`. To ensure correct rendering using GitPitch I recommend that you rename all image files where you are using spaces in their names. For example rename `Iot World.png` to `Iot-World.png` etc.

**Comment by kbeaugrand** [comment]
Hi, 

You're right, it's working but I've to try multiple times in order to get it working. 
It could be because your servers are hosted in US, and I'm getting that from France ;)
That's not a problem for me now.

Another problem for me is pictures inside the slideshow. They are corretly displayed in web slideshow but I've some rendering issue. 

Here are this new issue : #151

Regards,
