### ISSUE TITLE
Document dependency on "zip" program for local installation of gitpitch

### ISSUE THREAD

**Issue by phanikandula** [gitpitch/gitpitch#149]
Hello, 

I ran gitpitch locally on my windows machine and offline version (zip) wasn't getting created because there was no zip installed on my computer. 

Maybe call out zip as one of the dependencies like decktape is mentioned in 
 https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions?

Thank you.

**Comment by gitpitch** [comment]
Thanks for providing this feedback. The [server deploy](https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions) instructions on the Wiki have been updated to reflect this runtime dependency.

**Comment by phanikandula** [comment]
Thank you. Appreciate quick response!
