### ISSUE TITLE
Configuring gitpitch on ubuntu

### ISSUE THREAD

**Issue by pmsudhi** [gitpitch/gitpitch#15]
Hi,
After configuring and starting the application, when i browse to my server http://localhost:9000, it gives me a messageBad Request, Host not allowed error. my application logs says ,successfully started and listening on /0:0:0:0:0:0:0:0:9000.

After making build, i have done following changes
1. Changed Secret Key
2. Made gitlab as my default and set the API key.

Both gitlab and gitpitch is running on same ubuntu machine

Am i missed any steps?

**Comment by gitpitch** [comment]
Hi @pmsudhi the GitPitch server does respond on the `http://localhost:9000` endpoint. You should test your installation using a valid  slideshow presentation endpoint as described in the [build instructions](https://github.com/gitpitch/gitpitch/wiki/Server-Build-Instructions). 

For example, it recommends testing the following endpoint immediately after your GitPitch server starts up:

```
http://localhost:9000/gitpitch/kitchen-sink
```

Have you tried this? Does it work? If not, can you share the console output generated by your GitPitch server when it fails?

**Comment by pmsudhi** [comment]
Hi, Thanks for super quick response.  
when I do http://localhost:9000/gitpitch/kitchen-sink, it seems working and i can see output as in localhost.png

But When I do the same url with machine name instead of localhost, iam getting error "host not allowed" as in machname.png.

The console log not showing any additional entries while iam calling with machine name. The only entries i can see here is as below
2016-10-07 16:13:44,858 main [info] c.g.g.GRSManager - activating: GitHub, type=github, default=false
2016-10-07 16:13:44,869 main [info] c.g.g.GRSManager - activating: GitLab, type=gitlab, default=true
2016-10-07 16:13:44,869 main [info] c.g.g.GRSManager - activating: Bitbucket, type=bitbucket, default=false
2016-10-07 16:13:45,477 main [info] play.api.Play - Application started (Prod)
2016-10-07 16:13:45,758 main [info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

So, i guess i missed some configurations. sorry, I am very beginner at Linux systems and may be skipping some obvious steps.

![machname](https://cloud.githubusercontent.com/assets/16379528/19187592/efa15578-8ca9-11e6-85b3-311c6ee1b17f.png)
![localhost](https://cloud.githubusercontent.com/assets/16379528/19187598/f478fa74-8ca9-11e6-84ab-1ab64b288f96.png)

**Comment by gitpitch** [comment]
Using `localhost` will almost always work by default for a local installation, however using `hostname` requires that the `hostname` be mapped to a valid IP address, typically something you would do in your `/etc/hosts` file. If you're not familiar with this you may need to talk to a sys admin.

For your testing purposes I suggest you stick with `localhost`. The screenshot you have shared tells me that your GitPitch server is up and running. Now all you need to do is create a project on your local GitLab server and then add your `PITCHME.md` file for your presentation to that project. Then test it out. Let me know how it goes.

**Comment by pmsudhi** [comment]
Hi, hostname is mapped to valid Ip address. since my gitlab is also hosted on same machine with default port, when i type http://machinename, i can open the page.
Do I need to change anything at allowedorigins tag in application config file?

**Comment by gitpitch** [comment]
My advice for initial testing you should comment out the `allowedOrigins` property in the application.conf file. If that works, then try adding your `hostname` to the array and test again.

**Comment by pmsudhi** [comment]
Commenting out _allowedOrigins_ doesn't help. Also when i go through the console log i can see that system is able to resolve name(http://waspsource/api/v3/projects/gitpitch%2Fkitchen-sink) and able to call gitlab API

`2016-10-07 16:44:21,965 main [info] c.g.g.GRSManager - activating: GitHub, type=github, default=false
2016-10-07 16:44:21,970 main [info] c.g.g.GRSManager - activating: GitLab, type=gitlab, default=true
2016-10-07 16:44:21,970 main [info] c.g.g.GRSManager - activating: Bitbucket, type=bitbucket, default=false
2016-10-07 16:44:22,456 main [info] play.api.Play - Application started (Prod)
2016-10-07 16:44:22,688 main [info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
2016-10-07 16:44:38,195 application-akka.actor.default-dispatcher-3 [debug] c.g.s.PitchService - cachedRepo: grmKey=GRM:/gitlab/gitpitch/kitchen-sink
2016-10-07 16:44:38,239 Front-End-Pool [debug] c.g.s.PitchService - fetchRepo: pp=/gitlab/gitpitch/kitchen-sink/master [ white ]
2016-10-07 16:44:38,249 Front-End-Pool [debug] c.g.s.GitService - fetchRepo: pp=/gitlab/gitpitch/kitchen-sink/master [ white ]
2016-10-07 16:44:38,249 Front-End-Pool [debug] c.g.g.GRSManager - getService: matching GitLab
2016-10-07 16:44:38,253 Front-End-Pool [debug] c.g.g.GRSManager - getService: returning=com.gitpitch.git.vendors.GitLab@3bbcd625
2016-10-07 16:44:38,253 Front-End-Pool [debug] c.g.g.v.GitLab - genProjectId: pid=gitpitch%2Fkitchen-sink
2016-10-07 16:44:38,254 Front-End-Pool [debug] c.g.s.GitService - fetchRepo: apiCall=**http://waspsource/api/v3/projects/gitpitch%2Fkitchen-sink**
2016-10-07 16:44:39,106 Back-End-Pool [debug] c.g.s.GitService - fetchRepo: pp=/gitlab/gitpitch/kitchen-sink/master [ white ], fetch meta time-taken=849
2016-10-07 16:44:39,107 Back-End-Pool [info] c.g.s.GitService - GitLab: API Rate Limit Status [ null, null ]
2016-10-07 16:44:39,108 Back-End-Pool [debug] c.g.s.GitService - fetchRepo: pp=/gitlab/gitpitch/kitchen-sink/master [ white ], fail status=404
2016-10-07 16:44:39,109 Front-End-Pool [debug] c.g.s.PitchService - cachedRepo: grmKey=GRM:/gitlab/gitpitch/kitchen-sink
2016-10-07 16:44:39,109 Front-End-Pool [debug] c.g.s.PitchService - fetchRepo: pp=/gitlab/gitpitch/kitchen-sink/master [ white ], returning grm=null
2016-10-07 16:44:39,210 Front-End-Pool [debug] c.g.g.GRSManager - listGRS: [GRS[ GitHub ][ github ], GRS[ GitLab ][ gitlab ], GRS[ Bitbucket ][ bitbucket ]]
2016-10-07 16:44:39,219 Front-End-Pool [info] c.g.c.PitchController - landing:   [ notfnd, online ] /gitlab/gitpitch/kitchen-sink/master [ white ]`

**Comment by gitpitch** [comment]
If you are launching your GitPitch server using `sbt run` it is running in dev mode. So you can specify an alternate host address on the command line when you launch the server. Try this:

```
sbt run -Dhttp.address=waspsource
``` 

Note, I only ever use `localhost` when dev mode testing. For non-dev mode deployments I follow the [steps outlined here](https://www.playframework.com/documentation/2.5.x/Deploying) for production deployments.

**Comment by pmsudhi** [comment]
Hi,
Iam running _GitPitch_ server in production mode. i had made self-contained distributable and deployed it to `$HOME/bin/gitpitch` . and starting the server through script `./server`

**Comment by gitpitch** [comment]
Ok. And have you tried setting the `-Dhttp.address=waspsource` as suggested on the command line at launch?

What are your server logs showing following server startup?

**Comment by pmsudhi** [comment]
While Ispecify _-Dhttp.address=waspsource_ , i can't open the url in localhost or with host name(error same as in attached image). the server log doesn't have any error message except information regarding starting the server. the console output is as follow

`**/bin/gitPitch/bin$ ./server -Dhttp.address=waspsource**
2016-10-07 17:55:58,847 main [info] c.g.g.GRSManager - activating: GitHub, type=github, default=false

2016-10-07 17:55:58,852 main [info] c.g.g.GRSManager - activating: GitLab, type=gitlab, default=true

2016-10-07 17:55:58,852 main [info] c.g.g.GRSManager - activating: Bitbucket, type=bitbucket, default=false

2016-10-07 17:55:59,663 main [info] play.api.Play - Application started (Prod)

2016-10-07 17:55:59,942 main [info] p.c.s.NettyServer - Listening for HTTP on /127.0.1.1:9000
`
![err](https://cloud.githubusercontent.com/assets/16379528/19189928/2abe25b0-8cb8-11e6-9df3-77999da4074a.png)

**Comment by gitpitch** [comment]
The screenshot you have shared tells me that you are still trying to reach the GitPitch presentation using `localhost` in the URL in your browser. Have you tried using `waspsource` in the URL?

```
http://waspsource:9000/gitpitch/kitchen-sink
```

**Comment by pmsudhi** [comment]
Yes. Tried both url and result same error page in case I pass the parameter. And in case I start it without any parameters , i can access local host and not byhostname


Regards




From: David Russell

Sent: Friday, 7 October, 6:15 p.m.

Subject: Re: [gitpitch/gitpitch] Configuring gitpitch on ubuntu (#15)

To: gitpitch/gitpitch

Cc: Sudheesh PM, Mention



The screenshot you have shared tells me that you are still trying to reach the GitPitch presentation using localhost in the URL in your browser. Have you tried using waspsource in the URL?


http://waspsource:9000/gitpitch/kitchen-sink

**Comment by gitpitch** [comment]
At this point it is probably worth checking if you are experiencing a DNS problem on your host. Instead of trying to bind to your `hostname` when launching the server I suggest trying to launch the server IP address instead:

```
/bin/gitPitch/bin/server -Dhttp.address=xxx.xxx.xxx.xxx
```

Where `xxx.xxx.xxx.xxx` is the IP address that maps to the hostname `waspsource`.

Then after the server starts try opening the presentation at the following URL:

```
http://xxx.xxx.xxx.xxx:9000/gitpitch/kitchen-sink
```

**Comment by pmsudhi** [comment]
Hi,
Giving  IP Address also not resolved the issue. mean time i refreshed my ubuntu machine and redone the steps exactly as before and still the issue remains same. To conclude

1. DNS is resolving to valid IP address      

**Diffrent Scenarios**:     
**A) Starting Server with -Dhttp.address=192.168.1.65**     
   **_A.1)_** When I browse the page with http://192.168.1.65:9000/gitpitch/kitchen-sink , I receive Error page with message saying HOST NOT ALLOWED 192.168.1.65:9000     
   **_A.2)_** When i browse page with http://localhost:9000/gitpitch/kitchen-sink, I receive Error page "Unable to connect page"     
**B) Starting Server without -Dhttp.address**     
   **_B.1)_** http://localhost:9000/gitpitch/kitchen-sink , successfully open the presentation page and it is able to resolve gitlab api URL which is given in config file with Machine name. This is the reason i believe it is not related to DNS resolve issue     
   **_B.2)_** http://waspsource:9000/gitpitch/kitchen-sink, which opens, HOST NOT ALLOWED waspsource:9000 page.      
   **_B.3)_** http://192.168.1.65:9000/gitpitch/kitchen-sink, which opens, HOST NOT ALLOWED 192.168.1.65:9000 page.

**Comment by gitpitch** [comment]
@pmsudhi can you tell me about the host environment, is it a local box, an AWS instance, or something else?

By default, when you launch the GitPitch server the default `0.0.0.0` binding should be automatically accepted by the embedded Netty server and just work for any valid network interface (address) on your box.

What is in your /etc/hosts file? If you do not want to share that information publically here you can e-mail it to me. Can you also send me the output generated  by the following command:

```
ifconfig -a
```

Finally, please also include your `application.conf` file.

**Comment by steverice** [comment]
I believe this is just a Play Framework setting — you need to configure the [`hosts.allowed` property](https://github.com/gitpitch/gitpitch/blob/f4adfbed3ecdd1418880d017b70f3d11333d154e/conf/application.conf#L294) for the [AllowedHostsFilter](https://www.playframework.com/documentation/2.5.x/AllowedHostsFilter#Configuring-allowed-hosts).

Note that the [default value](https://www.playframework.com/documentation/2.5.x/resources/confs/filters-helpers/reference.conf) (set by Play) if you don't specify it isn't to allow all hosts, it's to only allow `localhost` and `.local` domains:
```
# Allowed hosts filter configuration
  hosts {

    # A list of valid hosts (e.g. "example.com") or suffixes of valid hosts (e.g. ".example.com")
    # Note that ".example.com" will match example.com and any subdomain of example.com, with or without a trailing dot.
    # "." matches all domains, and "" matches an empty or nonexistent host.
    allowed = ["localhost", ".local"]
  }

```

**Comment by pmsudhi** [comment]
Thanks @steverice . Yes it was the problem. My understanding was that if i comment that property it is going to allow ALL Hosts. Thanks for that help, by changing that I am now able to access this in all way. Thanks @gitpitch for patiently follow up with me

**Comment by gitpitch** [comment]
@steverice thank you very much. I've just tested and verified this config change on a staging server here. It works. @pmsudhi hopefully you now have what you need.

Each of the GitPitch servers I've deployed run behind `nginx` so do not require this config change. But this is very good to know. I'll update the build/deploy docs with details so people in the future won't get stuck on this.

**Comment by gitpitch** [comment]
Wiki documentation has been updated to include new section on [Server Deploy Instructions](https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions). Aim is to provide as a better starting point for future users setting up their own GitPitch server.
