### ISSUE TITLE
Image rendering issue in PDF version

### ISSUE THREAD

**Issue by kbeaugrand** [gitpitch/gitpitch#151]
Hi, 

I've got some rendering issue in my slideshow. 

Picture from my slideshow is correctly displayed in the web version : https://gitpitch.com/universite-clermont-auvergne/IoT/dev?grs=gitlab&t=white&p=talk-1#/6/1

But inside the PDF version, this picture is not weel rendered : 

![image](https://user-images.githubusercontent.com/9513635/35194632-9b977a36-feb6-11e7-802d-e023fbdc7b89.png)

Regards,

**Comment by gitpitch** [comment]
I'm not sure offhand why your presentation is experiencing this PDF rendering problem. Have you _size-optimized_ all of the image assets used by your presentation? If not, I recommend  you do.
 You might want to consider [tinypng.com](https://tinypng.com). It is a free online service that generates excellent image compression. 

Size optimized assets load faster. This may resolve your issue.

**Comment by gitpitch** [comment]
@kbeaugrand I looked again at your presentation and noticed you were using [inline image syntax](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#inline) to render image-only slides where the images themselves were of mixed/arbitrary dimensions and where the aspect aspect-ratio of your images did not match the aspect-ratio of your slides.

This aspect-ratio mismatch is the underlying cause of the printing problems you reported. 

So I forked your repo and made some changes to your `talk-1/PITCHME.md` to demonstrate the use of background image delimiters which give you control of over image size and scale. You can see the resulting presentation here:

[Talk-1 Modified PITCHME.md Demo Presentation](https://gitpitch.com/gitpitch/IoT/dev?grs=gitlab&t=white&p=talk-1)

If you try to print this sample presentation to PDF you will see that all slides print perfectly.

**As a general rule of thumb**, if you are using images of mixed/arbitrary dimensions you should use [slide background image syntax](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background) which lets you size and scale any image to an aspect-ratio that matches your slidesshow.

In practice this is a very simple change, for example, change your original slide markdown:

```
+++

@title[Les fabricants]
![Les capteurs](assets/logos/sensors_manufacturers.png)

```

to the following:

```
+++?image=assets/logos/sensors_manufacturers.png&size=auto 80%

@title[Les fabricants]
```

You can learn more about image sizing and scaling on the GitPitch wiki [here](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#slide-image-sizing--scaling).
