### ISSUE TITLE
Code presenting broken for Dockerfiles

### ISSUE THREAD

**Issue by akosma** [gitpitch/gitpitch#155]
The [techniques of code presenting described in the wiki](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting) do not work when presenting Dockerfiles. The blocks are simply not highlighted properly, or work in random fashion (that is, one block appears ok, then the other does not, etc). Tested in Firefox and Chrome for Mac (all latest versions).

Also, maybe related or maybe not, any spaces inside of the presented Dockerfiles are simply gone (both in Firefox and Chrome).

**Comment by gitpitch** [comment]
This is a known issue with dockerfiles, see #136. A workaround is provided in the link provided.

**Comment by gitpitch** [comment]
Closing as duplicate, see #136.
