### ISSUE TITLE
Request - specify markdown file name/location in the PITCHME.yaml

### ISSUE THREAD

**Issue by jodiedunlop** [gitpitch/gitpitch#156]
It would be great if I could name my markdown file something other than `PITCHME.md` so that it is agnostic to the presentation layer (gitpitch). That way, I can just throw a `PITCHME.yaml` file anywhere in my existing repo, and not have to rename my existing markdown files.

```yaml
markdown: ./markdown/my-talk.md
```

**Comment by gitpitch** [comment]
Thanks for this. I have looked into your suggestion. Nice idea. But it introduces complexity to the service most easily avoided by sticking with the existing, simple conventions. Closing request for now as will-not-implement.
