### ISSUE TITLE
Downtime

### ISSUE THREAD

**Issue by exoji2e** [gitpitch/gitpitch#157]
Hi, I'm receiving 502 Bad Gateway: `nginx/1.4.6 (Ubuntu)` when I try to browse to the [hello world slideshow](https://gitpitch.com/gitpitch/gitpitch).

**Comment by gitpitch** [comment]
Hi @exoji2e thanks for the heads up. A server error occurred earlier today, as reported on the GitPitch [Twitter account](https://twitter.com/gitpitch/status/965858725146673152). The issue is now resolved. If you experience any further problems accessing presentations please let me know.
