### ISSUE TITLE
Error running a presentation from a subfolder

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#158]
I noticed that the following presentation link is no longer working.

https://gitpitch.com/terrywbrady/dspaceUserMeeting?p=schedule

I took a look at the modular markdown section of the wiki, and I think that my URL is correct.

Please let me know if there is a change that should be made to be able to access this presentation again.

**Comment by gitpitch** [comment]
Hi Terry, it looks like you still are using an old (now retired) property in the `PITCHME.yaml` for this presentation.

Try deleting the following entry from the `schedule/PITCHME.yaml` file in your repo and let me know how it goes:

```
# Allow fast nav with shift key
revealjs-version : 3.4.1
```

It's probably worth checking the YAML for each of your presentations and removing this property if you find it.

**Comment by terrywbrady** [comment]
@gitpitch , I forgot about that setting.  Thanks for pointing that out.  I have updated my presentations.
