### ISSUE TITLE
404ing on presentations

### ISSUE THREAD

**Issue by jsjaspreet** [gitpitch/gitpitch#159]
looks like git pitch is 404ing for one of my repos

https://gitpitch.com/jsjaspreet/intro-to-graphql

swap space issue again?

**Comment by gitpitch** [comment]
@jsjaspreet thanks for reporting this problem. Looks like the issue was caused by a problem in the GitPitch nginx server configuration (pattern matching conflict with your specific repo name). Now resolved. Can you please test and verify.

**Comment by jsjaspreet** [comment]
Works. Thanks!
