### ISSUE TITLE
Code blocks indentation is missing

### ISSUE THREAD

**Issue by Lothiraldan** [gitpitch/gitpitch#16]
Hi, first of all thank you very much for your work!

I'm trying to work on a slidedeck with numerous code block and just saw that code block indentation seems missing. I also checked the kitchen-sink demo and it also seems that code block indentation is missing: https://gitpitch.com/gitpitch/kitchen-sink/master.

Could it be a bug in highlight.js?

**Comment by gitpitch** [comment]
Hi @Lothiraldan thanks for reporting this problem. Definitely a recent regression, code indentation is an important feature and should be working. Not likely a bug in highlight.js, rather something I've done in my production environment. I'll look into this (realistically, tomorrow) and update this thread when I have a better answer for you.

**Comment by Lothiraldan** [comment]
Awesome, thank you for the quick answer, please tell me if I can help.

**Comment by gitpitch** [comment]
@Lothiraldan I've just pushed a patch that will hopefully address this code block indentation problem you reported. Please let me know how you get on if you have a chance to test this. Thanks again for your help.

**Comment by Lothiraldan** [comment]
Thank you very much, the bug is resolved!

**Comment by gitpitch** [comment]
Excellent, thanks for all your feedback. Bug was resolved by commit 594da40a6237a2f81a8887a935a4144f4141ef25
