### ISSUE TITLE
Highlighting fragments in multiple code blocks on the same slide

### ISSUE THREAD

**Issue by amilkov3** [gitpitch/gitpitch#160]
```

'''scala
val x = 2
val y = x + 2
'''

@[1-2](highlight 1)

'''haskell
test = let x = 2
           y = x + 2
           in y + x
'''
<!-- neither this -->
@[1-2](highlight 2)
@[3](highlight 3)

<!-- nor this works -->
@[3-4](highlight 2)
@[5](highlight 3)
```

first code block highlighting works fine but second does not (pretend the `'` are backticks)

**Comment by gitpitch** [comment]
Yes, sadly support for this (code presenting across multiple code blocks on a single slide) is something I did built support for a few months back and somehow I forgot to merge those changes and also appear to have misplaced all of that work. So for now, it remains unsupported.

When time permits I'll try again.

**Comment by gitpitch** [comment]
Experimental support for code presenting across multiple code blocks on a single slide is now available on gitpitch.com.

The code indexes you use within your [code presenting markers](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting)  index as if there was just one code block on the slide.

For example:

'''scala
val x = 2
val y = x + 2
'''

'''haskell
test = let x = 2
           y = x + 2
           in y + x
'''

@[1](Declare constant x in Scala)
@[1, 3](Declare x in Scala and Haskell)
@[2, 4](Declare y in Scala and Haskell)

As noted, this support is experimental. Please try it out and let me know how it goes.
