### ISSUE TITLE
New Feature: Background Image Position in YAML

### ISSUE THREAD

**Issue by michaeltlombardi** [gitpitch/gitpitch#162]
Settings currently exist for color, image, and size, but it would be useful to also set position (for example, top left instead of center).  I will see if I can figure out how to implement. I am also looking to see if I can figure out a temporary workaround.

**Comment by gitpitch** [comment]
Hi Michael, a very nice feature idea. And you'll be glad to know, one that is already implemented. And in the merge queue. Support for this will go live within the next few days. 

Here is a sneak peek:

![gitpitch-image-controls](https://user-images.githubusercontent.com/19169584/38158327-5aef91c6-34bc-11e8-9e5f-d0cf277db4b0.jpg)

This effect was achieved using the following settings in my `PITCHME.yaml`:

```
background : assets/images/sunrise.jpg
background-size : 50% 100%
background-position : left center
background-color : "#D4C711"

# Right adjust text on slide.
layout : center-right
```

Another example:

![gitpitch-image-controls-2](https://user-images.githubusercontent.com/19169584/38158390-a77b7fa4-34bd-11e8-89d5-6c0633aded76.jpg)

**Comment by gitpitch** [comment]
I back ported this feature from the [GitPitch Desktop](https://hackernoon.com/gitpitch-desktop-sneak-peek-da23190dd5c3) branch as it just so useful. Now integrated and live on [gitpitch.com](https://gitpitch.com).

See the updated doc on the Wiki for details describing how to control background image positioning both when working with:

1.  [Global background image settings](https://github.com/gitpitch/gitpitch/wiki/Background-Setting)
2. [Slide specific image delimiter options](https://github.com/gitpitch/gitpitch/wiki/Image-Slides)

Your testing and feedback appreciated.

**Comment by michaeltlombardi** [comment]
I will test today or tomorrow and report back - super useful timing as my conference talk is in one week!

**Comment by michaeltlombardi** [comment]
Seems to be working for me - see [output](https://gitpitch.com/michaeltlombardi/documentarian/gitpitch?grs=gitlab#/1) and [source](https://gitlab.com/michaeltlombardi/documentarian/blob/gitpitch/PITCHME.yaml).

I am entirely happy with this feature, it works exactly per my naive expectations! 😁

**Comment by gitpitch** [comment]
Thanks for the feedback. Nice presentation. Meeting naive expectations, that's the holy grail of usability :)

As for GitPitch Desktop availability, I've already begun the release process but I can't give you an exact release date just yet. Keep an eye on Twitter or on my blog for news. Coming very soon.
