### ISSUE TITLE
Sub tree presentations don't pick up PITCHME.yaml completely

### ISSUE THREAD

**Issue by stmcginnis** [gitpitch/gitpitch#163]
I had an issue in a repo hosting multiple presentations. Within the presentation directory I added a PITCHME.yaml with a background, which was picked up fine. I then tried changing the theme from the default "white", but no matter what I set for theme it would show my custom background with the dark text of the white theme.

It did allow me to manually select a different theme through the presentation menu, which I believe I read should not be allowed when using a custom background.

While keeping the existing PITCHME.yaml in the subdirectory, I copied that to the root of my repo as a test. Once I did that, the presentation now works with the right background and theme-set text colors.

**Comment by gitpitch** [comment]
Hi Sean, if you can share a link to your presentation (that exhibits the problem you describe)  I will be happy to take a look at it.

**Comment by gitpitch** [comment]
I just viewed the `Vancouver2018/CinderSDS` presentation you shared:

```
https://gitpitch.com/stmcginnis/presentations?p=Vancouver2018/CinderSDS
```

The `black` theme is active per the `PITCHME.yaml`. As verified by the white font color on the tinder blocks background image. I also verified the theme in use by looking at the generated code on the page.

Has this problem you reported been consistently reproducible for you? Have you been opening multiple presentations from within the same repo/branch, if so, which ones?

<img width="1293" alt="cinder-blocks" src="https://user-images.githubusercontent.com/19169584/38312344-b49bc888-384b-11e8-89d7-2864cb8b1c27.png">

**Comment by stmcginnis** [comment]
Yes, it works now that I've done the workaround I mentioned. If you do this locally you should be able to see the same issue where it does not work until you put another PITCHME.yaml in the root of the repo instead of just in the root of the presentation folder.

**Comment by gitpitch** [comment]
I just forked your repo. Deleted the `PITCHME.yaml` that you added as a workaround at the root of your repo, then tried again. It all worked as expected.

See my forked/modified repo [here](https://github.com/gitpitch/presentations) and the resulting presentation [here](https://gitpitch.com/gitpitch/presentations?p=Vancouver2018/CinderSDS#/).

I can not reproduce the problem you reported. If you can point me at a presentation that reproduces the problem I will be happy to investigate further. If you can no longer reproduce the problem after updating your own repo, you can close out this issue thread.

**Comment by stmcginnis** [comment]
Hmm, sure enough, I delete that from my repo and it does work fine now too.

It had not for over a day, and I verified with multiple browsers from multiple machines just to make sure it wasn't some kind of caching issue. It only worked after duplicating the settings to the root of the repo.

Maybe something changed over the last day in the service? It is working right now so I will close. Thank you for checking on it.

**Comment by gitpitch** [comment]
No recent changes to the service. I honestly can not explain it, the behavior you described really should not be possible. But it was worth checking. Good luck with your presentation.

**Comment by stmcginnis** [comment]
Thanks! And thanks for working on such a great tool. Really impressed so far with all its capabilities.
