### ISSUE TITLE
Make all list as fragment from the yaml

### ISSUE THREAD

**Issue by xgouchet** [gitpitch/gitpitch#165]
Most of the time, I want all my list items to be revealed one by one, meaning that my markdown presentation are cluttered with 
```<!-- .element class="fragment" -->```

Would it be possible to add a yaml option to make all list item having the fragment class ?

**Comment by gitpitch** [comment]
Closing out this feature request as a new fragment list syntax has been provided which resolves the broader issue. See #166 for details.
