### ISSUE TITLE
Presentation cannot be generated as PDF

### ISSUE THREAD

**Issue by guillaumelobet** [gitpitch/gitpitch#167]
I am using GitPitch for my lectures and it is great! I used it last year and it worked very well. 

However, this year, when I went back to my previous presentation, and added a few slides, I could not generate the PDF anymore.... This is very annoying, as my students needs to be able to print it out for notes. 

Any idea why this is happening? Is the presentation too large? 

It is here: https://gitpitch.com/plantmodelling/LBRES2106/gh-pages#/

**Comment by gitpitch** [comment]
Hi Guillaume, I just opened and printed your presentation to PDF.

You can access that PDF document here: [PITCHME.pdf](https://github.com/gitpitch/gitpitch/files/1892963/PITCHME.pdf)

Did you wait sufficiently long for the print job to complete? If it times out on your connection then (1) refresh the presentation in your browser and (2) try printing again.

I did notice on slide 17 (Tubers and Roots - World Production) and slide 46 (Soil Retention Curve) both are missing images when printed.

This tells me that the images you are using are not compatible with the aspect ratio of the presentation and are therefore spilling outside the slide boundary. Resulting in printing problems. I strongly recommend using [background image sizing and scaling](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#scaling) to ensure large images fit on your slides.

I would also recommend using an image optimizer for every image found in your `img` directory. Just looking at the content of that directory your images look many and large. Try [tinypng.com](https://tinypng.com). It's free. And very effective at reducing image size.

**Comment by guillaumelobet** [comment]
Thanks a lot for this very fast answer! It seems to be working fine now! I'll pay more attention to the images size and ration in the future. 

Keep up the great work!
