### ISSUE TITLE
Once enabled, the fragmenting process runs on all subsequent slides

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#168]
The new fragment syntax described on the wiki is very nice.  The ability to embed other special markup within bulleted items will be very handy.

One issue that I have discovered with it is that once the fragmenting process is enabled on a slide, the bullets on all subsequent slides are fragmented.  It seems like the @ulend is not having the anticipated effect.

See https://gitpitch.com/DSpace-Labs/DSpace-rel-demo/webinar?grs=github

Note the behavior after Slide number 6.

**Comment by gitpitch** [comment]
Hi Terry, thanks for the feedback. And I'm glad to hear you like the new list fragment syntax.

You have indeed uncovered a bug. Which I have been able to reproduce. And I have a local patch that fixes it. But I do need to do some additional testing. So you can expect the patch to go live on gitpitch.com within about 24 hours. I'll bump this thread once that happens.

**Comment by gitpitch** [comment]
A patch for this issue has been pushed live on gitpitch.com. Can you please test and verify. Let me know if you find any problems. If not, you can go ahead and close out this thread.

**Comment by terrywbrady** [comment]
Works just as I hoped.  Thanks for the quick fix and the great service.
