### ISSUE TITLE
Images are not handled when inline in another block

### ISSUE THREAD

**Issue by xgouchet** [gitpitch/gitpitch#169]
I'm trying to use images in various different ways on my slides. Assuming I have an image at path `assets/my_image.png` in my git repository, the following works like a charm, as documented : 

```markdown
![Alt](assets/my_image.png)
```

Unfortunately, if I try to inline it within another block, the `assets/my_image.png` is left as is in the final html page, and I get a missing image in my presentation : 

```markdown
> In a quote ![Gradle logo](assets/my_image.png) 

## In a header ![Gradle logo](assets/my_image.png) 

- And in a list too ? ![Gradle logo](assets/my_image.png)
```

Going further, I sometimes want to add a specific class to the final `<img />` element for styling purposes, so instead of using the `![]()` syntax, I write my html element directly. Likewise, the relative path of the image is converted if the `<img />` element is top level, but not when it's inlined in a header, list, blockquote etc... So for example the first line will work, but not the others 

```html
<img src="assets/my_image.png" class="photo"/>

> In a quote <img src="assets/my_image.png" class="photo"/>

## In a header <img src="assets/my_image.png" class="photo"/>

- And in a list too ? <img src="assets/my_image.png" class="photo"/>
```

**Comment by gitpitch** [comment]
This issue thread fell off my radar, apologies. But in the spirit of better late than never I have an update for this thread that resolves the issues raised. There were two main issues:

1. Image paths do not work when inlined with other content
2. Using image tags to activate custom CSS class also exhibit inline path problem.

The first issue was resolved quite some time ago, image paths are properly resolved whether they are defined on standalone images or inlined images.

The second issue has a clean solution thanks to the `@img[class...]` markdown shortcut. The syntax for this shortcut is documented in the [Markdown Widget Guide](https://gitpitch.com/docs/markdown-features/widgets).

The sample snippets provided above can be replaced with the following - much cleaner - syntax:

```

@img[photo](assets/my_image.png)

> In a quote @img[photo](assets/my_image.png)

## In a header @img[photo](assets/my_image.png)

- And in a list too ? @img[photo](assets/my_image.png)

```

The new `@img[class...]` markdown shortcut lets you activate one (or more) custom CSS classes on any image. And the paths are properly handled no matter how the tag is used - standalone or inlined.
