### ISSUE TITLE
Print to PDF breaks for my presentation

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#170]
Here is my presentation link.

https://gitpitch.com/DSpace-Labs/DSpace-rel-demo/webinar#/

Unfortuantely, I am unable to get the print to pdf option to work.  I see the following message: "GitPitch Slideshow print service temporarily unavailable."

**Comment by gitpitch** [comment]
I believe printing for this presentation is failing for a number of reasons:

1. Spaces within file names are not supported - rename DSpace Overlays.jpg
1. Slide 17 - image should be [sized and scaled](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#scaling) to fit aspect ratio of slide
1. Slide 26 - image should be [sized and scaled](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#scaling) to fit aspect ratio of slide
1. Slide 29 - image should be [sized and scaled](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#scaling) to fit aspect ratio of slide
1. Slide 41 - image should be [sized and scaled](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#scaling) to fit aspect ratio of slide

I recommend using `size=auto 90%` for all of the background image slides indicated above.

As a general rule, if you are using background images that do not share the same aspect ratio as your slideshow,  you should always apply [sizing and scaling](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#scaling). This will ensure your images fit nicely on your slides. And it will also ensure that your images appear in PDF if you print.

Once you have applied these recommendations to your slideshow, let me know how it goes.

**Comment by terrywbrady** [comment]
Thanks.  After making your suggested changes, I tried isolating the slides in error and I think some of the code presenting slides are also causing issues.  I will just close this for now and rely on the offline presentation option.  Thanks for the quick reply.
