### ISSUE TITLE
css override doesn't work when running in a container

### ISSUE THREAD

**Issue by gitkodak** [gitpitch/gitpitch#172]
I don't know if this should even be here, but when I run gitpitch inside of a container I'm unable to use custom css.

The logs in the container say:

Front-End-Pool [debug] c.g.m.SlideshowModel - fetchThemeOverride: customCSS=null

But using the exact same presentation and running on my local machine:

```
Front-End-Pool [debug] c.g.m.SlideshowModel - fetchThemeOverride: customCSS=.reveal section img {                  
        margin: 0;                                                                                                            
        border: 0;                                                                                                            
        box-shadow: none;                                                                                                     
}                                                                                                                             
.reveal h2 {                                                                                                                  
        text-transform: none;                                                                                                 
}                                                                                                                             
.reveal h1 {                                                                                                                  
        text-transform: none;                                                                                                 
}                                                                                                                             
#gp-logo img {                                                                                                                
        max-height: none;                                                                                                     
        max-width: 99%;                                                                                                       
        vertical-align: middle;                                                                                               
}
```

I'm not sure where to even start troubleshooting this.  The css override line in PITCHME.yaml is:

theme-override : https://gitlab.company.com/myuser/gitpitch_test/raw/master/assets/css/PITCHME.css

(I've also used the relative path within the repo which also exhibits the same behavior.)

I've used knsit/gitpitch off of dockerhub and I've also built my own with both alpine and centos7 as a base, all the containers act the same way, the custom css doesn't work.

The whole PITCHME.yaml is:

```
---
theme : white
theme-override : https://gitlab.company.com/myuser/gitpitch_test/raw/master/assets/css/PITCHME.css
layout : center-left
logo : assets/images/combined-topbar-logo.png
transition : none
published : true
```

The actual markdown is a bog-standard hello-world.

```
---?image=assets/images/background.png&size=auto 50%&position=bottom
@title[Introduction]
## <span style="color: #009fdf">Company IT Infrastructure</span>

<span style="color: #8c857b">Domain Roadmap  
$someTechnology Domain goes here</span>


---

@title[Current State]

## <span style="color: #009fdf">Current State</span>

<span style="color: #8c857b">Describes the current state of the technology domain within Company  
Which technologies exist within the domain today  
How these technologies are used (use cases)  
If multiple technologies are used for the same use case, the relative quantities or percentages</span>
```

Further notes:  we're using an internal gitlab server and we have internally signed ssl certs.  We've accounted for the certs in our dockerfile by modifying application.conf to use PEM and copying our root ca certs into the container.

Is it possible for someone else to try to replicate this so we can eliminate a gitpitch bug and keep looking internally?

**Comment by gitkodak** [comment]
The rubber-ducking here worked-ish.  We didn't know the proper place to put the internal certs in alpine.  We were able to get it working with fedora and will try again with alpine.

However, this does point out that using the ssl {} section in application.conf does not configure the certs for all elements.  We had imported our certs to the container and use the PEM type and pointed it at the file.  Doing that half-worked, we were able to load the presentation from our internal gitlab, but whatever grabs the css apparently doesn't use playframework.  Or something.

**Comment by gitpitch** [comment]
Can you share the `ssl` configuration block within your `application.conf` so I can see your exact configuration?

**Comment by gitkodak** [comment]
Sure,

```
ssl { 
  trustManager = {
    stores = [                                                       
        { type = "PEM", path = "/etc/cacerts.pem" }       
      ]                                                                         
    }
  }  
```
During the container build we copy a full cacert file, including our internal cacerts, into /etc/cacerts.pem.

If we do it this way gitpitch can read the PITCHME.md and PITCHME.yaml files from our internal gitlab instance just fine, but apparently the mechanism that retrieves the custom css file doesn't use those certs.  As a side note:  if we leave the application.conf file completely as default then gitpitch just reports that it can't find the presentation on gitlab -- it doesn't mention ssl issues.

If, however, we use fedora and go through the redhat-ish process of copying our custom certs in and doing "update-ca-trust" (and leaving the ssl block as default) everything works as expected.

Another side-note: I did try to import into the jks, too, but that had the same symptoms.  It's very likely I did that wrong, though -- I'm an infrastructure guy and know little about the mysteries of java incantations.

I still haven't gotten around to doing this with alpine.  I need to, the fedora container is 2G!

**Comment by gitpitch** [comment]
You are working with the open source GitPitch server which does a lot of things differently to the production server on gitpitch.com. One of those differences is how it handles connections when dealing with slideshow assets - including custom css.

Given that, you might want to try adding a fallback to your config to allow the server to use the default JSSE trust store:

```
ssl { 
  trustManager = {
    stores = [                                                       
        { type = "PEM", path = "/etc/cacerts.pem" }
        { path: ${java.home}/lib/security/cacerts, password = "changeit" }
      ]                                                                         
    }
  }  
```

If you do try this out - I would be interested to learn how it goes.

As a side note, I will be releasing GitPitch Enterprise in the next couple of weeks. This is the full GitPitch.com server - including support for private repos, pro image support, markdown shortcut syntax, etc  - delivered as a Docker container for on-premises deployment.

This is designed to integrate seamlessly with self-hosted GitHub, GitLab, Bitbucket, GitBucket, Gitea, and Gogs servers. Note sure if this may be of interest to you but just wanted to take this opportunity to let you know that it's coming very soon.

GitPitch Enterprise licensing deals will include [GitPitch Desktop](https://gitpitch.com/desktop) site licenses. If any of this might be of interest drop me an email to discuss - david@gitpitch.com.

**Comment by onetapbeyond** [comment]
Just checking in, did the fallback config help?
