### ISSUE TITLE
Auto-generate reference list from citations

### ISSUE THREAD

**Issue by HenrikEckermann** [gitpitch/gitpitch#173]
Hi,

thanks for building gitpitch.  am trying gitpitch out for the second time and especially the outcome I like a lot. At this moment I am a lot of slower still though compared to working with pp etc. But I hope that will change. 

The reason for this post:

Is it possible to automatically create a reference list slide(s) at the end of the presentations using biblatex like e.g. in Rmarkdown/pandoc markdown?

Unrelated to that a question: 
If I write a slide with several bulletpoints I noticed that in case I write too many, the fontsize is not automatically scaled down like it would be in e.g. pp. Is that normal or am I doing something wrong. Generally this is a nice reminder of keeping it simple with only few points per slide but still: What is the easiest way of setting a smaller fontsize for a whole slide? I found `@size[0.6em](example)` in an example slide but I guess this is meant to only use for a small sentence or keywords...

Thanks

**Comment by gitpitch** [comment]
Hello Henrik, thanks for getting in touch.

> At this moment I am a lot of slower still though compared to working with pp etc. But I hope that will change.

To speed things up I recommend taking a look at [GitPitch Desktop](https://gitpitch.com/desktop). There is a short video on the linked page that shows how you can build GitPitch presentations very quickly using this new desktop tool.

> Is it possible to automatically create a reference list slide(s) at the end of the presentations using biblatex like e.g. in Rmarkdown/pandoc markdown?

Currently GitPitch does not auto-generate reference list slides for you. Can you tell me a little more about what you need exactly? An example would be very useful - showing what your input for the list might look like - and showing what output you would like to see.

> If I write a slide with several bulletpoints I noticed that in case I write too many, the fontsize is not automatically scaled down...

Your chosen GitPitch (reveal.js) theme determines the default font size for each element on your slide eg. h1, h2,..., p, etc. As you have already experienced, your text is scaled, but it is not shrunk-to-fit so if you use too much text it will eventually overflow the slide.

The solution is to use [custom css](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS).

Recent support for new list syntax makes applying custom styles for your bullet-points very easy. See the following [sample list syntax presentation](https://gitpitch.com/gitpitch/feature-demo/frag-shortcut-syntax) for a quick summary of the available syntax. The markdown for this presentation is [here](https://github.com/gitpitch/feature-demo/blob/frag-shortcut-syntax/PITCHME.md).

To give you a clearer idea how you can define and then apply custom CSS to match your bullet list needs see the following snippets. First, some sample custom CSS:

```

.reveal ul.list-long-items li {
   margin:0 0 15px 0;
   font-size: 0.9em;
}

.reveal ul.list-many-items li {
   margin:0 0 8px 0;
   font-size: 0.6em;
}

```

Now, some sample `PITCHME.md` markdown using that custom CSS:

```
@ul[list-long-items]
- This is an example of a long bullet point that goes on and on and on and on
- Here is another example of a long bullet point that goes on and on and on
@ulend

---

@ol[list-many-items]
- One
- Two
- Three
- Four
- Five
- Six
- Seven
- Eight
- Nine
- Ten
- Etc
@olend

```

Hopefully it is clear that you can play around with the `margin` spacing and `font-size` css property values to create custom CSS to fits your needs for your lists.

Once you have had a chance to look all of this over let me know if you have any further questions.

**Comment by HenrikEckermann** [comment]
Thanks for the great answer!

I will test these things out. I am not sure if I can finish this presentation this time on time using gitpitch because I am a bit under time pressure and that is not the best situation maybe to try something out where I seem to lack too much knowledge about CSS and HTML. I think the dektop tool is only for people who already have a subscription, is that possible? I certainly would be a candidate to subscribe after I finished my M.Sc. I will use the trial month for my next presentation to then decide if gitpitch is the best tool for me, especially with the desktop app. I attached a file with a reference list from my last presentation. This is APA6th style. If you use e.g. Rmarkdown you can specifiy in the YAML header like this:

` 
---
title: "example title"
author: "Henrik Eckermann"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
bibliography: any/path/library.bib
---
`

where the .csl file refers to a citation style and the .bib file contains all the information necessary for citing an article or a book for example. In Rmarkdown I then can write for example:

`@someauthorname2018 showed that xyz...` or `It has been shown that xyz...[@someauthorname2018]`. The reference list is then automatically generated and attached to the end of the output document. 

In case I cannot get the required output with your recommendations, I will let you know. Thanks again!!

[refs.pdf](https://github.com/gitpitch/gitpitch/files/1994928/refs.pdf)

**Comment by HenrikEckermann** [comment]
Hi David,

thanks again for your help. Great support! I will try this out.

I create these .bib files using Mendeley Desktop but as far as I know the .bib file can be used by many softwares that have been built to assist (e.g.) scientists to manage a library of articles, books etc. I do not know where the trend goes but as far as I see it there a two types of people: The ones using the “old school” stuff like Microsoft Word, Open Office etc.. They will also tend to use powerpoint or google presentation. They use .e.g Mendeley or Endnote etc., which automatically can create a reference list in the required style. In Psychology apa6th style is obligatory. In Medicine I think it is chicaco style but I dont know for sure. The point is that different disciplines use different styles and changing that by hand obviously is inefficient. Here (https://github.com/citation-style-language/styles <https://github.com/citation-style-language/styles>) you find most import .csl files (citation style languages). The other group of people who are at least a little bit into programming, start more and more using (R)Markdown for scientific writing in combination with latex. And the way I do this (which might not be optimal but still much more efficient than what the word guys do): I create a .bib file with e.g. Mendeley where all my libraries are in and pandoc can use the .csl file in conjunction with the .bib file to create the reference in the way I want. Important to know maybe: Pandoc created the output document from a .md, .Rmd, .pmd etc. source file into pdf, docx or .html but applying the correct style seems to be everything but straight forward. I wrote my own Python script to actually change the reference list because the indentation is not correct. I think that in a presentation it is not so important that the style is correct. But it might be a useful feature if a reference list is created in the end. Check out for example the attached references.Rmd source file. Imagine I would mention authors in the presentation slides just like in that document (@authorname) and the gitpitch automatically creates extra slides in the end with references.  By the way:  The apa style is not applied properly by pandoc because the indentation is missing (you can see the correct way if you go to the reference slide in the presentation I am currently working on here: (https://gitpitch.com/assets/libs/reveal.js/3.6.0/plugin/notes/notes.html <https://gitpitch.com/assets/libs/reveal.js/3.6.0/plugin/notes/notes.html>). I think this is also a nice way to implements a reference list because who likes to look at a slide completely full of references. It is nothing your would present to the audience but more something that people would look at if you hand out the presentation. Keep in mind that I am still a M.Sc. student. It would be more helpful for you if would talk to someone who is going to conferences regularly to present as a scientist because he/she will know what exactly is asked.

That is all I can tell you since I am unfortunately relatively limited in my (programming) knowledge still. I can program intermediate Python and R but that’s it….


I attached a .bib file. The csl file I get from a gitreporsitory without knowing how they are created.




Hope this helps.

Henrik

**Comment by gitpitch** [comment]
Henrik, thanks very much for providing these details - all very useful context.

While I will not be implementing citations and auto-references right away within GitPitch I have updated the title for this issue thread and labelled it as a request-for-enhancement.

This will allow others to find and upvote this feature request - and everyone is very welcome to provide additional suggestions/ideas on this thread.

**Comment by Sean-P-Carey** [comment]
I'd like to second the request for this enhancement.  Right now I use R-Studio and markdown to write APA formated papers and to do APA citations in academic slide presentations. While those slides look nice they do not compare to the functionality of GitPitch. If citations could be auto-generated from a .csl file folks in academia and (students and faculty) might use the product more.

**Comment by gitpitch** [comment]
I have just pushed brand new support for citations and auto-generated bibliographies for GitPitch slide decks. Using existing BibTEX, EndNote, and RIS databases. See the [Citations + Bibliography Guide](https://gitpitch.com/docs/citations/bibliography) for details. 

Note, if you are using GitPitch Desktop make sure you pull the latest image to try this out.

I have not publicly announced this feature yet as it needs real world testing. So if you can, please try it out and let me know how it goes. @Sean-P-Carey @HenrikEckermann I'm particularly interested in how you see it's suitability for folks in academia. Thanks, David.

**Comment by HenrikEckermann** [comment]
Hi David,

thanks for implementing it. I gonna use it as soon as I have to do another presentation. Currently due to lock down that will not happen anytime soon. I will let you know!

Best,

Henrik

**Comment by gitpitch** [comment]
Hi Henrik, I hope you are keeping well under current circumstances. As for feedback, I'll be happy for it whenever your time and opportunity permits. Cheers, David.

**Comment by gitpitch** [comment]
The new support for citations and auto-generated bibliographies with GitPitch slide decks has been [announced](https://twitter.com/gitpitch/status/1264938077056897024). I'm wide open to feedback from anyone testing or using this feature in the wild. Thanks, David.

**Comment by gitpitch** [comment]
Closing this RFE as implemented. If you have additional input please feel free to re-open the thread anytime. Cheers, David.
