### ISSUE TITLE
download offline version from GitPitch Desktop

### ISSUE THREAD

**Issue by rgdonohue** [gitpitch/gitpitch#174]
Currently, it appears changes developed locally using the Desktop app must first be pushed up to the repo and rendered from gitpitch.com/... to be able to download the compiled offline .zip?

**Comment by gitpitch** [comment]
Hi Rich, 

> ...changes developed locally using the Desktop app must first be pushed up to the repo and rendered from gitpitch.com

That is correct, if you want a self-contained offline bundle you do need to download that from gitpitch.com.  

Of course, Desktop itself is the new recommended solution for presenting GitPitch presentations offline. So in many cases if you already have Desktop, there is simply no longer any need to download the offline bundle.

What use case have you in mind that requires the self contained offline zip? Offhand, the obvious one is if you wanted to self-host your presentation - hosting somewhere other than on gitpitch.com. If that's it, you will need the offline bundle and as noted, you get it from the gitpitch.com.

Hope this helps.

**Comment by gitpitch** [comment]
> I wanted to...remove the slide menu entirely.

Just fyi, as a GitPitch Pro subscriber you can remove the burger-menu entirely using the following property in your `PITCHME.yaml`:

```
pro-menus-hidden : true
```

This feature is documented in the [GitPitch Pro Guide](https://gitpitch.com/pro-guide).
