### ISSUE TITLE
GitHub Desktop doesn't render @div

### ISSUE THREAD

**Issue by rgdonohue** [gitpitch/gitpitch#175]
Seems to not work right on the rendered local version with Desktop.

```@div[left-50]
![logo](assets/images/logo.png)
@divend

@div[right-50]
# New maps in the new medium

### Teaching web cartography for a distributed workforce  

[Rich Donohue](https://twitter.com/rgdonohue)  
[Matt Wilson](https://twitter.com/wilsonism)
@divend
```

![image](https://user-images.githubusercontent.com/1952205/39961368-dd49c6fe-55f1-11e8-9334-e52e0477c99b.png)

Pushed up to remote renders with div elements on gitpitch.com/username/branch ... (although the markdown headers simply rendered as text, post as separate Issue?) ...

![image](https://user-images.githubusercontent.com/1952205/39961380-0ce0ad24-55f2-11e8-90e2-dbcbee05316e.png)

**Comment by gitpitch** [comment]
Rich, can you please do a `docker pull` on the GitPitch Desktop image from the Docker store to ensure you have the very latest version installed locally. After the `pull` restart Desktop and let me know if `@div` are rendering as expected.

**Comment by gitpitch** [comment]
> the markdown headers simply rendered as text, post as separate Issue?

With regards this second issue, please note the following:

Content placed within `@div` automatically become HTML snippets, so they are not processed as Markdown. So you must use further HTML snippets, not Markdown syntax, for that embedded content.

For example, instead of this:

```
@div[left-50]
# New maps in the new medium
@divend
```

Use this instead:

```
@div[left-50]
<h1>New maps in the new medium</h1>
@divend
```

**Comment by rgdonohue** [comment]
Yes, the `docker pull` upgrades worked. Thank you!

Good to know about the content within `@div`. Is that a gitpitch thing or how Markdown is rendered within GitHub, etc?

**Comment by gitpitch** [comment]
> Yes, the docker pull upgrades worked. Thank you!

That's great, glad to hear it.

> Good to know about the content within @div. Is that a gitpitch thing or how Markdown is rendered within GitHub, etc?

It's not a GitPitch specific thing. All markdown processors that are compatible with GitHub Flavored Markdown rules behave this way. 

Inline elements within `<div>` are processed as Markdown - for example, Markdown bold `**` or italics `*` syntax on text should work fine.

But block-level elements within `<div>` are not processed as Markdown - for example,  Markdown header elements like `#`, `##`, etc.  Which was your use case.
