### ISSUE TITLE
A typo in wiki Home.md

### ISSUE THREAD

**Issue by pityonline** [gitpitch/gitpitch#176]
Here are two **Bitbucket**s in Home.md:

> 3:### Markdown Presentations For Everyone on GitHub, GitLab, **Bitbucket, BitBucket**, Gitea, and Gogs.
> 27:No more Keynote. No more PowerPoint. Just Markdown. Then git-commit on any branch within a public GitHub, GitLab **Bitbucket, BitBucket**, Gitea, or Gogs repo.

I think the latter should be **GitBucket**, and there should be a comma after **GitLab** in line 27.

**Comment by gitpitch** [comment]
Thanks for pointing these out. I have update the Wiki to reflect the changes you suggested. Thanks again.
