### ISSUE TITLE
Nested Fragments

### ISSUE THREAD

**Issue by chgad** [gitpitch/gitpitch#177]
Hi, im encountering the problem that i want a nested unorderd list to be displayed with the Fragment feature and this screws up the alignment.

Example:
- First Topic
  - sub item 1
  - sub item 2
- Second Topic
  - sub item 1

thsi is how it should look like.
Howeever in my case it looks like this
![gitpitch_issue](https://user-images.githubusercontent.com/21121667/39967933-c5e2cdac-56c4-11e8-8c5c-bdeaf100fc67.png)

As u can see the second "Topic" is **not** correctly aligned

I'm using the following syntax in my `.md`:
```
@ul
- Topic 1
@ulend
@ul
  + test 1
  + test 2
  + test 3
  + test 4 
@ulend

@ul
- Topic 2
@ulend
@ul
  + test 1
  + test 2
  + test 3
@ulend
```

Thanks in advance

**Comment by gitpitch** [comment]
If you can share a link to a slide in a sample presentation that demonstrates the problem you have described I will take a look when time permits.
