### ISSUE TITLE
Can't determine working URL for this file

### ISSUE THREAD

**Issue by solvingj** [gitpitch/gitpitch#179]
https://github.com/AnnArborDetroit-CPP/aadcpp-meetup-content/blob/working_branch/05-2018/PITCHME.md

It's on a feature branch, and in a subfolder, is there a limitation where this scenario doesn't work?

I'm trying this URL and getting "Presentation 404" error:
https://gitpitch.com/AnnArborDetroit-CPP/aadcpp-meetup-content/working_branch?05-2018

If I replace `working_branch` with `master`, it works, but of course it's cached so I cannot get updates in a reasonable timeframe.

**Comment by gitpitch** [comment]
> It's on a feature branch, and in a subfolder, is there a limitation where this scenario doesn't work?

No limitation. If you want to render a `PITCHME.md` within a subfolder you must use the `p` query param on your presentation URL. This is true, regardless of what branch you are using:

For example:

```
https://gitpitch.com/AnnArborDetroit-CPP/aadcpp-meetup-content/working_branch?p=05-2018
```

Click [here](https://gitpitch.com/AnnArborDetroit-CPP/aadcpp-meetup-content/working_branch?p=05-2018) to see your presentation live.

More details on the `p` query parameter [here](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing).

**Comment by solvingj** [comment]
That was it, thank you!
