### ISSUE TITLE
no rhyme or reason around @ul issues

### ISSUE THREAD

**Issue by jerdog** [gitpitch/gitpitch#181]
Working on a new presentation, and in one slide @ul doesn't line up but in next slide it does. 

repo: https://gitlab.com/jerdog/droidconde2018

**Comment by gitpitch** [comment]
Hi Jeremy, no rhyme but perhaps I can give you a reason. 

Here is the original markdown:

```
## More about me
@ul
- 25+ years in Technology
- 18 years in Mobile
- 10+ years in Community/DevRel
- Community/DevRel Consultant
@ulend
```

I believe those `+` symbols are causing the markdown parser to treat the items as nested list items. And that's a bug. And something I will look into further.

But for now, I have a workaround for you to try:

```
## More about me
@ul
- 25&plus; years in Technology
- 18 years in Mobile
- 10&plus; years in Community/DevRel
- Community/DevRel Consultant
@ulend
```

I have simply replaced the `+` with the corresponding HTML character code.

Does give you what you need for now?

**Comment by jerdog** [comment]
#seemslegit.

Thanks!

**Comment by jerdog** [comment]
BTW this workaround did work.

**Comment by gitpitch** [comment]
A patch is now live that addresses the original issue posted on this thread. Jeremy - thanks for reporting this. Closing issue as resolved.
