### ISSUE TITLE
Logo Positioning

### ISSUE THREAD

**Issue by kenrim626** [gitpitch/gitpitch#186]
When using the logo position `bottom-right`, the navigation arrows (the arrows that display the possible directions for navigation) are on top of the logo.

It would be great if they...
- ... would automatically change position relatively to the log (if the logo is 300px high, they would go 300px higher, or in width depending on a property)
- ... could be repositioned in other corners (same as `logo-position`)
- ... could be disabled in presentation view (the one that the audience sees, if speaker mode is activated)

**Comment by gitpitch** [comment]
Support for [auto-repositioning of the navigation controls](https://gitpitch.com/docs/settings/logo/) when *logo-position* is set to **bottom-right** is now live. Also a new custom [controls layout setting](https://gitpitch.com/docs/settings/controls-layout) is now made available. Please try it out and let me know how it goes.
