### ISSUE TITLE
Line numbers in code listing

### ISSUE THREAD

**Issue by dcode** [gitpitch/gitpitch#187]
It'd be helpful for adding line numbers to the code listings. I'm well aware of the [highlight.js maintainer's position](http://highlightjs.readthedocs.io/en/latest/line-numbers.html) on this, but it really doesn't meet all the use-cases, where highlight.js is used.

My usecase is I'm making presentations that contain code for an educational context. I definitely like the code highlight functionality, but that really only facilitates delivery of content. When a student has a question about the code, they have to be like "can you describe that line..no two above that...no you went too far, down one." Line numbers would alleviate this issue.

Fortunately, a kind gentleman, mikemiles86, created a "[reveal.js plugin](https://github.com/mikemiles86/reveal-line-numbers)" just for this reason using CSS counters. It's very clean. The only non-obvious problem to solve is how to apply the `line-numbers` class to the code block. Most of my code listings are code delimiter slides so  you could do:

```
---?code=path/to/source.file&lang=language-hint&line-numbers=1
``` 
:point_up: you could even use the `1` to allow starting line numbers at a different value....  _maybe_ ..I'd be happy with just starting at `1` if that's all that's feasible.

thanks!

Plugin: https://github.com/mikemiles86/reveal-line-numbers

**Comment by IEvangelist** [comment]
Yes, I would love support for line numbers also. It is often helpful when presenting a bit of code to reference the line number when talking about it.

**Comment by gitpitch** [comment]
Support for activating line-numbers within code blocks is now live. See the [new doc here](https://gitpitch.com/docs/code-features/line-numbers/). Please try it out and let me know how it goes.

**Comment by dcode** [comment]
Awesome! Thanks!!
