### ISSUE TITLE
List shortcuts not rendering for master @ 2b6e904

### ISSUE THREAD

**Issue by jknair** [gitpitch/gitpitch#188]
Using the master @ 2b6e904a62a0711c68c8e688f04689f5f999da27 the ```@ul... @ulend``` ```@ol... @ulend``` dont seem to be rendering at all 

<img width="1239" alt="gitpitch-rendering-issue" src="https://user-images.githubusercontent.com/335487/42418220-446a6840-82b9-11e8-89e9-bff11ce42fe4.png">

**Comment by gitpitch** [comment]
Hi, GitPitch [markdown shortcuts](https://gitpitch.com/docs/markdown-features/shortcuts) are unique to the the [GitPitch Enterprise](https://gitpitch.com/docs/enterprise/) server. Which means they are available to everyone on gitpitch.com and to anyone hosting their own instance of *GitPitch Enterprise*.

The open-source server does not support this shortcuts feature.

**Comment by jknair** [comment]
ohk. 
@gitpitch  So it will be very easy for everyone to identify which of these features are enterprise only if they are marked on the Docs and wiki to avoid this confusion. Thank you for the prompt response.

**Comment by gitpitch** [comment]
To close out this issue thread I have adopted the suggestion to update the official docs to indicate features that are not part of the open-source project. See [here](https://gitpitch.com/docs/markdown-features/shortcuts) and [here](https://gitpitch.com/docs/layout-features/snap-position-layouts/) respectively.
