### ISSUE TITLE
Custom language highlighting

### ISSUE THREAD

**Issue by StephenCleary** [gitpitch/gitpitch#189]
I'd like to define and register a [custom `highlight.js` language](http://highlightjs.readthedocs.io/en/latest/language-guide.html).

**Comment by StephenCleary** [comment]
> is your interest truly in adding support for your own custom language(s) or am I simply missing support for some existing language in the highlight.js 9.12.0 bundle?

It's actually my own custom language - one that doesn't technically exist. I'm giving a talk on how different concepts over the last couple decades have transformed how asynchronous code is written, and my illustrations use a language that is kind-of-sort-of-like JavaScript, C#, Python, Java, and C++ combined, but purposely does not match the syntax of any existing language.

I don't expect this to be a common request. :)

For my talk, I'm working around this by just copy/pasting the resulting highlight.js HTML into my `PITCHME.md` and manually fixing it. Not ideal, but it's not a blocker, either.

I did initially try to get this working with a custom script, but couldn't get it to work (and end up at [the issue you mentioned](https://github.com/gitpitch/gitpitch/issues/129)). It's not clear to me what attack vector this is preventing, though. I'll follow up on [that issue](https://github.com/gitpitch/gitpitch/issues/129) with more questions on that front.

**Comment by gitpitch** [comment]
Closing this RFE. Feature not planned for inclusion.
