### ISSUE TITLE
Support for GitLab Snippets

### ISSUE THREAD

**Issue by tjc1575** [gitpitch/gitpitch#19]
I see that GitHub gists are supported to add code to presentations. It would be nice to have support for GitLab Snippets, which are GitLab's version of gists. The snippets are associated with a project so it keeps things more organized.

**Comment by gitpitch** [comment]
It would indeed be nice. Unlike GitHub GIST, currently GitLab Snippets are not embeddable. There are a number of Issues/RFEs [8088](https://gitlab.com/gitlab-org/gitlab-ce/issues/8088) open requesting this feature. It is something I am tracking and once GitLab supports embeddable Snippets I do plan on updating GitPitch to take advantage of this.

It may be worth noting that you can create anonymous GIST on GitHub so you do not even need to have a GitHub account. And you then use those anonymous GIST to build your GitPitch presentation, just like you would use any other GIST.

**Comment by tjc1575** [comment]
I didn't realize that Snippets weren't embeddable. Well hopefully GitLab adds that feature soon. It would be cleaner if I could keep the snippets with the originating project.
