### ISSUE TITLE
Spaces seem to be not supported in image url

### ISSUE THREAD

**Issue by DesHorsley** [gitpitch/gitpitch#190]
Specifically the background image short hand:

`---?image=http://image with space.jpg`
Will not display the background image.

This doesn't work if the string has spaces, or encoded spaces (`%20`)

Sample test url: `https://images.unsplash.com/reserve/oIpwxeeSPy1cnwYpqJ1w_Dufer%20Collateral%20test.jpg`

**Comment by gitpitch** [comment]
Support for spaces within image and video url paths now live on gitpitch.com. When time permits can you please test and let me know how it goes. Thanks.

**Comment by DesHorsley** [comment]
Works like a charm, thanks for the fast support!
