### ISSUE TITLE
Offline gitpitch documentation

### ISSUE THREAD

**Issue by StephenCleary** [gitpitch/gitpitch#191]
Still learning GitPitch and have a long flight coming up next week (hoping to use GP for the talk I'm flying out to give). It would be great if we had access to the [GitPitch documentation](https://gitpitch.com/docs) offline. I poked around the site but didn't see a download option, and `gh-pages` is practically empty. For now I've cloned the wiki from this project, but it would be really nice to have offline docs available from the pro docker container, or at least a PDF download option.

**Comment by gitpitch** [comment]
Nice suggestion. I have just added a one-click download link on the [Offline Slideshow](https://gitpitch.com/docs/foundation-features/offline/) page within the docs. This gives you the complete HTML documentation bundled within a zip archive file. Just expand it and then open the *index.html* file under a local Web server on your desktop.

For example, download the docs bundle and then:

```console
1. unzip docs.zip

# The unzip should expand the zip contents into a gitpitch-docs directory

2. cd gitpitch-docs
3. python -m SimpleHTTPServer
```

Then open the docs in your web browser at https://localhost:8000.

@StephenCleary as you are likely to be the first person to try this out can you please let me know how it goes. Thanks, David.

**Comment by gitpitch** [comment]
No worries Stephen. Best of luck with your upcoming presentation. I'm closing this issue as resolved - the complete docs are now available for download and offline use.
