### ISSUE TITLE
Specify logo element within custom style css?

### ISSUE THREAD

**Issue by jangari** [gitpitch/gitpitch#192]
Not being terribly conversant in css and yaml, I have no idea if this is easy, impossible or anything in between.

I have configured a custom theme for a bunch of presentations, and am looking at configuring a corresponding light coloured theme. The company logo, as defined in the pitchme.yaml, will need to change per theme (white on transparent for the dark theme and dark colours on transparent for the light theme.

Is there a way to have the theme select the correct logo? Either by specifying it in the theme css, or with some tricky yaml code?

**Comment by gitpitch** [comment]
> Is there a way to have the theme select the correct logo?

No, not that I am aware of. You can find a more complete answer/suggestion on how you might achieve the result you want on the related issue thread #193.
