### ISSUE TITLE
Support for multiple custom themes?

### ISSUE THREAD

**Issue by jangari** [gitpitch/gitpitch#193]
As an issue related to #192, is it possible to allow users to select from multiple custom themes, just like the 6 default themes can be selected from the sidebar? I'm envisaging having a light and a dark theme conforming to my organisation's branding, and allow users to select between them, whereas this currently seems to only be doable using the `theme-override` yaml setting.

**Comment by gitpitch** [comment]
> is it possible to allow users to select from multiple custom themes, just like the 6 default themes can be selected from the sidebar?

It is not possible, only a single [custom theme](https://gitpitch.com/docs/themes/custom) can be activated for a given presentation via your *PITCHME.yaml*. And the decision about activating that custom them can only be made by the presentation author - not by the audience (users).

If you want to create two versions of a slideshow presentation where the markdown content is the same but they differ only by the custom styling applied to each presentation then I recommend you look into the docs on [modular markdown](https://gitpitch.com/docs/git/branch-shared-markdown/).

You should end up with a file structure something like this in your repo:

```
.
└── slides
    ├── dark
    │   ├── PITCHME.md
    │   └── PITCHME.yaml
    ├── light
    │   ├── PITCHME.md
    │   └── PITCHME.yaml
    └── shared
        └── slides.md
```

The `slides/shared/slides.md` would contained the actual markdown for your presentation slides.

The `PITCHME.md` found in both the `dark` and `light` directories would contain a single [include delimiter](https://gitpitch.com/docs/git/branch-shared-markdown/#include-delimiter-syntax) pointing at the `slides.md` file. Nothing else.

And then you could set distinct fixed and custom theme setting values in the `PITCHME.yaml` files for each of the respective `dark` and `light` presentations.

Finally, you would then have to share the appropriate slideshow URL if you wanted your users to view the `dark` or the `light` version of the slideshow. See [here](https://gitpitch.com/docs/git/branch-many-slideshows/) to learn how to construct those URLS.
