### ISSUE TITLE
EPS figures not rendered on Chrome

### ISSUE THREAD

**Issue by mrava87** [gitpitch/gitpitch#194]
Hi,
I am making a presentation with some eps figures and adding them as background image. For example:

---?image=assets/images/title_logo.eps&size=50% 100%&position=left&color=#B8DDDE

They seem to work fine and in Safari (PC based) but they are invisible in Chrome (PC based) and Safari (iPhone). Have you ever encountered this problem and is it a known issue with a workaround?

Thank you!

**Comment by gitpitch** [comment]
Hi Matteo, I am not at all familiar with this file type so I have never personally encountered this problem. If you can point me at a sample presentation that I can use to reproduce the problem I will take a closer look.

**Comment by mrava87** [comment]
Hi, thanks for quick reply!
Take a look at slide this sample presentation (slide 9 and those below). I have reproduced the same example I have in a private repo that I cannot share, basically in the first slide I have a eps figure which has transparency (reason why I want to use eps) and the other 2 are the png and jpg version of it (where i tried to replicate the same color as slide background). 

slide: https://gitpitch.com/mrava87/Learning_GitPitch#/9
repo: https://github.com/mrava87/Learning_GitPitch

If you look at the first slide in Safari you will see this 
![eps_slide](https://user-images.githubusercontent.com/22675848/43045813-e4d85a56-8dbf-11e8-9688-c07299804469.png)
while if you look at the png you will see this
![png_slide](https://user-images.githubusercontent.com/22675848/43045814-e5067bfc-8dbf-11e8-9214-794a9e434a33.png)
The first look much nicer, thats why I would like to use eps :)
But if you look at the first slide in Chrome you won't see anything but the text on the right.

Hope this makes sense?

**Comment by mrava87** [comment]
As a quick fix I have actually being able to keep transparency in png :) Eps is definitely better format for high quality vectorial plots but I guess it is maybe better to stay away to avoid suprises when switching in between web browsers ;)

**Comment by gitpitch** [comment]
Here's a little more feedback - that strongly suggests that you are definitely going to want to stick with transparent pngs.

I tried your "Test with eps" slide on Chrome v67 and Firefox 60. In both cases the eps image file **did not display**. The only browser which correctly rendered the image for me here was Safari v11.

This is probably all the data you need - it seems clear that cross browser support for eps image files is anything but consistent. Given this, I would strongly recommend against the use of eps image files for GitPitch presentations to avoid further surprises...

**Comment by mrava87** [comment]
Great thanks a lot for feedback! I did not really put much thinking into it and used the native format of my figure but I can imagine cross browser support is not an easy task ;) I will always convert them to png to avoid surprises..
