### ISSUE TITLE
Code block inside @ul section

### ISSUE THREAD

**Issue by speterson-zoll** [gitpitch/gitpitch#198]
I have the following in a slide:
`@ul

- Add the workspace's `bin` subdirectory to your `PATH`:
    ```bash
    $ export PATH=$PATH:$(go env GOPATH)/bin
    ```
- You can use `$GOPATH` instead of `go env GOPATH` to keep things simple
- To learn more about the `GOPATH` environment variable, type `go help gopath`

@ulend`

It looks great here in GitHub, rendering as I would expect.  However, in GitPitch it renders as 

> bash $ export PATH=$PATH:$(go env GOPATH)/bin

and then each line of the UL appears, with the first line appearing above the bash line.  It seems like Markdowsn is largely ignored inside the @ul tag.  Is this an issue or so I need to take a different approach?

**Comment by gitpitch** [comment]
Hi Scott, the ul tags auto-generate HTML, so everything inside those tags are treated as markup, not markdown. You'll need to take another approach.

You might want to consider replacing your single-tick and tripple-tick markdown code blocks with <code>...</code> tags and see how that goes.

**Comment by speterson-zoll** [comment]
Thanks for the quick reply.  I noticed that the single and triple ticks are being rendered with `<code>` tags, so some translation from Markdown to markup is happening.  I'm not familar with the `...` tags you referenced and I'm not finding any references.  Can you point me in the right direction?

**Comment by gitpitch** [comment]
Try the following syntax:

<img width="867" alt="ul-with-code" src="https://user-images.githubusercontent.com/19169584/43846285-296d79d0-9b58-11e8-828f-d5e259e94d5c.png">

I've had to share a screenshot here to show you the raw markdown, otherwise GitHub would try to render it and you won't be able to see the raw details.

**Comment by gitpitch** [comment]
You can also achieve a solution using just 3 bullet points as follows:

<img width="1377" alt="url-with-code-2" src="https://user-images.githubusercontent.com/19169584/43847440-cd8a76ba-9b5a-11e8-965d-fa1bfab7645c.png">

**Comment by speterson-zoll** [comment]
Ah, OK, thanks.  I hadn't tried it with `<pre>` yet, which took care of it.
