### ISSUE TITLE
PITCHME.md could not be parsed.

### ISSUE THREAD

**Issue by iSatishYadav** [gitpitch/gitpitch#199]
# PITCHME.md could not be parsed.
## Steps to repro
1. Visit https://github.com/iSatishYadav/UnitTesting 
2. Verify contents of PITCHME.md same as provided here: https://github.com/gitpitch/in-60-seconds#step-2-create-a-pitchmemd-file-in-the-root-directory-of-your-repository
3. See results at https://gitpitch.com/iSatishYadav/UnitTesting
4. PITCHME.md could not be parsed.

**Comment by gitpitch** [comment]
Hi Satish, the contents of your `PITCHME.md` are similar but not identical to the contents in the `in-60-seconds` sample file.

If you open your own file in an editor and inspect the file for invisible characters you will see the following is the actual contents of your file:

<img width="495" alt="invisibles" src="https://user-images.githubusercontent.com/19169584/43872197-9d8e8a5a-9baa-11e8-8e50-7c44e480c5bc.png">

Note the two unexpected characters at the start of the file. Delete those characters GitPitch should be able to parse your file.

**Comment by iSatishYadav** [comment]
Wow, that's exactly the issue was. Thanks
Issue resolved after removing those characters.
