### ISSUE TITLE
How to set no border on images?

### ISSUE THREAD

**Issue by martbhell** [gitpitch/gitpitch#2]
I'm not a fan of the black border around the images. Is there a way to disable it?

I'd like to do this especially for logos on a white background.

**Comment by gitpitch** [comment]
Hi @martbhell disabling border styling on images is not currently supported but a broader feature that will permit overriding default styling (including things like image borders) is planned and should be available as early as next week. I'll update this thread once that feature goes live.

**Comment by martbhell** [comment]
Great, login forward to it!

**Comment by gitpitch** [comment]
Check out the new Wiki documentation on [Slideshow Custom CSS](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) for GitPitch presentations. This new feature gives you a lot of power to customize the look and feel of your slideshows, including the ability to remove borders around images.

**Comment by martbhell** [comment]
Thanks! That did the trick :)
