### ISSUE TITLE
Possible to link directly to a slide?

### ISSUE THREAD

**Issue by steverice** [gitpitch/gitpitch#20]
Is this currently possible? Would be very beneficial when referencing something specific but wanting to give others the broader context of a talk.
Thanks!

**Comment by gitpitch** [comment]
Hi @steverice It is possible but you will need to construct the URL yourself. There are two steps involved here:

#### 1. You need to construct a `direct` URL to your slideshow

These `direct` URLs take the following form:

```
https://gitpitch.com/pitchme/slideshow/github/username/repo/branch
```

So for example, the `direct` URL for your slideshow presentation is the following:

```
https://gitpitch.com/pitchme/slideshow/github/steverice/pagerduty-api-v2-deck/master
```

#### 2. Append Slide Specific Fragment

These `slide fragements` take the following form:

```
#/horiz-slide-number/vert-slide-number
```

Note, the `vert-slide-number` is optional. The `horiz-slide-number` points at a `top-level` slide in your presentation. For example, to create a `slide-fragment` that will allow you to point at the 4rd top-level slide in your deck, use this:

```
#/4
```

The `vert-slide-number` points at a vertical slide below a `top level` slide. For example, to create a `slide fragment` that will allow you to point at the 2nd vertical slide below the 4th horizontal slide in your deck, use this:

```
#/4/2
```

### 3. Append Slide Specific Fragment to `direct` URL

Finally, you need to append the slide specific fragment for the slide you want to link to onto the `direct` URL for your slideshow, For example:

```
https://gitpitch.com/pitchme/slideshow/github/steverice/pagerduty-api-v2-deck/master#/4/2
```

You can now share this full URL and whoever opens the URL should see the specific slide you want to point them at. 

Please keep in mind that if you later change the number of slides in your slideshow, these links may no longer be valid.

Final tip, given these `direct` URLs bypass the GitPitch landing page for your slideshow you may also want to share the standard GitPitch URL:

```
https://gitpitch.com/steverice/pagerduty-api-v2-deck
```

This will allow your users to easily start at the beginning of your presentation and also Embed, Share, Print, and go Offline, etc.

If you try this please let me know if it works or if you have any further questions.

**Comment by steverice** [comment]
@gitpitch this is perfect! Thank you so much! Been very impressed by your open-source maintenance of this project.
I'll close the issue, but would you consider adding this to the wiki?

**Comment by gitpitch** [comment]
Glad you now have what you need @steverice. Great suggestion about updating the wiki. I've gone ahead and done that, see the new [Slide Direct Links](https://github.com/gitpitch/gitpitch/wiki/Slide-Direct-Links) page.

Thanks for your positive feedback, it's much appreciated. Any help you can give to get the word about GitPitch to fellow devs is much appreciated too.
