### ISSUE TITLE
Loading different font(s)

### ISSUE THREAD

**Issue by MrCode97** [gitpitch/gitpitch#203]
I tried loading a different font. There for I added:
```
.reveal {
    font-family: 'Open Sans', sans-serif;
}

```
to my PITCHME.md and also:
```
<style>
@import url('https://fonts.googleapis.com/css?family=Open+Sans');
</style> 

```
and then replaced it with:
```
 <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> 
```
 but both ways did not work. Is this not supported or where did I go wrong?

**Comment by gitpitch** [comment]
You indicated that you added your `@import` to your `PITCHME.md`. If you want to add custom CSS to any slideshow, you can only do so by registering a custom CSS file in your `PITCHME.yaml`. Details in the [docs here](https://gitpitch.com/docs/themes/custom/).

Note, if you do manage to load a custom font from a remote URL do keep in mind that it will not work when your are offline.

**Comment by MrCode97** [comment]
My mistake I meant PITCHME.css.
Here is what I tried:
https://github.com/baloise/ws-itsec_owasp/commit/58c22fff0709251b9d1ae12847a248d5f1cf14ec

**Comment by gitpitch** [comment]
A HTML `<link>` tag is a mechanism for loading external resources into a HTML page, like stylesheets. Your `PITCHME.css` is a stylesheet. So you are going to use valid stylesheet syntax. In this case, replace your tag with  a valid [CSS import](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) statement. 

Something like this:

```
@import url("https://fonts.googleapis.com/css?family=Open+Sans");
 
 .reveal {
    font-family: 'Open Sans', sans-serif;
}
...
```

**Comment by gitpitch** [comment]
I see you have used the `@import` in your sample presentation and you have created a test slide that attempts to activate the imported font on some text using your own custom `test-font` css class. A class you have defined as follows:

```
.test-font {
    font-family: 'Fjalla One', serif;
}
```

For this to work, you are going to have to use `!important` on your rule, as follows:

```
.test-font {
    font-family: 'Fjalla One', serif !important;
}
```

If you do this you should then see the desired result:

<img width="541" alt="new-font png" src="https://user-images.githubusercontent.com/19169584/43989908-50f30ebc-9d7d-11e8-87e7-2ce8a32fd502.png">

**Comment by MrCode97** [comment]
That works perfectly. Thanks a lot!
