### ISSUE TITLE
 chart: resolution & size

### ISSUE THREAD

**Issue by MrCode97** [gitpitch/gitpitch#204]
GitPitch / reveal.js seems to render this as an img / picture: But with the resolution set, it seems to me kind of blurry. Also at some point the chart "overflowed" the slide.

How can I change the resolution? How do I scale the chart (because of overflow) ? 
see: https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/2/1

**Comment by gitpitch** [comment]
Charts are not rendered as images (jped, png, etc) but as graphics within a HTML5 Canvas.

The chart on your sample slide does not look particularly blurry to me. Perhaps you should play around with your colors to create sharper contrast.

As for overflow, I do not see any problem on your sample slide. What am I missing here?

**Comment by MrCode97** [comment]
Well, I assume it depends on the resolution of the presenting screen then.. In my opinion it is acceptable but you can see that it is not that "sharp"

Overflow: I realized that by using @snap it will not overflow; therefore I changed it and it was not overflowing anymore. But I changed it back (for now) so you can have a look if you want to:
https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/3/1

**Comment by MrCode97** [comment]
First of all, thanks a lot for your feedback!

About using @snap:
I am aware that this is used @snap[noth|south|midpoint|east|...] but that did not work out for me.. Maybe I am using it wrong?

using (1)@snap incorrect or(2)not using snap gives me that:
https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/2/1 (1)
https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/2/3 (2)

using @snap[position] (correct?) gives me that:

https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/2/2

and other times when I used @snap the output became blurry or the layout did not fit at all and so on (but maybe I did use it the wrong way!). If you want me to search those cases in the history, I can do that. However; I guess I played around with @snap and found that it worked for me when using it in that way (= using snap incorrect=not using snap, but I must have forgotten to delete the "@snaps" or was to lazy or whatever ..therefore you saw so many invalid snap-layouts)

About transitions:
I just looked into that and I think I am going to disable transition by adding

transition : none

to my PITCHME.yaml

if I will be using @snap

**Comment by MrCode97** [comment]
I adapted your solution and also set `transition : none` in PITCHME.yaml

Now it somehow adds several different backgrounds and again the title is blurrier (with snap) check it out:
https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/2/1 (with snap)
https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/3/1 (without using snap)

I am not saying it does not work but I think I will go for a presentation without using snap-layouts (at least for now). But still; thanks for your effort.

**Comment by gitpitch** [comment]
Based on some quick testing this latest issue has nothing to do with *snap-layouts*. It looks like vertical slides, using the `+++` delimiter are having problems cleaning their background images on `none` transitions.

The workaround for now is to use horizontal slides, using the `---` delimiter.
