### ISSUE TITLE
chart: defining the axis

### ISSUE THREAD

**Issue by MrCode97** [gitpitch/gitpitch#205]
I managed to start the y-axis from zero instead of the lowest value (from dataset) by adding:
```
 "options": { "responsive": true, "scales": { "xAxes": [{ "stacked": true }], "yAxes": [{ "stacked": true }] } }
 (according to: https://github.com/rajgoel/reveal.js-plugins/tree/master/chart)
```
but I have not been able to make the "end" of the axis 10 (exept when the highest value from dataset was 10) by adding:
```
 "options": { "responsive": true, "scales": { "xAxes": [{ "stacked": true }], "yAxes": [{ "stacked": true }] }
 "target":"#myplot1",
 "height":1500,
 "width":"1500",
 "xAxis":{"domain":[2004,2017]},
 "yAxis":{"domain":[0,10]},] 
 }
```
 Only workaround I found was to add an additional dataset (only one vlalue / point):
 ```
    "data":[8,4,8,9,9],
    "label":"Trend Broken Authentication","backgroundColor":"rgba(20,220,220,.8)"
   },
   {
    "data":[2],
    "label":"","backgroundColor":"rgba(0,0,0,.0)"
 ```
but that is not really satisfying.
 see: https://gitpitch.com/baloise/ws-itsec_owasp/awareness#/3/1

**Comment by gitpitch** [comment]
This might be an RFE for the [Chart.js project](https://www.chartjs.org/). Or you might at least want to ask over there in case somebody on project can provide you with a better approach.
