### ISSUE TITLE
Night theme overflows

### ISSUE THREAD

**Issue by joachim-n** [gitpitch/gitpitch#207]
See https://gitpitch.com/joachim-n/git-pitch-demo/master#/4 for example.

**Comment by gitpitch** [comment]
The theme you use for your presentation sets numerous style rules for your slide content including default font sizes, margins, borders, colors, etc. So the amount of content you can fit on a slide is a function of (1) the content and (2) the chosen theme.

**GitPitch will not auto-fit arbitrary content onto a slide.** As a presentation author, you can choose a theme. And then develop your content to fit your slides accordingly.

In this case, the styles associated with the `night` theme do not permit your current content to fit on the slide. The most obvious change you could make would be to use a `h2` or `h3` for your slide title. Alternatively, you could use your own custom CSS rules to size the text in your list elements. But changing the header size is a lot easier and makes a lot more sense in this case.

**Comment by joachim-n** [comment]
> GitPitch will not auto-fit arbitrary content onto a slide

I'd actually assumed that was the case, as the size of headings changes for the size of the window.

I'll apply CSS to make it all smaller if that's not the case.
