### ISSUE TITLE
Background opacity stopped working

### ISSUE THREAD

**Issue by MrCode97** [gitpitch/gitpitch#208]
Since a few hours; background opacity does not work anymore. It used to work just fine by using:

`+++?image=/path/to/image.jpg&opacity=35`

Has something changed?

**Comment by gitpitch** [comment]
Background image opacity support is a [GitPitch Pro](https://gitpitch.com/pricing) feature. See the the [docs](https://gitpitch.com/docs/image-features/opacity) for details. If you have activated a Pro subscription and the opacity feature is not working, please let me know.

The opacity feature had been enabled recently for a short while for all presentations - temporarily - to support some testing I was doing. That testing is now completed. Regular free v pro feature support has resumed for all users.

**Comment by MrCode97** [comment]
I am not using a Pro subscription and were not aware of that fact. Therefore it makes sense that it stopped working. Thank you for your quick replay.
