### ISSUE TITLE
add a vertical slide using markdown

### ISSUE THREAD

**Issue by opensas** [gitpitch/gitpitch#210]
To create a vertical slide in reveal.js you have to nest "section" elements.

Is it possible to achieve the same using the PITCHME.md approach?

How should I embed the section html to accomplish that?

**Comment by gitpitch** [comment]
See the [slide delimiters](https://gitpitch.com/docs/getting-started/delimiters/) doc for a description of how to create horizontal and vertical slides. You can also take a look at the [kitchen sink sample presentation](https://gitpitch.com/gitpitch/kitchen-sink) for a live demonstration of horizontal and vertical slides.
