### ISSUE TITLE
Pro subscription not working with organization / GitHub Education

### ISSUE THREAD

**Issue by lisah2u** [gitpitch/gitpitch#214]
Hi, I signed up for the pro subscription which works great for offline development. But when I try to use it with content under GitHub Education (org name idia640), my subscription does not recognize me as a pro user and I can't activate surveys for presentations I designed for class use. I would love it if this could be corrected in some way!

**Comment by gitpitch** [comment]
Hi Lisa,

>  I would love it if this could be corrected in some way!

You have the option to switch your current subscription from your `lisah2u` personal account to the `idia640` organization. I will follow up with you by email to provide further details so we can discuss.
