### ISSUE TITLE
Parentheses inside syntax shortcut

### ISSUE THREAD

**Issue by agoluberg** [gitpitch/gitpitch#217]
Parentheses (more precisely ending parenthesis) cannot be used inside syntax shortcuts:
`@css[my-class](want an ending ) here)`
also this doesn't work:
`@css[my-class](let's try to escape \) here)`

Is there a way to use `)` inside syntax shortcut?

**Comment by gitpitch** [comment]
You should be able to use the corresponding HTML character code for the left-parenthesis if you want that left-parenthesis to be rendered on your slide, for example:

```
@css[my-class](want an ending &#41; here)
```

Let me now how it goes.

**Comment by agoluberg** [comment]
Thanks for the quick reply! This indeed works. But I actually want to have style with code. I have something like that:

```
`"`@css[u](`(ab&#41;?cd`)`"`
```

The output has `&#41;` in it.

I can however do something like that:
```
`"`@css[u](`(ab`&#41;`?cd`)`"`
```

(regular expression where the string between quotes is underlined)

So the `)` gets inside the `css`, but is not interpreted as code. I guess I could change the css for `u` class so that it looks the same.

Just wanted to know, whether there is a better way for that.

**Comment by gitpitch** [comment]
Yeah, the HTML character encodings within these kinds of fenced code blocks will not be decoded when rendered. In truth I've never seen anyone use `@css` shortcut syntax wrapped around fenced code blocks like this before. Interesting. Anyway, I don't have any alternative workaround for you, so your own solution is the one to go with.
