### ISSUE TITLE
Clarification on Markdown Shortcurts

### ISSUE THREAD

**Issue by jerdog** [gitpitch/gitpitch#219]
So on https://gitpitch.com/docs/markdown-features/shortcuts/ it says:
>Note: The Markdown Shortcuts feature is supported by gitpitch.com, GitPitch Desktop, and GitPitch Enterprise. This feature is not part of the GitPitch open source project.

However when I load up the gitpitch open source project locally it seems like some of them actually do work..

<img width="1309" alt="screenshot 2018-10-12 16 43 08" src="https://user-images.githubusercontent.com/296864/46879426-f8f60600-ce3d-11e8-9d3f-a5f4ecf139cb.png">

with the `@snap[----]` at least working. Can you clarify, and maybe let some more of them work?

**Comment by gitpitch** [comment]
Hi Jeremy, the only shortcut from the set of shortcuts listed in the [documentation](https://gitpitch.com/docs/markdown-features/shortcuts) that is supported by the open source server is the `@fa` shortcut for rendering Font Awesome icons on your slides.

All other shortcuts are implemented by the pro server only. So those features are available to everyone - free and subscribers - on gitpitch.com. 

I'm not sure what `PITCHME.md` markdown or custom css styles were used to generate the screenshot you shared on this thread but if it was an open source server then `@snap` shortcuts were not used to render the sample slide.

**Comment by gitpitch** [comment]
When you say you downloaded it do you mean you clicked on the `Offline Version (.zip)` in the slideshow menu made available for all presentations on the gitpitch.com?

This [offline feature](https://gitpitch.com/docs/foundation-features/offline/#one-click-offline-slideshow-download) gives you a self-contained static bundle with all dependencies for the specific presentation. 

The offline bundle is not the same as running your own instance of the open source server. Which you can also do, per the [following instructions](https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions).

So if you are simply taking your presentation offline from gitpitch.com then all features will work offline. But if you are using the open source server to render your presentations then - as noted above - the only shortcut supported from the set of shortcuts listed in the documentation is the @fa shortcut for rendering Font Awesome icons on your slides.

**Comment by jerdog** [comment]
Ahh interesting - so yeah I did use the Offline download. My apologies for
confusing the things. However, I have not been able to make the other @
features work, but will have to try again to get specifics.
