### ISSUE TITLE
Wondering if building own server (as per wiki), will this allow viewing private gitlab repos?

### ISSUE THREAD

**Issue by Analect** [gitpitch/gitpitch#22]
I have a use-case to present pitchme's from non-public repos on my self-hosted gitlab server ... is that possible to do with a local pitchme server install?  Thanks for your great project.

**Comment by gitpitch** [comment]
Hi @Analect thanks for your feedback, glad you like this project. Unfortunately for you, private repos are not currently supported. Only PITCHME in public repos can be rendered as slideshow presentations. So it will not matter if you are using your local self-hosted server or [GitPitch.com](https://gitpitch.com). I know this is not the answer you were hoping for, apologies for that.

**Comment by Analect** [comment]
OK. Thanks for the clarification.
