### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by georgi-bozhinov** [gitpitch/gitpitch#220]
Hello,

I know this might be a duplicate, but all the issues about local development ( viewing the presentation on a local server for example without pushing to github ) make reference to a link in the [wiki](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally) that does not exist, not for me at least, it gives me a you have no permission to edit this wiki error. Is there any way to do this? 

Thank you,
Georgi

**Comment by gitpitch** [comment]
Hi Georgi, the old Wiki has been replaced by the new and much improved [GitPitch Docs](https://gitpitch.com/docs). The root page in the Wiki now links to those docs. But as you found, the inner page you referenced is now a dead link.

For offline development there is now **GitPitch Desktop**. It's a subscriber only feature. And you can find more details about the Desktop and static downloads in the [Offline Docs](https://gitpitch.com/docs/foundation-features/offline/).

**Comment by georgi-bozhinov** [comment]
Thank you.
