### ISSUE TITLE
Is there something wrong with graph colors?

### ISSUE THREAD

**Issue by aalmada** [gitpitch/gitpitch#222]
The graphs in the feature-demo repository appear grayed out. Only the line graph seems to show colors correctly.

https://gitpitch.com/gitpitch/feature-demo/charts#/3

**Comment by gitpitch** [comment]
Hi Antão, for the charts to render properly according to their properties I should be using the *JSON property syntax* from the Charts plugin consistently. I have just updated the sample `PITCHME.md` markdown to demonstrate the proper usage in all cases. If you open the sample presentation once again you will see each chart is now rendered as expected per the *color* and *label* properties. Thanks for bringing this to my attention.

**Comment by aalmada** [comment]
For some reason I thought a default palette would be used. Thanks for the clarification.
