### ISSUE TITLE
Set document title

### ISSUE THREAD

**Issue by brunns** [gitpitch/gitpitch#226]
Is there a way to set the presentation document's title, i.e. the content of the HTML `<title>` tag?

**Comment by gitpitch** [comment]
> Is there a way to set the presentation document's title, i.e. the content of the HTML <title> tag?

Not currently.

I have thought in the past about populating the <title> tag on presentation pages with any value specified  on the [footnote setting](https://gitpitch.com/docs/settings/footnote). And I guess there could be a case for a new, dedicated *title setting* to deliver this as a feature.

I'm interested in feedback, so will leave this issue open for comment.

**Comment by brunns** [comment]
Yeah, I actually tried setting a `title` in my `GITPITCH.yaml` in case it was an undocumented feature. :-) I'd certainly appreciate it if it were.

**Comment by gitpitch** [comment]
Simon, please check out the [GitPitch Pro Bonus Features](https://gitpitch.com/docs/pro-features/bonus) guide. It has been updated to document support for a new **title** setting. If you have a chance to try this out can you please let me know how it goes.

**Comment by brunns** [comment]
That works a treat, thank you.
