### ISSUE TITLE
Make video background loop

### ISSUE THREAD

**Issue by Fed03** [gitpitch/gitpitch#227]
Hi, 
First of all many thanks for this incredible tool!
I would like to use a video background like a gif. Now I saw that Reveal.js allows this https://github.com/hakimel/reveal.js/#video-backgrounds so maybe it could be a good idea to include that options into the "query string" of the video background

what do you think?

**Comment by gitpitch** [comment]
Hi Federico,

> First of all many thanks for this incredible tool!

You're very welcome, glad you like it.

> what do you think?

Nice idea. I will add it to my TODO list. I have no ETA for this feature but will update this thread when I have something for you to try.

**Comment by Fed03** [comment]
Thank you for the super quick answer!
If I'll be able to find time to work on on this on my own and send a PR
I'll let you know

Il giorno mar 27 nov 2018, 11:20 David Russell <notifications@github.com>
ha scritto:

**Comment by gitpitch** [comment]
Experimental support for new video **loop** and **muted** params on [background video delimiters](https://gitpitch.com/docs/rich-media-features/background-videos/) is now live on gitpitch.com.

To automatically *loop* a background video simply activate the **loop** parameter on the delimiter, for example:

```
---?video=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4&loop=true
```

To automatically *mute* a background video simply activate the **muted** parameter on the delimiter, for example:

```
---?video=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4&muted=true
```

You can of course both *loop* and *mute* as follows:

```
---?video=http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4&loop=true&muted=true
```

By default, both **loop** and **muted** are disabled.

Federico, can you please test this new behavior and let me know how it goes. Thanks.

**Comment by Fed03** [comment]
I'm astonished O_o
You are 🥇

All working as expected, thanks! I'll let you know if I find something odd

**Comment by gitpitch** [comment]
Great. Thanks for suggesting this feature, for testing, and providing feedback. Closing issue as resolved.
