### ISSUE TITLE
gitpitch can't render "@" sign properly with gitea

### ISSUE THREAD

**Issue by LaughingBlue** [gitpitch/gitpitch#230]
Here are some screenshot about gitpitch/the-template
Expect:
![annotation 2018-12-24 234843](https://user-images.githubusercontent.com/17382936/50403081-befa9600-07d6-11e9-86cf-3b7d0e9f2960.jpg)
But with my gitea:
![annotation 2018-12-24 234904](https://user-images.githubusercontent.com/17382936/50403103-e2254580-07d6-11e9-8eec-48890b66e338.jpg)
I can't get proper rendering with all `@[act](text)` kind syntax on gitea.
I'm using Gitea, 1.6.1

**Comment by gitpitch** [comment]
The `@[act](text)` syntax is the markdown shortcut syntax used to deliver [snap layouts](https://gitpitch.com/docs/layout-features/snap-position-layouts/) and [related features](https://gitpitch.com/docs/markdown-features/shortcuts). These features are not part of the open source server. Only standard markdown is supported by that server. Hence the rendering your are seeing.
 
You can use these markdown extensions on [gitpitch.com](https://gitpitch.com) or when working directly with a self-hosted [GitPitch Enterprise](https://gitpitch.com/enterprise) server.

**Comment by LaughingBlue** [comment]
Oh, I see. Thank you:)
