### ISSUE TITLE
The slideshow URLs in docs are images

### ISSUE THREAD

**Issue by missmatsuko** [gitpitch/gitpitch#231]
Can they be `<pre>` instead of `<img>` so people can copy, paste, and edit them easily?

https://gitpitch.com/docs/getting-started/urls

**Comment by missmatsuko** [comment]
@gitpitch Was it enough of a problem that users were complaining about it? If they realized they forgot to change the url after seeing the 404 message, I don't think it's a big deal. Or maybe there could be message at that URL to say they forgot to change the URL for their repo?

At the very least, can the alt text for the images be updated to reflect the contents of the image? Currently the URL won't be accessible for people using screenreaders, if the image failed to load for some reason, if the page content was copied and pasted into plain text, etc. etc.

**Comment by gitpitch** [comment]
> Was it enough of a problem that users were complaining about it?

Indeed, yes. Hence the current use of images. As for a message, the 404 page already includes a link back to the [URLs page](https://gitpitch.com/docs/getting-started/urls/) in the docs so people get help where they need it - on a 404.

> At the very least, can the alt text for the images be updated to reflect the contents of the image? 

That can be done. I'll open this issue again so I will remember these changes need to be made.

**Comment by gitpitch** [comment]
The template URLs in the [docs](https://gitpitch.com/docs/getting-started/urls/) have been updated:

1. The images are now hyperlinked so you can click to open plus
1. The alt text has been updated to reflect the template URL path
