### ISSUE TITLE
Slide counter is a link for some reason

### ISSUE THREAD

**Issue by missmatsuko** [gitpitch/gitpitch#233]
The slide counter at the bottom right of the slide deck (e.g. https://gitpitch.com/gitpitch/kitchen-sink#/) is a link to the current slide. This seems unnecessary, could be just text.

**Comment by gitpitch** [comment]
Yep, the link serves no purpose today, just an artifact. Thanks for brining this to my attention.

**Comment by gitpitch** [comment]
I have just verified that the slide counter anchor is an artifact of the underlying reveal library. For compatibility sake this is not something I am going to change here. Closing.
