### ISSUE TITLE
Issue wrapping a fenced code block in a css[fragment]()

### ISSUE THREAD

**Issue by aviaviavi** [gitpitch/gitpitch#234]
I have a multline fenced code block, that i'd like to be able to transition into the slide via the `css[fragment]()` functionality. It works fine when I have a single line of text, but for something like

> @css[fragment](
>  ```
> some
> code
> here
> ```
> )

Which doesn't seem to render properly

example:
https://gitpitch.com/aviaviavi/talks/fragments?grs=github&t=beige&p=intro-to-parsers-2019-01#/5

Am I doing something wrong, or is this a bug?

**Comment by gitpitch** [comment]
Hi Avi, my answer is in two parts.

First, the `@css` shortcut is not a block element so it does not support multiline content. So in this case, it is not the right tool for the job.

Second, if you want your code blocks to behave as fragments they will require special processing. You have two options:

#### Option 1: Basic Approach

Replace the triple-backticks with `<pre><code>` syntax and activate the `fragment` class directly on the `<pre>` element, as follows:

```
### What we're used to

@css[text-09 fragment](For simple things, just checking a few conditions directly works fine. For instance, grabbing content between brackets.)

<pre class="fragment"><code>[parse_this]
</code></pre>

<pre class="fragment"><code class="lang-haskell">s :: Text

...
if head s == "[" && last s == "]"
then Text.replace "]" "" (Text.replace "[" "" s)
</code></pre>
```

#### Option 2: Advanced Approach

If you are a GitPitch Pro subscriber you can take advantage of the [@code markdown widget](https://gitpitch.com/docs/markdown-features/pro-widgets) which -  among other benefits - helps to greatly simplify the markdown:

```
### What we're used to 

@css[text-09 fragment](For simple things, just checking a few conditions directly works fine. For instance, grabbing content between brackets.)

@code[text fragment](src/snippets/parse.txt)

@code[haskell fragment](src/snippets/parse.hs)
```

Either approach should give you what you need.

**Comment by aviaviavi** [comment]
Thanks so much for the response @gitpitch! Used this for a talk last night and it worked very well :)
