### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by DavidTNguyen** [gitpitch/gitpitch#235]
My docker-compose and and IDE I have (atom, vscode, intellij) don't seem to play well together.  It froze up.  It stopped reload both the deck and my editor.

```version: '3'
services:
  gitpitch:
    image: gitpitch/desktop:pro

    volumes:
     - ~/dev/myworkingdir:/repo

    environment:
      - "GP_HOST=localhost"
      - "GP_PORT:9000"
      - "GP_GITHUB_AS_DEFAULT=true"
    
    ports:
      - 9000:9000```

**Comment by gitpitch** [comment]
David, 'm moving this thread over to GitPitch support. You will hear from me by email shortly.
