### ISSUE TITLE
Is there a short-hand way to hyperlink out to a file in my git repo

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#236]
When I build a presentation file, I often have tutorial resources that I would like to link out to.

For instance, if I want to hyperlink out to my README file, I would want to enter something like `[README](README.md)` in Markdown.

I know that I can hard-code a link to my git repo, but when I do that I need to specify a branch name.  I would like to be able to link out to a code file that resides in the same branch as the presentation file.

**Comment by gitpitch** [comment]
Hi Terry,

> For instance, if I want to hyperlink out to my README file, I would want to enter something like `[README](README.md)` in Markdown...I would like to be able to link out to a code file that resides in the same branch as the presentation file.

Nice idea. So I have just gone ahead and implemented a new shortcut syntax to make this very easy for you. So traditionally you would define a link as follows:

```
[README](README.md)
```

Now you can use a new `@gitlink` shortcut prefix to automatically convert a link in you presentation to a link on the corresponding file on GitHub, GitLab, or Bitbucket repo. And this shortcut syntax is branch aware etc.

The new syntax in your **PITCHME.md** would look as follows:

```
@gitlink[README](README.md)
```

And you can link to files at any level in your repository structure, for example:

```
@gitlink[SAMPLE CODE](src/python/hello.py)
```

I haven't had time to update the GitPitch docs yet but hopefully this note gives you enough to get going. This feature is now live on gitpitch.com. And will be available in an updated GitPitch Desktop within the next 24 hours. 

If you do test this new feature out I would appreciate feedback letting me know how it goes. Cheers, David.

**Comment by terrywbrady** [comment]
@gitpitch ,

This is a fantastic addition.  Thank you.

I settled on the following code which does exactly what I need.

```
@gitlink[Windows 10 Setup](documentation/setup.Windows10.md)

@gitlink[MacOS Setup](documentation/setup.MacOS.md)

@gitlink[Linux Desktop Setup](documentation/setup.LinuxDesktop.md)
```

I had initially wanted to do the following.

```
- @gitlink[Windows 10 Setup](documentation/setup.Windows10.md)
- @gitlink[MacOS Setup](documentation/setup.MacOS.md)
- @gitlink[Linux Desktop Setup](documentation/setup.LinuxDesktop.md)
```

This caused some formatting issues, so I tried adding the `@ul ...  @ulend`

I still saw had some formatting issues with the following:

```
@ul 
- @gitlink[Windows 10 Setup](documentation/setup.Windows10.md)
- @gitlink[MacOS Setup](documentation/setup.MacOS.md)
- @gitlink[Linux Desktop Setup](documentation/setup.LinuxDesktop.md)
@ulend
```

Thank you for the quick response!

**Comment by gitpitch** [comment]
Thanks for this quick and detailed feedback. Honestly I hadn't yet tested use of this new syntax as items within lists etc. But I will do so. And bump this thread when I have updates for you to try out.

**Comment by gitpitch** [comment]
Support for the new `@gitlink` markdown shortcut has been updated. @terrywbrady it should now support all of the use-cases you described and more. Patch live on gitpitch.com. Again, if you have a chance to test I'm very thankful for any feedback you can provide.

**Comment by terrywbrady** [comment]
@gitpitch , the formatting is working for me now.  thanks again

**Comment by gitpitch** [comment]
Terry, tanks for the additional testing and feedback.

The GitPitch Desktop now recognizes this syntax too - although keep in mind when viewing a deck in the Desktop these links go to `#`, ie, the page you are on. That is because in the Desktop there is no connection with GitHub, GitLab, or Bitbucket. But when you push your slides to an upstream repository, the links will automatically activate, taking you to the corresponding repo files. For instructions on how to update your local copy of GitPitch Desktop, see the docs [here](https://gitpitch.com/docs/pro-features/desktop-faq).

Closing this issue as resolved.

**Comment by gitpitch** [comment]
Just FYI, the GitPitch docs have been updated with a description of the new `@gitlink` markdown shortcut. See [here](https://gitpitch.com/docs/markdown-features/widgets/).
