### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by noraj** [gitpitch/gitpitch#237]
No, answer from #220, #191, #174, #147 are not answering this issue.

That doesn't answer the local development/presentation question, actually we can:
- Buy the 4$/month subscription: `Works with local file system`, `Live previews in the browser` and `A dedicated Desktop App`. But it seems it still require the bundle from gitpitch.com to work offline (#174). 
![image](https://user-images.githubusercontent.com/16578570/52901410-673f4080-3203-11e9-896a-8fdfe9809368.png)
- Free: upload a PITCHME.md file to a public repository, edit it locally, re-push, preview, edit it locally, re-push, preview, edit it locally, re-push, preview then download the build and serve it. If a modification is needed?  edit it locally, re-push, preview, then re-download. And not talking about slideshow that you do not want to put online or if you have no internet connection.

But actually people need a little gitpitch CLI tool just to preview an offline slideshow with liveload (not building the bundle or PDF). This only require an embedded web server and a javascript markdown renderer script **like reveal.js is already doing**: 

> You'll also need to add the plugin/markdown/marked.js and plugin/markdown/markdown.js scripts (in that order) to your HTML file.
>
> This is based on data-markdown from Paul Irish modified to use marked to support GitHub Flavored Markdown. Sensitive to indentation (avoid mixing tabs and spaces) and line breaks (avoid consecutive breaks).
>
> [Source](https://github.com/hakimel/reveal.js/#markdown)

**Comment by gitpitch** [comment]
> This only require an embedded web server and a javascript markdown renderer...

The GitPitch server performs significant pre-processing of slide content to deliver the full set of features available to slide decks served online at [gitpitch.com](https://gitpitch.com). The same pre-processing is required to serve slide decks generated by [GitPitch Desktop](https://gitpitch.com/docs/pro-features/desktop) offline.

The simple CLI tool w/ embedded web server you are requesting makes sense for simple reveal.js presentations. But will not work for GitPitch slide decks.

**Comment by noraj** [comment]
Smart answer, you mean "Pay". There is the desktop tool but you can do the same tool without a GUI. And there is the server but the server will work only for instance of gitlab, github, etc. why can't the server render a local directory? The true answer is: "because we want for people to pay". That's why you provided a bundled zip where the markdown was compiler as html instead of keeping the markdown file and loading it from a JS library so that people can't modify it easily offline. We are forced to use the online gitpitch.com with reduced feature or pay to get offline.

So GitPich is not free, it is freemium.
So GitPitch is not open source but mostly closed source (docker, gitpitch desktop) with partial open source code (server and revealjs fork).
But that is right to be a paid and closed source software  but as there is no description of the free plan here https://gitpitch.com/pricing, one begin to use the tool until he realizes that the free plan is more a demo or very reduced version and that he won't be able to do what he though I will be able to do for free.

So there is one action you **must** do: add the description of the free plan like GitHub did so people won't be deceived as I was:

![image](https://user-images.githubusercontent.com/16578570/53124995-1f028400-355d-11e9-9c71-a8b523c5c9ee.png)

Also most a the features of the Lite, Pro or Enterprise plan are enterprise there is nothing done for individuals.

An individual just want to make a presentation and be able to do it offline not to have it delivered by docker, export slide to PPTX, keynote, google slides, etc. Will I pay 50$/yr to do 1 presentation per year to make a conference I'm not paid for? Of course not only an enterprise can afford that.

**Comment by gitpitch** [comment]
Thanks for your suggestion. The GitPitch [pricing](https://gitpitch.com/pricing) page now links directly to the GitPitch [community features](https://gitpitch.com/free-features) page. That page provides a high-level summary of the *free features* available to everyone on GitHub, GitLab, and Bitbucket.

With regards your *nothing-for-individuals* comment. The [GitPitch Documentation](https://gitpitch.com/docs) provides detailed guides for all features. If you read these docs you will see that the vast majority of features are free. And that feature list is extensive. Where a feature is *subscription-only*, that feature is clearly marked as such.

Ultimately, you appear to be looking for a free, offline slideshow tool. Ok. GitPitch is not for you. There are numerous other options out there for you to try. The old favorites PowerPoint and Keynote. Use reveal.js directly. Or try a markdown editor like Marp. Best of luck finding the tool that's right for you.

**Comment by noraj** [comment]
Instead of a hero announcing GitPitch Community  features I was more thinking about a 4th column so it will be very clear!

![image](https://user-images.githubusercontent.com/16578570/53194313-5cc1e400-3613-11e9-8ede-e0526bfc2fa0.png)

**Comment by noraj** [comment]
@gitpitch Thanks for suggestions, I knew Marp but the old deprecated version now the New Marp Next project is exactly what I need! Thanks.
