### ISSUE TITLE
Font Awesome: upgrade to version 5

### ISSUE THREAD

**Issue by noraj** [gitpitch/gitpitch#238]
Font awesome is still using Font Awesome 4.7.0 and generate icon like this:

```html
<i class="fa fa-thumbs-up" aria-hidden="true"> Sounds good to me!</i>
```

But for example the [markdown](https://fontawesome.com/icons/markdown?style=brands) icon is not working.

For example

```
@fa[markdown fa-5x]
```

Is producing:

```html
<i class="fa fa-markdown fa-5x" aria-hidden="true"> </i>
```

But nothing is displaying.

Here is the upgrade guide https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by gitpitch** [comment]
> But for example the [markdown](https://fontawesome.com/icons/markdown?style=brands) icon is not working.

As you noted, GitPitch currently [supports](https://gitpitch.com/docs/rich-media-features/font-awesome/) the Font Awesome 4.7 icon set. That 4.7 icon set - see [here](https://fontawesome.com/v4.7.0/icons/) - does not offer an `fa-markdown` icon. That is why nothing is displaying on your sample slide.

Upgrading to Font Awesome 5.0 is on my TODO list. Thanks for this RFE. I'll leave it open and see if it attracts additional upvotes.

**Comment by gitpitch** [comment]
GitPitch now supports Font Awesome 5. Details for working with FA5 *solid* and *brand* icons in the [docs](https://gitpitch.com/docs/rich-media-features/font-awesome).

**Comment by noraj** [comment]
@gitpitch Very nice, thanks for everyone.
