### ISSUE TITLE
Parametrized path to PITCHME.md 

### ISSUE THREAD

**Issue by ikalnytskyi** [gitpitch/gitpitch#24]
(this is a feature request)

It'd be nice to be able to pass a path to `PITCHME.md` so I can have multiple presentations within a single repo and branch. Example:

```
|-- talk-1
|   `-- PITCHME.md
|-- talk-2
|   `-- PITCHME.md
|-- talk-3
|   `-- PITCHME.md
`-- README.md
```

Any chance to see it in near future? Because right now it's the only significant lack that prevent me from using GitPitch.

**Comment by gitpitch** [comment]
Hi @ikalnytskyi glad to hear you are trying out GitPitch. So in truth I don't really see me adding this feature as you have described anytime soon for two reasons:

1. GitPitch uses a simple, consistent convention of looking for a PITCHME.md in the root directory of any public repo and your proposal breaks with that convention and I'm not yet convinced we need to break it.

2. Git already provides a native (natural) solution to this type of problem via feature branches, a feature that GitPitch supports out-of-the-box.

You only need a single repo. Within that single repo you can create a collection of talks (presentations), where each talk is maintained within it's own feature branch: `talk-1`, `talk-2`, `talk-3`, etc.

Then all talks are uniformly named (addressed) by GitPitch as follows:

```
https://gitpitch.com/ikalnytskyi/talks-repo/talk-N
```

Maybe you can still convince me, is there some reason why the feature branch approach does not work for you?

**Comment by ikalnytskyi** [comment]
@gitpitch Thanks for the answers.

1. > GitPitch uses a simple, consistent convention of looking for a PITCHME.md in the root directory of any public repo and your proposal breaks with that convention and I'm not yet convinced we need to break it.

  Why to break anything? It's a good default that I'd like to see anyway. All I ask is just to introduce maybe a new URL that receives relative path to the file.

2. > Git already provides a native (natural) solution to this type of problem via feature branches, a feature that GitPitch supports out-of-the-box.

  Unfortunately that would work only for trivial cases. What if I need some common stuff? I don't want to cherry-pick changes upon a lot of branches each time I need to change that common stuff (like theme branding or something like that). Or what if I want to somehow store slide sources within my blog sources, and convert them into html/pdf when I build my blog?

  I don't say it's not possible to achieve with current approach. It's just a bit inconvenient, in my opinion.

**Comment by gitpitch** [comment]
Hi @ikalnytskyi thanks for explaining your use case. The benefit of sharing common stuff is a good example, I get it. Typically I use GitHub pages to store common assets (such as images, css files, etc) and then I use absolute URLs to those assets in my presentations. So a single change to those assets is picked up by all dependent presentations without having to make branch-by-branch changes.

That said, I will take a look at what can be done to give you what you need and I will update this thread over the next few days. The most likely solution will involve a new query param on the URL for your presentation. Something like this:

```
https://gitpitch.com/user/repo?m=talk-1
```

In this example, GitPitch would render the `PITCHME.md` found under the `talk-1` directory found at the base of your repo.

In general, the value for the `m` param would simply identify any directory path within your repo. Within that directory GitPitch will still expect to find a `PITCHME.md`. When the `m` parameter is not specified GitPitch will simply revert to its default behavior.

**Comment by gitpitch** [comment]
@ikalnytskyi I have just pushed initial support for this feature request live on `gitpitch.com`.

You can now specify a new query parameter `p` on any slideshow url. This parameter allows you to specify a relative directory within your repo where GitPitch will look for the `PITCHME.md` and  `PITCHME.yaml` for a given presentation.

For example, based on your initial RFE feedback, the URL for your `talk-1` presentation within the `master` branch for the `talks-repo` would look as follows:

```
https://gitpitch.com/ikalnytskyi/talks-repo?p=talk-1
```

The URL for your `talk-2` presentation within the `dev` branch for the `talks-repo` would look as follows:

```
https://gitpitch.com/ikalnytskyi/talks-repo/dev?p=talk-2
```

Note (1), due to [GitPitch caching policies](https://github.com/gitpitch/gitpitch/wiki/GitPitch-Caching) it is still strongly recommended to develop your presentations within a feature branch, not within the `master` branch. 

Note (2), this support only changes where the server looks for your `PITCHME` files. All other files addressed at relative paths, such as paths in your Markdown to image or css assets, are relative to repo root directory. This makes it simple for multiple presentations to share common assets.

When you have time can you please test this and let me know how it works out. If you can confirm for me that the feature support is stable and reliable I will merge the feature into the GitPitch `master`.

**Comment by gitpitch** [comment]
FYI the [GitPitch Wiki has been updated](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Management) to document this new feature.

**Comment by ikalnytskyi** [comment]
@gitpitch thank you very much! I'll definitely take a look within couple of day as I need to prepare a talk to upcoming conference. I'll provide my feedback as soon as possible. :)

**Comment by gitpitch** [comment]
Hi @ikalnytskyi just checking in to see if you have had a chance yet to test/verify this new feature?

**Comment by varac** [comment]
@gitpitch @ikalnytskyi  Awesome, thanks! I was interested in the same feature - will report back soon.

**Comment by gitpitch** [comment]
I'm closing this issue as resolved as the feature is now supported as [documented here](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing). If anyone has any feedback please feel free to update the issue thread. Of course you can re-open the issue if you have hit any problems with this feature.

**Comment by lisah2u** [comment]
Is it possible to add a second parameter to a url such as https://gitpitch.com/user/repo/branch?p=talk-3 for the purpose of viewing speaker notes? More specifically, do you support multiple parameters to account for viewing notes (n=true)?

**Comment by gitpitch** [comment]
The parameters on a GitPitch presentation URI are just a regular [query string](https://en.wikipedia.org/wiki/Query_string) so you can pass as many parameters as you like.

For example, to pass a second parameter to view speaker notes you can do as follows:

```
 https://gitpitch.com/user/repo/branch?p=talk-3&n=true
```

The speakers notes for the presentation found in the `talk-3` directory will now be displayed.
