### ISSUE TITLE
Cannot access GITPITCH.md using Gitlab private repository

### ISSUE THREAD

**Issue by RopoMen** [gitpitch/gitpitch#240]
Hi,

I have self hosted Gitlab CE 11.8.0 and I have private repository which contains GITPITCH.md. I was testing this docker image https://hub.docker.com/r/knsit/gitpitch 

I was unable to get my test slide to show up. I thought that I had issues with my personal API key, but I tested with curl and api/v4 request worked fine. When Gitpitch was requesting files from repository 
```
grsLink=http://git.example.com/USER/REPOSITORY/raw/master/PITCHME.yaml?gp=0
```
request got redirected in to login page. 

<img width="1150" alt="screen shot 2019-02-26 at 15 27 59" src="https://user-images.githubusercontent.com/7492812/53416289-da9f3a00-39db-11e9-8fcd-b205384ba877.png">

I started Googling and found possible issue https://gitlab.com/gitlab-org/gitlab-ce/issues/54572 

What I understand from that, is that 
1. That issue Affects GitLab CE/EE 8.8 and later.
2. It also should affect gitlab.com private repositories

I think Gitpitch should change the way it's accessing Gitlab files and use only api/v4

```
curl -sNH 'PRIVATE-TOKEN: <token>' 'http://git.example.com/api/v4/projects/PROJECT_ID/repository/files/PITCHME.md/raw?ref=master'
```

Br,
Markku

**Comment by gitpitch** [comment]
You are correct, the open source server is still using GitLab API v3. And the Docker image you are using - an image maintained by someone else - is automatically built against the open source repo.

The server on gitpitch.com has already been updated to use the GitLab v4 API. As has the official [GitPitch Enterprise](https://gitpitch.com/enterprise) Docker image.

I have not yet back-ported this update to the open source server. When time permits I'll do that. Hopefully sometime over the coming weeks. Feel free to bump this thread if you don't see any updates.

**Comment by gitpitch** [comment]
Quick update. Having spent some time looking into this I realized that the version of the GitLab API does not really matter here. *The open source server does not support* private repos.

While an update to the GitLab v4 API may permit fetching a `PITCHME.md` from a private repo associated with the master *token* specified in the server config, it would not support fetching any other presentation assets, such as images etc.

For private repository support you need either (1) a Pro subscription on https://gitpitch.com or (2) a license for [GitPitch Enterprise]( https://gitpitch.com/enterprise) to deploy on-premises.

For public repositories, the open source server should work perfectly without requiring any changes.
