### ISSUE TITLE
Include footer in pdf printout

### ISSUE THREAD

**Issue by flokno** [gitpitch/gitpitch#241]
It would be great to have the option to include the presentation footer in a pdf printout.

**Comment by meeas** [comment]
Seconded.  I provide the PDF exports to my students and I use the footer for my copyright notice.

**Comment by gitpitch** [comment]
Support for a new `print-footer` setting has been added to [GitPitch Desktop](https://gitpitch.com/docs/pro-features/desktop). When the setting is activated in the [PITCHME.yaml](https://gitpitch.com/docs/settings/pitchme/) for any slide deck, the slide footer will be rendered when printing to PDF and PPTX:

```
print-footer: true
```

By default, the `print-footer` setting is `false`. It is worth noting that when activated, the standard navigation-help message that typically appears in the footer on the first slide is replaced with the [footnote](https://gitpitch.com/docs/settings/footnote/) for the slide deck. This ensures a custom footnote (for example, a copyright notice) appears on every slide.

You will need to download the [latest Desktop image](https://gitpitch.com/docs/pro-features/desktop-faq) to try out this feature. The official docs have not yet been updated to reflect this new feature, coming soon. But the information provided here gives you what you need to test out this new feature. If you do test, feedback is appreciated.

**Comment by gitpitch** [comment]
The full set of `print` settings are now documented in a single [GitPitch Print Settings Guide](https://gitpitch.com/docs/settings/print).
