### ISSUE TITLE
Rendering remote can give different slides than rendering with desktop version

### ISSUE THREAD

**Issue by flokno** [gitpitch/gitpitch#243]
I sometimes get different results when rendering the slides online vs. rendering them locally with the Desktop app.

I include an example where I used the `snap` environment to locate a flowchart on the east part of slide with
```
@snap[east span-39]
@img[shadow](assets/flowcharts/flowchart.png)
@snapend
```
I expect this to produce
![screenshot_20190305_162001](https://user-images.githubusercontent.com/28858706/53815871-d1c1e180-3f62-11e9-82d7-7b94784a615e.png)

whereas online I get
![screenshot_20190305_161938](https://user-images.githubusercontent.com/28858706/53815870-d1c1e180-3f62-11e9-82bb-a05ed3e28114.png)

You find the slide deck [here](https://gitpitch.com/flokno/dpg-19?grs=gitlab#/15)

**Comment by gitpitch** [comment]
Florian, the quick workaround is to define `span-39` as a style in your `assets/css/PITCHME.css`, like this:

```
.span-39 { width: 39% !important }
```

I need to update the set of built-in styles used by the online server to include the latest and full set of `span-xx` classes that are already available in the Desktop. Currently only the 5, 10, 15...90, 95, 100 spans are available online. Not the full set of 1,2,3...95,96,97,98,99,100 spans that are found in the Desktop.

When I make that change I'll bump this thread. But for now, you need the workaround. Thanks for bringing this to my attention.

**Comment by gitpitch** [comment]
The gitpitch.com server has been updated with the full set of `span-xx` styles. This change should resolve the problem reported here. Depending on your browser you may need to refresh or clear your cache to see this change take effect for your presentation.

If you applied the *workaround* to your `PITCHME.css` can you please undo that change. Then test and let me know how it goes.

**Comment by flokno** [comment]
The fix works for me, no need for any workaround. Thank you very much!
