### ISSUE TITLE
Is it possible to stop page numbering at specific slide?

### ISSUE THREAD

**Issue by flokno** [gitpitch/gitpitch#244]
Context: I want to include an appendix with extra slides in my presentation, but don't want to include them in the page numbers. Is this possible?

**Comment by gitpitch** [comment]
What you are asking for is not possible.

However, if you take advantage of the [modular slideshow support](https://gitpitch.com/docs/git/branch-modular-slideshows/) that GitPitch offers you could maintain your *appendix with extra slides* as an *Appendix Deck*, separate-but-directly-alongside your main presentation. And then simply link to the *Appendix Deck* on the last slide of your main presentation.

This would solve the issue of slide numbers in your main deck. And it gives you a clean way to maintain supplemental slide materials in an appendix.

For example, if this is your main deck:

```
https://gitpitch.com/acmecorp/slides
```

Then the last slide on that deck could link to:

```
https://gitpitch.com/acmecorp/slides?p=appendix
```

That's the general idea. The doc I linked to above provides the necessary details.

**Comment by flokno** [comment]
Ok thanks, I'll take a look!

**Comment by flokno** [comment]
Thanks for bringing the modular markdown feature to my attention, seems cool.

However, when I use `---?include=...` it still shows the slide numbers, which somehow is to be expected. And linking to the appendix would mean I switch to it entirely and lose my other slides, I guess. What I could do is prepare two presentations: One without and one with appendix, and then switch to the latter at the end. Hmm. 

I mean it's not a big problem for me, but let's say, if it would be easy to include something like
https://github.com/hakimel/reveal.js#slide-number
to easily take out slides from the numbering, I'd be interested in using it :).

**Comment by gitpitch** [comment]
> However, when I use ---?include=... it still shows the slide numbers

Sure. I didn't intend for you to just use the `include` syntax. That would simply deliver a single deck out of multiple markdown sources - modular markdown. 

But if you split your content into distinct *content* and *appendix* markdown files then each file be referenced as a standalone presentation - modular slideshows. Each with it's own `PITCHME.yaml`, and custom CSS. And these individual files can also be aggregated. I describe that in more detail below.

#### Option 1
 
You can then add a link from the *content* deck to the *appendix* deck.

> And linking to the appendix would mean I switch to it entirely and lose my other slides, I guess. 

I'm not exactly sure what you mean here by `lose my other slides`. Your *appendix* deck could simply link back to the *content* deck. Perhaps the best way to do that would be to add a link back to the *content* deck from the [footnote](https://gitpitch.com/docs/settings/footnote/) of the *appendix* deck.

#### Option 2

> One without and one with appendix, and then switch to the latter at the end. Hmm.

Probably the cleanest way to adopt this approach would be to use the following file structure in your repo:

```
.
├── PITCHME.md
├── appendix
│   └── PITCHME.md
└── slides
    └── PITCHME.md
```

The content of the top-level `PITCHME.md` would simply include the *slides* and *appendix* content as follows:

```
---?include=slides/PITCHME.md

---?include=appendix/PITCHME.md
```

The `PITCHME.md` under the `slides` directory would contain just the presentation *content*. And the `PITCHME.md` under the `appendix` directory would contain just the appendix *content*.

Then you could easily switch between all 3 options with the following URLs.

For everything, slides and appendix:

```
https://gitpitch.com/user/repo
```

For the slides only:

```
https://gitpitch.com/user/repo?p=slides
```

For the appendix only:

```
https://gitpitch.com/user/repo?p=appendix
```

**Comment by flokno** [comment]
Yes that sounds reasonable. Thank you!
