### ISSUE TITLE
theme-override not working for private gitlab

### ISSUE THREAD

**Issue by kserin** [gitpitch/gitpitch#245]
I'm currently using gitpitch opensource with my own gitlab server:
```
git {
    repo {
        services = [
            {
                name        = "GitLab2"
                type        = "gitlab"
                site        = "http://********.prive"
                apibase     = "http://*********.prive/api/v4/"
                apitoken    = "**********"
                apitokenheader    = "PRIVATE-TOKEN"
                rawbase     = "http://********.prive/"
                branchdelim = "~"
                default     = "true"
            }
        ]
    }
  }
```

When I tried to use `theme-override : next/PITCHME.css` in my PITCHME.yaml, it seems that the css is not correctly loaded.
After inspecting network, it seems that the `PRIVATE-TOKEN` header is not set for the PITCHME.css request (it is correctly set for PITCHME.md request):
```
GET /*****/*****/raw/master/next/PITCHME.css HTTP/1.1
User-Agent: Java/1.8.0_181
Host: ********.prive
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive

[ ... ]

GET /*****/*****/raw/master/next/PITCHME.md?gp=90 HTTP/1.1
Cache-Control: no-cache
PRIVATE-TOKEN: ********
Host: *********.prive
Accept: */*
User-Agent: AHC/2.0
```

**Comment by gitpitch** [comment]
Hi Kévin, the GitPitch open-source server does not support private repos. So the token is not set on any assets fetches, including `PITCHME.css`. The token on the open-source server was only ever used to avoid API call limits when the open-source server was being used live on gitpitch.com.

For GitPitch private repository support you need either (1) a Pro subscription on [gitpitch.com](https://gitpitch.com/pricing) or (2) a license for [GitPitch Enterprise]( https://gitpitch.com/enterprise) that supports public and private repos within self-hosted GitHub, GitLab, and Bitbucket servers.

**Comment by kserin** [comment]
Oh ! So it's not a bug and it's not necessary that I do a pull request to fix that ?

**Comment by gitpitch** [comment]
Not a bug! No PR. I offer the Pro subscription service on gitpitch.com and the Enterprise server to deliver private repo support. The open-source server is public repo only.
