### ISSUE TITLE
Add speaker-mode-hidden property

### ISSUE THREAD

**Issue by wand3r** [gitpitch/gitpitch#246]
Similar to [pro-menus-hidden](https://gitpitch.com/docs/pro-features/bonus/#pro-only-slideshow-menu-control) but for speaker/presenter mode.

From my perspective, after I perform a presentation, I want to publish it for my audience. But I don't want to share my speaker notes because these are more unpolished ad-hoc thoughts.

Currently, there are two ways to handle this:
* create two branches, one witch speak notes and one without
* use [modular markdown](https://gitpitch.com/docs/git/branch-shared-markdown/) and have two separate markdown files with and without speak notes

In both cases, we need to duplicate our slides and remove speak notes in one branch/module. Additionally, if we want to make further changes, we must make them in both places, so maintenance becomes tiresome.

With `speaker-mode-hidden` I could just set it to `true` on my `master` branch and publish it. From my experience, I always use a desktop version to present my decks in case of problems with the internet, so I can just set it to `false` locally. Even if someone wants to use an online version for presenting, he can still set it to `true` on another branch/module without whole duplication.

In practice, `speaker-mode-hidden` property could just block opening speaker window for all users.

**Comment by gitpitch** [comment]
@wand3r I have just added support for a new [speaker-mode](https://gitpitch.com/docs/speaker-features/window) setting that can be set for any slide deck. This setting allows presentation authors to enable or disable speaker-notes and speaker-window features for any deck. To disable these features, simply disable the **speaker-mode** property in your *PITCHME.yaml*:

```yaml

speaker-mode : false

```

The [Speaker Guide](https://gitpitch.com/docs/speaker-features/window) has been updated accordingly. The addition of this setting should provide a solution for each of the use-cases mentioned above when publishing and sharing decks online.

If you are using GitPitch Desktop to test this feature make sure to [download the latest image](https://gitpitch.com/docs/pro-features/desktop-faq). As this is a new feature, testing and feedback appreciated. Cheers, David.
