### ISSUE TITLE
Add Option for Code Line Wrapping

### ISSUE THREAD

**Issue by michaeltlombardi** [gitpitch/gitpitch#247]
Right now long lines of code display, but in a scrolling window.

Editing code to match isn't a huge deal, but it does mean I've had to modify code/source files for my presentation.

Having the ability to cause those lines to wrap instead via a setting in `PITCHME.yaml` would be _very_ useful.

**Comment by gitpitch** [comment]
Hi Michael, you should be able to do what you need with a small snippet of [custom css](https://gitpitch.com/docs/themes/custom).

Try adding this snippet to modify the current default behavior for your sample deck:

```
.hljs { white-space: pre-wrap; }
```

You will need to test and verify but if I understand correctly what you are after then I believe it should work. You should also test this change with [code presenting fragments](https://gitpitch.com/docs/code-features/presenting) just to be sure there are no unwanted surprises. I'll be interested to hear how you get on.

**Comment by michaeltlombardi** [comment]
Yup, this worked!
