### ISSUE TITLE
 Home page: miss link to pricing

### ISSUE THREAD

**Issue by muescha** [gitpitch/gitpitch#249]
Where:
- homepage gitpitch.com
- mobile view

What I see:
- many Informations but no pricing link

What I expect:
- at least in the footer a link to https://gitpitch.com/pricing

**Comment by gitpitch** [comment]
Thanks for pointing this out. Link to pricing page now added.

**Comment by muescha** [comment]
Just my 2cents. 

The free tier you should also add to the pricing page in the same layout as the other pricing options. If I just overview the options the free community pricing (in the first paragraph) was not visible for me.
