### ISSUE TITLE
Slides preview

### ISSUE THREAD

**Issue by ikalnytskyi** [gitpitch/gitpitch#25]
(this is a feature request)

It'd be nice to have some sort of preview before committing `GITPITCH.md`. So far I have two thoughts:

* Online text editor where one can copy-paster `GITPITCH.md` content.
* Render `GITPITCH.md` from repo's pull request, where one can change its content with `git push --force` in order to have a good Git history in the end.

**Comment by gitpitch** [comment]
Hi @ikalnytskyi 

This is definitely a nice idea and someday I would like to see a dedicated tool that would give you quick and easy previews of a GitPitch presentation under development.

There is a simple trick I use myself when developing my own presentations that you might like to try:

1. Create a skeleton one-page presentation and git-push it.
2. Open your skeleton one-page presentation on gitpitch.com.
3. Click `Offline` to download the self-contained presentation bundle.
4. View and verify your presentation [per Wiki instructions](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Offline)

Once you have verified that you can view your presentation offline then you can use your offline bundle as an offline presentation development tool.

Within the offline bundle you will need to develop your presentation Markdown content in the following file:

```
assets/md/PITCHME.md 
```

When you update the content in this `PITCHME.md` file you can then reload your offline presentation in your browser and observe/preview your changes. Note, you may need to clear your browser cache before each reload depending on how your local HTTP Server works.

If you do try this out let me know how you get on.

**Comment by zariye** [comment]
@gitpitch thanks for this helpful instructions! =) do you also have an idea how it could work with including pictures (in case i do not want to use a feature branch)

**Comment by gitpitch** [comment]
Hi @zariye it's very simple to work locally with pictures/images etc. As noted above, when you work locally using the `offline` bundle as your development and test environment you use the following file to develop the Markdown content for your presentation.

```
assets/md/PITCHME.md 
```

If you want to use pictures within your presentation then simply add an `assets` directory alongside the `PITCHME.md` file and place your image files in that directory. For example:

```
assets/md/PITCHME.md 
assets/md/assets/pic.png
```

You can then use a relative URL to access that image in your Markdown:

```
![PIC](assets/pic.png)
```

The final step you need to do is to make sure than you git push this `assets` directory when you are also pushing your `PITCHME.md` to your git repo.

If any of this is unclear please let me know and I'm sure we can work it out.

**Comment by zariye** [comment]
awesome

**Comment by gitpitch** [comment]
Offline bundle approach detailed above provides preview solution per this feature request. Closing issue as resolved.

**Comment by taboot** [comment]
B0bj@hotmail.com
