### ISSUE TITLE
code widget does not render underscores in front and after __init__ method in Python

### ISSUE THREAD

**Issue by meleantonio** [gitpitch/gitpitch#250]
I am trying to create a slide with a class example with 
```
@snap[east span-46 fragment]
@code[python code-slow-reveal code-wrap code-line-numbers zoom-08](code/classexample.py)
```
and my ```classexample.py``` is 
```python
class classexample:

    def __init__(self, v):
        self.Value = v
    
    def roundOff(self):
        return round(self.Value)
    
    def multiplyBy(self, n):
        return self.Value * n

 ```
however Gitpitch is not rendering the __ around the constructor method:
![Screenshot 2019-05-28 at 16 55 45](https://user-images.githubusercontent.com/8898165/58492797-8d14a380-8169-11e9-8880-8d803e801843.png)

I'm on a MacBook Pro with MacOS Mojave 10.14.5, using Chrome, and Gitpitch Pro.

**Comment by gitpitch** [comment]
Hi Antonio, thanks for reporting this issue. I will investigate. And update this thread once I find a solution. Cheers, David.

**Comment by gitpitch** [comment]
Having quickly tried to reproduce the problem reported I found the following. When the [@code widget](https://gitpitch.com/docs/markdown-features/pro-widgets) is used at the top-level of the slide the `__` around the constructor method is rendered as expected:

![code-widget-full](https://user-images.githubusercontent.com/19169584/58519594-8f651500-81de-11e9-852a-1338cd0856be.jpg)


But when the widget is used within a [snap region](https://gitpitch.com/docs/layout-features/snap-layouts) then the reported problem can be reproduced:

![code-widget-snap](https://user-images.githubusercontent.com/19169584/58519615-a4da3f00-81de-11e9-8b5a-3f6036db7695.jpg)

This quick update is just to let you know that if you can temporarily redesign your slide - with your code sample at the top-level of your slide (not snapped) - then you have a temporary workaround for this issue. I will of course continue to investigate and find a more permanent fix.

**Comment by meleantonio** [comment]
Thanks David, will try this, and wait for a fix.

**Comment by gitpitch** [comment]
A patch has gone live on [gitpitch.com](https://gitpitch.com) and in the latest version of [GitPitch Desktop](https://gitpitch.com/docs/pro-features/desktop-faq). This patch should resolve the encoding problem for the [@code widget](https://gitpitch.com/docs/markdown-features/pro-widgets) reported on this issue thread. @meleantonio if you have a chance to test this out I would appreciate it if you could let me know if the patch is working for you there. Thanks, David.

**Comment by meleantonio** [comment]
Works like a charm! Thanks David @gitpitch

**Comment by gitpitch** [comment]
Great, thanks for reporting, testing, and your feedback @meleantonio. Closing this issue as resolved.
