### ISSUE TITLE
gitpitch not rendering ```*``` in code widget

### ISSUE THREAD

**Issue by meleantonio** [gitpitch/gitpitch#251]
This is similar to issue #250 

I am trying to compare two pieces of code (one in Python, one in Matlab). In both, gitpich is not rendering some of the ```*``` in an expression. 

For example, here is the Python code:

```python
import numpy as np
import matplotlib.pyplot as plt

fs = [1, 2, 4]
all_time = np.linspace(0, 2, 200)
t = all_time[:100]

for f in fs:
    y = np.sin(2 * np.pi * f * t)
    plt.plot(t, y, label='{} Hz'.format(f))

plt.legend()
plt.savefig('basics_python.pdf')
```

The Gitpitch code is:
```gitpitch
@snap[east span-46 fragment]
@code[python code-slow-reveal code-wrap code-line-numbers code-wrap zoom-08](code/simpleexample.py)
@snapend
```

Gitpitch renders only the last ```*``` in the expression ```y = np.sin(2 * np.pi * f * t)``` inside the for loop. The same happens with Matlab code, so I am guessing this is a more general problem than just rendering Python code. 

I'm on a MacBook Pro with MacOS Mojave 10.14.5, using Gitpitch Pro.

**Comment by gitpitch** [comment]
Hi Antonio, thanks for reporting this issue. I am in the middle of some major GitPitch related work right now so it will be a least a few days before I can look into implementing and then rolling out a patch for this encoding issue. In the meantime you might want to try the following simple workaround. Tweak your code snippet as follows:

```
for f in fs:
    y = np.sin(2 \* np.pi \* f \* t)
    plt.plot(t, y, label='{} Hz'.format(f))
```

This tweak simply adds a `\` or backslash before each of the `*` symbols that appear in the `for` loop in your sample code. Hopefully this will give you what you need right now. Pending a more permanent fix of course as soon as I can get to it.

**Comment by meleantonio** [comment]
@gitpitch thanks, it works.

**Comment by gitpitch** [comment]
A patch is now live on [gitpitch.com](https://gitpitch.com) and within [GitPitch Desktop](https://gitpitch.com/docs/pro-features/desktop) that should address the issue described on this thread. You will need to pull the latest Desktop image to test locally. @meleantonio if you try again with your original Python source file I would be interested to hear how that testing goes.

**Comment by meleantonio** [comment]
@gitpitch  David it works, thanks!
