### ISSUE TITLE
Pro Code Widget presenting block not highlighting correctly

### ISSUE THREAD

**Issue by xtaje** [gitpitch/gitpitch#253]
The pro code annotation and presenting seems to have a problem parsing or highlighting this code block:

https://github.com/xtaje/in-60-seconds/blame/master/PITCHME.md#L35
https://gitpitch.com/xtaje/in-60-seconds#/4

**Comment by gitpitch** [comment]
Hi Ed, you need a blank line between the `@code` widget declaration and the live code `annotations`, for example:

````
@code[py](src/test.py)

@[1-3](init some vars)
@[1,4-9](check the words for blacklisted symbols)
````

Add the blank line as shown above and your code should render cleanly on your sample slide.

An additional quick tip, I recommend [snapping](https://gitpitch.com/docs/layout-features/snap-layouts) code annotations into the southern grid position of the slide, as follows:

```
@code[py](src/test.py)

@snap[south span-100]
@[1-3](init some vars)
@[1,4-9](check the words for blacklisted symbols)
@snapend

```

It delivers a better use of space on the slide which is visually more appealing for your audience.

**Comment by xtaje** [comment]
Thanks!

It looks like there is also a small discrepancy in the way the annotations work between the different kinds of code delimiters.

For the gist based [delimiter](https://github.com/xtaje/in-60-seconds/blame/master/PITCHME.md#L30), there is no newline between the delimiter and code annotations, but it renders correctly.  The docs show that there is supposed to be a newline.

**Comment by gitpitch** [comment]
Thanks for this feedback. I always recommend following the documented syntax. That syntax is guaranteed to work today. And tomorrow. Any undocumented syntax such as the example you found may well work today, but it may or may not work in the future.
