### ISSUE TITLE
Feature request: loading custom fonts

### ISSUE THREAD

**Issue by TimVanMourik** [gitpitch/gitpitch#256]
I've got a custom font in an OTF file that I would really like to use in my `gitpitch` presentation. Normally in a CSS file I would load it like this:

```
@font-face {
  font-family: 'My-Custom-Font';
  src: url('/some/local/path/to/fonts/My-Custom-Font.otf?raw=true');
  font-weight: bold;
}
```
or
```
@font-face {
  font-family: 'My-Custom-Font';  
  src: url('https://some/url/to/fonts/My-Custom-Font.otf?raw=true');
  font-weight: bold;
}
```
for a local file and a file from a url respectively.

Now unfortunately neither of these option is currently possible. For the local option the reason is probably that the gitpitch bundle that is compiled does not look for fonts (but I might be wrong, my under-the-hood-understanding is limited) and the remote option the reason is (1) a cross-origin error and (2) a reliance on remote resources that is undesirable for local presentations. As the latter reason is rather fundamental, the way forward is probably to scan for local files and compile them with the rest.

**Comment by gitpitch** [comment]
First class support for custom fonts within GitPitch slide decks is coming soon. You can check out the [GitPitch Custom Fonts announcement](https://twitter.com/gitpitch/status/1259878926710644736) which includes a link to a sample slide deck. I'll share more details here over the coming days. Cheers, David.

**Comment by gitpitch** [comment]
Support for custom fonts is now live. Full details in the [Custom Fonts Guide](https://gitpitch.com/docs/themes/custom-fonts).

**Comment by TimVanMourik** [comment]
Very nice, looks great :D
