### ISSUE TITLE
Including part of file contents as code based on tags ala asciidoctor

### ISSUE THREAD

**Issue by hallvard** [gitpitch/gitpitch#257]
asciidoctor allows including parts of file contents into code blocks using tags, see https://asciidoctor.org/docs/user-manual/#include-partial

This could be a nice solution for GitPitch, to make the extraction and presentation more flexible and less sensitive to exact file contents, both when including using the ---?code syntax, e.g. with a tag=xyz parameter, and when selecting parts with @[from-to], e.g. @[tag].

**Comment by gitpitch** [comment]
Hi Hallvard, thanks for getting in touch. And thanks for introducing me to asciidoctor tagged includes. My blink reaction is that I really like this idea. And I think it would make a very nice addition to GitPitch. I will need to dig deeper to evaluate the time/effort to deliver this as a feature. For right now, I will leave this RFE open for others to comment and/or upvote. Thanks again, David.

**Comment by hallvard** [comment]
I've so far implemented a region parameter to the code inclusion feature that support both the existing line, start-end syntax and a tag, e.g.
?code=...&region=2
?code=...&region=2-4
?code=...&region=tag
The first will include line 2, the second lines 2-4 (inclusive) and the last all lines between pairs of lines containing the tag.

**Comment by gitpitch** [comment]
Great. I'll be interesting to look this over when you're ready so I can see how well the approach translates into the production source base for it to make its way into the product.

**Comment by gitpitch** [comment]
A final update for anyone browsing this thread. GitPitch now supports range and tag filters for all source code files and GitHub GIST. For details, see the [Code Filters Guide](https://gitpitch.com/docs/code-features/pro-code-filters).
