### ISSUE TITLE
List markup not working as expected within @snap

### ISSUE THREAD

**Issue by hallvard** [gitpitch/gitpitch#258]
The following markup works on its own, i.e. gives a nice bulleted list:

```
### Test pitch

* one
* to
* three

- four
- five
- six
```

However, if it is wrapped in @snap and @endsnap the list items aren't understood as such, they are just displayed as normal text with * interpreted as italic, see image below

<img width="874" alt="Screenshot 2019-08-08 at 00 31 23" src="https://user-images.githubusercontent.com/400291/62662319-f6880e00-b973-11e9-9704-c927b74df2eb.png">

**Comment by gitpitch** [comment]
Hi Hallvard, thanks for reporting this issue. It is a known limitation within snap tags. With the exception of regular markdown heading syntax, as a general rule you should use markdown widgets within snap tags. So in the case of lists within snap tags, you should use something like this:

```
@ul
* one
* to
* three
@ulend
```

And if you do not want your list to be presented in fragments (steps) use this:

```
@ul[](false)
* one
* to
* three
@ulend
```

You can learn more about the markdown widgets for lists in the docs [here](https://gitpitch.com/docs/markdown-features/list-fragments/).

**Comment by hallvard** [comment]
But this is specific for lists, other kinds of markup will face similar issues, with no markdown widget as solution.

When reading about the snap layout mechanism, I didn't notice this limitation, although I wondered why these markup widgets were used instead of normal markup. Where is it explicitly stated that ordinary markup isn't supported within snap regions? For me it's more of a show-stopper than limitation.

I'm curious, what is the technical reason for this limitation? Is it because of limitations to the underlying mechanism used by snap layout? Is that something that you expect can be solved?

**Comment by gitpitch** [comment]
> But this is specific for lists, other kinds of markup will face similar issues, with no markdown widget as solution.

Sure. I was providing you with a solution to the problem you reported. While also drawing your attention to the more general issue re. content limitations within snapped regions.

There was a guide that used to described these limitations but it is out of date. I need to update it and publish it again as a chapter within the snap layouts guide.

>  Is that something that you expect can be solved?

It is something I am working on. For example, just today I added support for markdown fenced code blocks within snapped regions. You'll can pull the latest version of the desktop to try this out.

**Comment by hallvard** [comment]
I'm currently evaluating GitPitch by translating a set of slides I have for a university course, that's why I'm more concerned about the general power than this particular list. GitPitch is promising, and I'm willing to invest some time on reporting and fixing issues if I know it's worth it. E.g. I mostly have a fix for the recently reported #257.

Concerning markdown fenced code, when you say "pull", do you mean the docker image, not the git code repo? What is the relation between the code repo, the mentioned work on markdown fenced code and the docker image? BTW, if you prefer, we can move this thread to somewhere else.

**Comment by gitpitch** [comment]
I understand. And I appreciate your feedback. And happy to respond as best I can.

By "pull" I mean pull the latest desktop docker image.

> What is the relation between the code repo, the mentioned work on markdown fenced code and the docker image?

No relationship whatsoever. The source base for the desktop and the server diverged from the code in this public repo a long time ago. All production code is maintained in private repos. This public repo is where GitPitch began as an open source project. I still use this repo so I can discuss new issues and RFEs with my users.

**Comment by hallvard** [comment]
OK, so it's not really an open source project with added value in a private repo. Do you then expect others to fix issues and provide PRs? How can this work when that code, including the code I wrote to fix the issue I reported, will be based on code in an obsolete repo!

**Comment by hallvard** [comment]
BTW, how it markdown fenced code used, in case I try it out?

**Comment by gitpitch** [comment]
> OK, so it's not really an open source project with added value in a private repo. 

GitPitch began as an open source project -  delivering a markdown presentation server. And this repo still maintains that open source server. You are very welcome to use it. Many people do.

I also develop and maintain a closed source project. Which offers extensive free and paid features beyond the capabilities of the open source project. This project is made available as a hosted service on gitpitch.com. Again, you are very welcome to use that if you wish.

> Do you then expect others to fix issues and provide PRs? 

I do not. But if you would like to contribute a PR to the open source server please go ahead. But note, whether that PR also makes it into the closed source project is not a given. But it certainly helps.

> BTW, how is markdown fenced code used, in case I try it out?

Fenced code blocks are part of the markdown spec. Supported using the three back-ticks syntax. From today, this same standard markdown syntax is now supported inside `@snap...@snapend` tags.

**Comment by hallvard** [comment]
Ok, I understand, fair enough. It is a bit different than what I consider the "ideal" model, where the closed parts are architecturally built on top of the open core, and all, including the ones getting paid, contribute to the core, and the one(s) getting paid additionally add value to the closed parts. That makes it easier to see the relationship (between open and closed parts) and contribute to the core, knowing it will benefit all. I know it's a bit more challenging, but it provides the most benefit.

I think the open source site would benefit from making this clearer. Currently, it promotes the gitpitch.com site and service, a lot of which is (as you say) not directly related to the repo. Only the last paragraph makes this clear. IMO, the open source site should present the capabilities of the code in that repo, not the closed code version.

Concerning "markdown fenced code", I read it as "fenced markdown code", i.e. a way to embed general markdown in @snap regions. Anyway, it sounds useful!

**Comment by gitpitch** [comment]
UPDATE: FYI @hallvard and anyone else reading this thread at a later date.

I have just released a brand-new Snap Layouts Markdown Rendering Engine that is now active on [gitpitch.com](https://gitpitch.com) and in all versions of [GitPitch Desktop](https://gitpitch.com/docs/work-offline/desktop). Pull latest desktop images from Docker Hub.

The new rendering engine supports 100% markdown syntax within GitPitch [snap-layouts tags](https://gitpitch.com/docs/layout-features/snap-layouts).This means you can now wrap any markdown (without exceptions) within snap-layouts tags and see it rendered as expected.

All [GitPitch Widgets](https://gitpitch.com/docs/markdown-features/widgets) and [GitPitch Pro Widgets](https://gitpitch.com/docs/markdown-features/pro-widgets) continue to render inside and outside of snap-layouts tags as before.

**Comment by hallvard** [comment]
Nice!
