### ISSUE TITLE
Presentation 404: PITCHME.md not found in repo on GitHub.

### ISSUE THREAD

**Issue by jensonzhao** [gitpitch/gitpitch#259]
Hi there,

My first presentation doesn't work and I don't know why. Can you help?
https://gitpitch.com/team-flash/tdd-fizzbuzz

Best,
Yang

**Comment by gitpitch** [comment]
Hi Yang, thanks for reporting this issue. There was a temporary glitch that has since been fixed. You should be able to access your deck again now. But let me know if not. Cheers, David.

**Comment by jensonzhao** [comment]
wow that's fast! thank you. :-)

**Comment by gitpitch** [comment]
You're very welcome Yang. Btw, that same glitch crept into [GitPitch Desktop](https://gitpitch.com/docs/work-offline/desktop). So if you're using that tool, please make sure to pull the latest image. Details on downloading the latest Desktop image are also found in the linked docs.
