### ISSUE TITLE
Question relating to Private Repos

### ISSUE THREAD

**Issue by mwelch2** [gitpitch/gitpitch#26]
Is it possible to use gitpitch on a private repository?

**Comment by gitpitch** [comment]
Hi @mwelch2 private repos are not currently supported. Only `PITCHME` in public repos can be rendered as slideshow presentations.

**Comment by vogxn** [comment]
given github oauth and integrations, is this something that is possible to include in your roadmap? i love gitpitch and my org is entirely on github as are many others. this would be a super useful feature for us.

**Comment by gitpitch** [comment]
Hi @vogxn thanks for getting in touch. It so happens I am already working on GitPitch 3.0. That release will introduce a number of new features, including subscription-only features that will support private repos.

I do not yet have a release date for you but I will update this thread with further news as it becomes available. You can reach out to me anytime by e-mail if you have any questions or would like to discuss 3.0. I'd be very interested to learn from you how your org is using GitPitch today and how it might use private-repos it in the future. Cheers, David.

**Comment by vogxn** [comment]
Thanks for your response, David. I just happened to start using within my org to do internal talks and presentations. It's just me right now but the first talk has had a good impression on people. I'm hoping that the rest of the team will pick it up for their presentations.

**Comment by gitpitch** [comment]
@vogxn I'm very glad to hear your first presentation using GitPitch was well received within your org. Hopefully the first of many. If I can be of any help or you have further questions please feel free to reach my here or directly by e-mail.

**Comment by gitpitch** [comment]
A quick update on this thread regarding private repository support. I've just announced GitPitch Pro is coming soon. A subscription service that unlocks Git private repos to deliver public, private, and password-protected presentations and much, much, more. Read the following GitPitch [blog post for details](https://medium.com/@gitpitch/gitpitch-pro-coming-soon-bda8c71ca9ea).

**Comment by gitpitch** [comment]
GitPitch support for private Git repos is now available. Full access beta program has begun. Beta details [here](https://medium.com/@gitpitch/your-invitation-to-join-gitpitch-pro-beta-a613008c9c75). Additional details on the new [website](https://gitpitch.com). @mwelch2 @vogxn

**Comment by gabrieljoelc** [comment]
Should this be closed now?

**Comment by gitpitch** [comment]
Thanks Gabriel, you're right this issue can be closed out. The official documentation for private repo support can be [found here](https://gitpitch.com/docs/pro-features/security).
