### ISSUE TITLE
Too many permissions

### ISSUE THREAD

**Issue by andrecarlucci** [gitpitch/gitpitch#260]
Hey guys,

Any chance of logging in with Github, but NOT allowing read and write to all public and private repository data?

**Comment by gitpitch** [comment]
Hi Andre, currently GitHub does not support *read-only* Oauth scope for repositories. So GitPitch can not request it. You will need to grant the current set of requested permissions to login. Following login, GitPitch will only ever use your token to perform *read-only* operations on your repo data. It only ever reads data directly required by your presentations. And it will only ever access that data when your presentation is opened on [gitpitch.com](https://gitpitch.com).
