### ISSUE TITLE
Markdown Tables don't render in snap

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#261]
I'm trying to use a Markdown (MD) table. If I do nothing it's too large for the page:

```
---

Folder|Re-Runnable|Description
--- | ---
`/build`|@fa[ban]|Scripts to build release
`/data`|@fa[sync]|Re-runnable data scripts
`/packages`|@fa[sync]|Ex: `pkg_emp.pks` and `pkg_emp.pkb`
@css[text-red text-bold](`/release`)|@fa[times-circle]|_More Later_
@css[text-grey](`/scripts`)|@fa[ban text-grey]|@css[text-grey](Common scripts / helpers for developers)
`/synonyms`|@fa[sync]|Synonyms
`/views`|@fa[sync]|Views
`/www`|@fa[ban]|Web files (for APEX)

---
```

![Snip20190901_15](https://user-images.githubusercontent.com/2925726/64082637-56ea4100-cccf-11e9-9f96-3336b7058cce.png)

If I try to wrap the image in a `snap` to set the font size to a smaller font it does not render properly:

```
---

@snap[midpoint text-07]

Folder|Re-Runnable|Description
--- | ---
`/build`|@fa[ban]|Scripts to build release
`/data`|@fa[sync]|Re-runnable data scripts
`/packages`|@fa[sync]|Ex: `pkg_emp.pks` and `pkg_emp.pkb`
@css[text-red text-bold](`/release`)|@fa[times-circle]|_More Later_
@css[text-grey](`/scripts`)|@fa[ban text-grey]|@css[text-grey](Common scripts / helpers for developers)
`/synonyms`|@fa[sync]|Synonyms
`/views`|@fa[sync]|Views
`/www`|@fa[ban]|Web files (for APEX)

@snapend

---
```

Looks like:

![Snip20190901_18](https://user-images.githubusercontent.com/2925726/64082661-a2045400-cccf-11e9-8952-ea57ef47f8a3.png)

From the second screenshot, the MD table is not rendered properly

**Comment by gitpitch** [comment]
@martindsouza thanks for reporting this issue. Looks like a bug in the new markdown rendering engine used for rendering content within *snap-layouts*. I will update this thread once I have had a chance to investigate.

**Comment by gitpitch** [comment]
Btw, if you need a temporary workaround you could use regular HTML syntax to create your table. Just make sure that you do not indent your HTML tags as doing so may cause your table to be treated as raw code not a table.

For example, you could do something like this:

```markdown

@snap[west span-50 text-04]

<table>
<tr>
<th>Company</th>    
<th>Contact</th>    
<th>Country</th>                 
</tr>                            
<tr>                             
<td>Alfreds Futterkiste</td>      
<td>Maria Anders</td>    
<td>Germany</td>    
</tr>  
<tr>    
<td>Centro comercial Moctezuma</td>    
<td>Francisco Chang</td>    
<td>Mexico</td>    
</tr>         
<tr>              
<td>Ernst Handel</td>    
<td>Roland Mendel</td>       
<td>Austria</td>                                                     
</tr>   
<tr>  
</table>

@snapend

```

**Comment by gitpitch** [comment]
@martindsouza a new patch to fix the snap-rendering of markdown tables has just gone live on [gitpitch.com](https://gitpitch.com). This same patch has also been integrated into GitPitch Desktop. Pull the [latest version](https://gitpitch.com/docs/pro-features/desktop-faq) of the desktop from Docker Hub.

When your time permits can you please test and verify the fix. Thanks.

**Comment by martindsouza** [comment]
@gitpitch Still getting the same issue. The image I'm using is `924c8ba14a51`

**Comment by gitpitch** [comment]
@martindsouza it looks like the public build did not complete earlier. Apologies, you were testing an old image. The new image is now available. Please docker pull and try again.

**Comment by martindsouza** [comment]
@gitpitch still the same issue. Image is `725ba03a7bed`

**Comment by gitpitch** [comment]
@martindsouza I believe the issue is with your current table syntax. The snap-layouts markdown renderer **requires** you to use a pipes (`|`) when opening and closing a row in any table. Add those pipes to your markdown and your table should render as expected.

**Comment by martindsouza** [comment]
Works now. For others this is my new table structure:


```
---

@snap[midpoint text-06 span-100]

| Folder | Re-Runnable | Description | 
| --- | --- | --- |
| `/build` | @fa[ban] | Scripts to build release |
| `/data` |@fa[sync] | Re-runnable data scripts |
| `/packages` | @fa[sync] |Ex: `pkg_emp.pks` and `pkg_emp.pkb` |
| @css[text-red text-bold](`/release`) | @fa[times-circle] | _More Later_ |
| @css[text-grey](`/scripts`) | @fa[ban text-grey] | @css[text-grey](Common scripts  | / helpers for developers)  | 
| `/synonyms` | @fa[sync] | Synonyms |
| `/views` | @fa[sync] | Views | 
| `/www` | @fa[ban] | Web files (for APEX) |

@snapend

---

Results in:

![image](https://user-images.githubusercontent.com/2925726/64256162-1a416400-cee0-11e9-8bd2-834495a31dea.png)

```
