### ISSUE TITLE
Font Awesome non-solid Icons

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#265]
It seems that we can only add solid Font Awesome (FA) icons. It would be good to be able to add non-solid icons. 

Example is [`building`](https://fontawesome.com/icons?d=gallery&q=building&m=free):

![image](https://user-images.githubusercontent.com/2925726/64475247-7e149880-d13d-11e9-83ef-e6bdc51e770f.png)

Image on the left is `solid` whereas the one on the right is not solid. Current [help](https://gitpitch.com/docs/rich-media-features/font-awesome/) around FA seems to only suggest support for solid icons.

**Comment by gitpitch** [comment]
> It would be good to be able to add non-solid icons.

@martindsouza GitPitch had support for **1500+ solid** and  **400+ brand** icons. And now it also has support for **100+ regular** icons. To learn how to use these new icons, see the updated [Font Awesome 5 Icons Guide](https://gitpitch.com/docs/rich-media-features/font-awesome) in the docs.

This enhanced Font Awesome support is live on [gitpitch.com](https://gitpitch.com). And offline, just pull the [latest GitPitch Desktop image](https://gitpitch.com/docs/pro-features/desktop-faq).

**Comment by martindsouza** [comment]
Note: To use the new "regular" icons the syntax is: `@far[regular-icon-name]` ex: `@far[building]`
