### ISSUE TITLE
How to give access to private repos

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#266]
I have a private repo on Github and want to publish my slides online. I have read [https://gitpitch.com/docs/pro-features/security/](the docs) about private repositories but don't see how I give Gitpitch access to read the repo.

_Note: I have added `published : true` in the `PITCHME.yaml` but I don't think that elevates the need fro Gitpitch to have access to my repo._

**Comment by gitpitch** [comment]
Hi Martin,

GitPitch has access to your private repos by virtue of the fact that you have activated a PRO plan on your `github/martindsouza` account. So private repo access has already been granted to GitPitch.

If you now add a `PITCHME.md` to any private repo and then activate `published`, `stealth`, or `confidential` mode  in the `PITCHME.yaml` for your deck - per the [GitPitch Security Guide](https://gitpitch.com/docs/pro-features/security) - then GitPitch can serve that slide deck to your audience. There is nothing else you need to do. Just following the instructions in the security guide.

**Comment by martindsouza** [comment]
@gitpitch I think it just took a few minutes for things to load. Looks like it's working now. 

Thanks for the clarification of how you have access to my private repo.  Maybe good to include such a note int he Pro Security docs
