### ISSUE TITLE
Ability to include notes in exports

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#268]
Is it possible to have an option when generating a PDF or PPTX to also include a Notes in the slides? Just tested and both PDF and PPTX don't include the notes.

**Comment by gitpitch** [comment]
@martindsouza it is not possible to include notes in exports. Probably the simplest way today to create a PDF or PPTX that includes your notes is to:

1. Make a copy or your `PITCHME.md` in your repo and then
2. In that copy do a global find-and-replace of the `Note:` delimiter with a regular `---` slide delimiter.
3. That will create one extra slide per slide-specific note in the deck
4. Then generate PDF or PPTX for the modified deck.

It's worth noting, if you have fragment-specific notes you would need to manually duplicate those notes into an appropriate notes slide for printing.

**Comment by martindsouza** [comment]
I think the replace `note:` with `---` is a reasonable change. Is it possible to include that directly in the PDF build process as an option?

As for the fragmented notes would it be hard to find all `@note[*]` and replace append to bottom of "Notes" slide?

**Comment by gitpitch** [comment]
>  Is it possible to include that directly in the PDF build process as an option?

Possible but unlikely. But I will leave the thread open to see what level of interest this feature request receives over the coming months.

**Comment by meeas** [comment]
As an OSS developer and a GITPITCH Pro subscriber, I would be very interested in this feature in PDF exports.  In fact I would suggest that if the added, the resulting PDF, that the exporter inject a blank frameless, logo-less page after each slide wether it contains notes or not, that way when you print the PDF with 2 pages per page, it keeps the slide and notes properly aligned.  I'm considering using this with my training courses, and I currently provide books to my students with the slides on the top of each page and notes on the bottom of each page.

I don't think this feature would be useful for PPTX exports unless you could insert the notes into the proper location in the PPTX.  Out of curiosity, you mentioned this wasn't possible.  Is it a limitation of the current PPTX export library?

**Comment by gitpitch** [comment]
@martindsouza @meeas I have just pushed support for printing slide-specific notes within PDF and PPTX documents into the Desktop. You will need to download the [latest Desktop image](https://gitpitch.com/docs/pro-features/desktop-faq) to try out this feature.

To see notes in your generated documents simply activate the `print-notes` setting in the `PITCHME.yaml` for your deck, as follows:

```yaml
print-notes : true
```

By default, the `print-notes` setting is `false`. You can use this new setting in conjunction with the existing [print-fragments](https://gitpitch.com/docs/settings/print-fragments/). For example:

```yaml
print-notes : true
print-fragments : false
```

By default, `print-fragments` is true. Be aware, fragment-specific notes are not exported. And if a slide has no note, then nothing extra is printed for that slide. I am not planning to generate blank slides for slides-without-notes. _**This page is intentionally left blank**_ died with IBM back in the 80s. And I'm not planning on resurrecting the dead :) But if you want to print two-pages-in-one you can add a "No note for this slide." note on any slide that does not contain a real note.

The official docs have not yet been updated to reflect this new feature. I'll get to that in due course.  But given you both expressed interest in this feature I'm hoping you can test it and provide feedback. Thanks, David.

**Comment by gitpitch** [comment]
The GitPitch docs have been updated with a new [Print Notes Setting Guide](https://gitpitch.com/docs/settings/print-notes/).

**Comment by gitpitch** [comment]
The full set of `print` settings are now documented in a single [GitPitch Print Settings Guide](https://gitpitch.com/docs/settings/print).
