### ISSUE TITLE
Include GitPitch documents with docker image

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#269]
I was offline and was working on my GitPitch slides and wasn't able to access to the documentation. Would be useful d it be to include the documentation with the Docker image./ 

I imagine the link being accessible via http://localhost:9090/gitpitch/desktop/manager.

If processing the documentation at the same time as a users slides is too much at least include a PDF link (where PDF is included in image) so users can view documentation offline.

**Comment by gitpitch** [comment]
@martindsouza the complete GitPitch docs are available for download. See [here](https://gitpitch.com/docs#gitpitch-docs). Giving you everything you should need when working offline.

**Comment by gitpitch** [comment]
FYI To improve discovery of the offline docs bundle the [Work Offline Guide](https://gitpitch.com/docs/work-offline) now has a dedicated chapter called [Offline Documentation](https://gitpitch.com/docs/work-offline/documentation).
