### ISSUE TITLE
Viewport in GitPitch Desktop

### ISSUE THREAD

**Issue by jakupmichaelsen** [gitpitch/gitpitch#270]
How to edit viewport settings for GitPitch Desktop? 

I'd like to be able to use 100% of with of my screen realestate :)

**Comment by gitpitch** [comment]
Hi Jakup, currently there is no hook for presentation authors to control the amount of _"empty space"_ between the edge of the slide area and the edge of your browser window. The area available to render your slide content is computed by the underlying reveal library based on a number of factors - including the browser viewport size and the result of content scaling to preserve the aspect ratio of your slides. These sizes are recomputed each time a slide is rendered or the browser viewport changes. Given this you will need to work within the slide area available. But you won't be able to force content out to the edges. Cheers, David.

**Comment by jakupmichaelsen** [comment]
Hi David.
This is easy to do with pure Reveal.js: 

```
Reveal.initialize({
    width: '100%',
    height: '100%'
})
```

But since GitPitch Desktop runs as a Docker image, I haven't been able to find or edit the html-template you use for Reveal.js.

**Comment by gitpitch** [comment]
> This is easy to do with pure Reveal.js

Sure. I'm aware of the `width` and `height` config options in the underlying reveal.js. There is also another config option called `margin` that is also pertinent here. But as noted, I do not currently expose those config options or `hooks` to GitPitch users. And I'm not sure I want to. As these are entirely untested configurations which may or may not play well with existing features.

When my time permits I'll try play around with these and see how well they interact with existing  GitPitch features, in particular, snap layouts. If I learn anything interesting I'll update this thread. But for now, there are no config `hooks` for you to use today.

**Comment by jakupmichaelsen** [comment]
Is it possible to run GitPitch directly from source, instead of through the docker image? 

It's just a huge amount of screen real estate that is lost to all that margin. I use reveal.js as an English teacher, and make ample use of the full layout of each Reveal.js slide. Before GitPitch, I used [reveal-md](https://github.com/webpro/reveal-md/), another markdown implementation of reveal.js, which handles passing reveal.js settings through a `defaults.json` file: 

``` 
"revealOptions": {
  "width": "100%",
  "height": "100%"
  },
```
Wouldn't it be possible to add this in a `PITCHME.yaml` file?

**Comment by gitpitch** [comment]
Just FYI, I did some testing using these options. By activating `100%` not only does it have the effect of disable uniform scaling of slide content but the resulting rendering also plays very poorly with GitPitch snap-layouts. Which is what I pretty much expected. Consequently, I will not be exposing these options. If you _really_ want this configuration for your decks above all else, I suggest using plain `reveal.js`.

**Comment by jakupmichaelsen** [comment]
Thanks for trying :) 
I'm just wonder if the resulting un-uniform scaling and problems with snap-layouts couldn't be solved through tweaking the CSS? 🤔
