### ISSUE TITLE
Is there an upgrade guide?

### ISSUE THREAD

**Issue by EvgenyOrekhov** [gitpitch/gitpitch#272]
I revisited my old GitPitch presentations and they don't work as they used to anymore. For example `<!-- .element: class="fragment" -->` doesn't work anymore. Is there any upgrade guide? Or at least a changelog?

**Comment by gitpitch** [comment]
There is no upgrade guide. But the [Markdown Fragments Guide](https://gitpitch.com/docs/markdown-features/fragments/) provides details on how best to activate fragments for content on your slides.

If that does not address your problem share a link to your deck and I will take a look. If you share a link, please point out which slide or slides demonstrate whatever problems you encountered.

**Comment by gitpitch** [comment]
Thinking further, the syntax you indicated should work, it has not been deprecated. So can you please share a link to your deck so I can investigate. It would be helpful if you could point out which slide or slides demonstrate whatever problems you encountered.Thanks.

**Comment by EvgenyOrekhov** [comment]
@gitpitch

Broken slide: https://gitpitch.com/EvgenyOrekhov/talks?p=can-we-live-without-this#/5/1
Source: https://github.com/EvgenyOrekhov/talks/blob/master/can-we-live-without-this/PITCHME.md#with

I don't know if it's related, but you can see that code indentation is also broken on the slide.

**Comment by gitpitch** [comment]
I've just looked over your `PITCHME.md` for your deck and I'm seeing some unexpected syntax. Specifically, your use of the following comment syntax on a line all of it's own with no connection to any slide element:

```
<!-- .element: class="fragment" -->
```

What do you expect this to do? I don't expect it to do anything. 

Per the [Reveal README](https://github.com/hakimel/reveal.js/#element-attributes):

> Special syntax (through HTML comments) is available for adding attributes to Markdown elements. This is useful for fragments, amongst other things.

The example they use is as follows:

```markdown
- Item 1 <!-- .element: class="fragment" data-fragment-index="2" -->
- Item 2 <!-- .element: class="fragment" data-fragment-index="1" -->
```

Obviously GitPitch  has a much simpler ways to achieve the same result for list items:

```markdown

---

- Item 1 |
- Item 2 |

---

@ul
- Item 1
- Item 2
@ulend

```

These snippets show the old way for plain-text list item fragments and the recommended way for all lists fragments using the [List Markdown Widget](https://gitpitch.com/docs/markdown-features/list-fragments).

But back to your original issue, the key thing about the HTML comment feature is that the syntax is used _on an element_. In the example from the Reveal README, on list item elements.

In your deck, you are using this comment syntax but it is not directly connected with any element on your slide. And as such it does nothing. If this once did something for you it was coincidental. This feature has never been intended to support nor documented to be used as you are currently using it.

Here are some concrete suggestions for you:

```markdown

![Edsger W. Dijkstra](img/dijkstra.jpg)

Edsger W. Dijkstra

<!-- .element: class="fragment" -->

---

![Edsger W. Dijkstra](img/dijkstra.jpg)

Edsger W. Dijkstra <!-- .element: class="fragment" -->

---

![Edsger W. Dijkstra](img/dijkstra.jpg)

@css[fragment](Edsger W. Dijkstra)

---

![Edsger W. Dijkstra](img/dijkstra.jpg)

@div[fragment]
Edsger W. Dijkstra
@divend

```

Each of these slide snippets are explained as follows:

1. The first slide shows your original markdown
2. The second slide shows how you can fix your original markdown using comment syntax
3. The third slide shows how you can use a GitPitch shortcut syntax 
4. The fourth slide shows how you can keep your content and styling separate

Slides 2, 3, and 4 will all render the same. Which approach you take is really up to personal preference.

Whatever approach you take, you will need to update your deck. And I refer you again to the [Markdown Fragments Guide](https://gitpitch.com/docs/markdown-features/fragments/) for best practices. If you can't find the answer you need for a specific slide in that guide, let me know and I can advise further.

**Comment by EvgenyOrekhov** [comment]
@gitpitch I was using the `<!-- .element: class="fragment" -->` syntax to reveal code blocks one by one. In this example only the first code block used to appear, and I had to press the down arrow to reveal the next code block:

````markdown
```js
ooo.eee.oo.ah_ah.ting.tang.walla.walla.bing = true;
ooo.eee.oo.ah_ah.ting.tang.walla.walla.bang = true;
```

```js
with (ooo.eee.oo.ah_ah.ting.tang.walla.walla) {
    bing = true;
    bang = true;
}
```

<!-- .element: class="fragment" -->
````

What is the proper way to achieve this?

**Comment by gitpitch** [comment]
Ok. So if you are a GitPitch subscriber on a paid-plan you can take advantage of the advanced [fenced-code blocks](https://gitpitch.com/docs/code-features/fenced-blocks) syntax:

````markdown
```js
ooo.eee.oo.ah_ah.ting.tang.walla.walla.bing = true;
ooo.eee.oo.ah_ah.ting.tang.walla.walla.bang = true;
```

```js fragment
with (ooo.eee.oo.ah_ah.ting.tang.walla.walla) {
    bing = true;
    bang = true;
}
```
````

And if you are on the free plan the simplest approach is to wrap the second code block on your slide in `div` or `snap` tags, like this:

````markdown
```js
ooo.eee.oo.ah_ah.ting.tang.walla.walla.bing = true;
ooo.eee.oo.ah_ah.ting.tang.walla.walla.bang = true;
```

@div[fragment]
```js
with (ooo.eee.oo.ah_ah.ting.tang.walla.walla) {
    bing = true;
    bang = true;
}
```
@divend
````

Either approach should give you what you need.

**Comment by EvgenyOrekhov** [comment]
@gitpitch Thank you for quick replies! Great support!
