### ISSUE TITLE
Multi-level includes

### ISSUE THREAD

**Issue by meeas** [gitpitch/gitpitch#273]
It seems that the current implementation of "---?include=..." only works one level deep.  If you include a PITCHME.md that has its own include statement, that include statement only provides a single empty slide.  Not sure if this is a bug or if the include functionality was only intended to work a single level deep.  I'd love to have at least 5 levels deep of includes, and am actively trying to include 2-3 levels in a current set of training courses.

**Comment by gitpitch** [comment]
Hi Justin,

> Not sure if this is a bug or if the include functionality was only intended to work a single level deep.

Not a bug. Only intended to work a single level deep. It is implemented this way to avoid any possibility of circular dependencies. Which would add  a __lot__ of additional complexity.

> I'd love to have at least 5 levels deep of includes, and am actively trying to include 2-3 levels in a current set of training courses.

Based on the support available today, not possible. It looks like you will need to to reconsider how you structure your course content to deliver a modular solution.
