### ISSUE TITLE
Can't make an image link

### ISSUE THREAD

**Issue by becka11y** [gitpitch/gitpitch#274]
I want to use an image rather than text for a link. Thus, the image must have alt text.  I have tried:

[@img[alt text](assets/img/local-image.png)](https://link-destination)

This sets the class value for the image to the alt text. I realize the @img is used for styling an image. It would be nice to be able to style an image and also add the required alt text.

I have also tried:
[![alt text](assets/img/local-image.png)](https://link-destination) 

This works locally but not when displaying via gitpitch link.  

Sorry, if this is described somewhere or I am not following the instructions properly - I did look. 
(see https://gitpitch.com/becka11y/wcag-by-example#/113)

**Comment by gitpitch** [comment]
Hi Becky, if I understand correctly what you need you can do the following:

```
<a target="_blank" href="https://your/target/url">
![YOUR ALT TEXT](path/to/img.file)
</a>
```

Let me know if this gives you what you need.

**Comment by becka11y** [comment]
Yes, thanks! Sorry, duh - I forget that I can embed html within markdown. I knew I was going to be embarrassed by posting this.

**Comment by gitpitch** [comment]
No problem Becky. Glad you have a solution for what you need. All the best, David.
