### ISSUE TITLE
Latex on GitPitch Desktop Pro Edition doesn't work.

### ISSUE THREAD

**Issue by fx-kirin** [gitpitch/gitpitch#275]
I followed the example [here](https://gitpitch.com/docs/rich-media-features/latex-math/), but only the raw text was shown in the slide with the latest gitpitch pro desktop version.

Could you tell me what went wrong?

![Selection_029](https://user-images.githubusercontent.com/2161266/67543370-0a9a0b00-f72c-11e9-90e6-cfe8ac3e1423.png)

**Comment by gitpitch** [comment]
@fx-kirin can you please share a link to your repo with the files for your slide deck? Or if your files are not yet in a repo, can your share your puml file here? And the markdown for your sample slide? Thanks.

**Comment by gitpitch** [comment]
Btw, I just ran a quick test in GitPitch Desktop here and it seems to be working as expected. You can see a screenshot of what I'm seeing on my desktop here:

![test-puml](https://user-images.githubusercontent.com/19169584/67543748-03b7cc00-f71d-11e9-8291-27455da913c4.png)

**Comment by gitpitch** [comment]
Ok, great. Happy to hear it is working for you now. Cheers, David.
