### ISSUE TITLE
Hypertext links not exported to powerpoint?

### ISSUE THREAD

**Issue by nio101** [gitpitch/gitpitch#278]
It seems that hypertext links are not exported properly to powerpoint format?
It seems to be exported as formatted text without any link.
Note: it works with PDF export.

**Comment by gitpitch** [comment]
Hi Nicolas,  

> It seems that hypertext links are not exported properly to powerpoint format?

That is correct. This is a [documented limitation](https://gitpitch.com/docs/pro-features/desktop#export-slide-deck-content-constraints) of export to PPTX. Per the docs, if you need active links within your PPTX deck I recommend adding a dedicated slide at the end of your generated PPTX file. That additional slide can be used to include active links to related content. Hope this helps. David.
