### ISSUE TITLE
Offline generated slides fail to reflect some of the PITCHME.yaml theming options

### ISSUE THREAD

**Issue by jaromir-benes** [gitpitch/gitpitch#279]
Hi

The slides generated offline using the pro desktop fail to reflect some of the theming configuration options set in the PITCHME.yaml file (e.g. anything that goes after "transform" in theme-headline is not considered offline, i.e. emphasis, scale, line-height, padding). When I push everything to GitHub and generate the slides online, the appearance is correct.

This is on macOS Catalina 10.15.2, Docker 2.1.0.5, Safari and Chrome (the same issue on both).

Not sure if this is a known issue. If needed, I'll upload screenshots to document what I mean.

Best
Jaromir

**Comment by gitpitch** [comment]
Hi Jaromir, thanks for getting in touch. So it sounds like you might be running an old version of GitPitch Desktop. When is the last time you updated your Desktop image?

Support for theme settings like emphasis, scale, line-height, padding etc. was released alongside the new [Theme Builder](https://twitter.com/gitpitch/status/1215583521957240832) in early January 2020. 

Try downloading the [latest Desktop image](https://gitpitch.com/docs/work-offline/desktop-faq#how-can-i-download-the-latest-desktop-pro-image) and let me know how that goes. Cheers, David.

**Comment by jaromir-benes** [comment]
Many thanks, David, for a very prompt response.

Indeed, I haven't updated the desktop in a while... I tried to update right now but after a successful login into docker, I get the following error when pulling gitpitch/desktop:pro

Error response from daemon: pull access denied for gitpich/desktop, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Any ideas?
Many thanks again,
Jaromir

<img width="839" alt="Screen Shot 2020-01-19 at 9 42 59 PM" src="https://user-images.githubusercontent.com/25515306/72691512-bfae4a80-3b04-11ea-9660-67961956e974.png">

**Comment by gitpitch** [comment]
Hi Jaromir, it looks like you might have a small typo on your `docker pull` command, specifically the spelling of `gitpitch`. Try this:

```
docker pull gitpitch/desktop:pro
```

That should give you what you need. Let me know. Cheers, David.

**Comment by gitpitch** [comment]
Jaromir, I just realized that the typo is my 100% fault. I just recently updated the profile page and the text on the Copy button is incorrect. I will fix that right away. My apologies for the inconvenience here. And thanks for bringing this to my attention. Cheers, David.

**Comment by gitpitch** [comment]
Quick update on this thread. The typo mentioned above has been fixed and that fix has been pushed to the live server. Thanks again @jaromir-benes for bringing this to my attention.

Do let me know if you test the latest Desktop image and if it resolves the issue you reported.

**Comment by jaromir-benes** [comment]
Awesome. I pulled the new img and everything works like a charm. Many
thanks David!
