### ISSUE TITLE
PITCHME.yaml documentation?

### ISSUE THREAD

**Issue by Hwesta** [gitpitch/gitpitch#28]
A PITCHME.yaml is referenced on the [custom CSS](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) wiki page but I can't find other references or documentation on it.  Can you add some documentation about where this file is expected to be and what configuration can be put there?

I ran into this problem because the custom CSS I added didn't seem to work.  I added this PITCHME.yaml to the root of the repository
```
theme-override : docs/css/PITCHME.css
```
And the CSS file at `docs/css/PITCHME.css`
```
a img {
    border: 0;
}

.reveal .slides {
    text-align: left;
}
.reveal .slides section>* {
    margin-left: 0;
    margin-right: 0;
}
```

**Comment by Hwesta** [comment]
Of course, 2 mins after I submit this I find the https://github.com/gitpitch/gitpitch/wiki/Slideshow-Settings page with more information. Sorry!

**Comment by gitpitch** [comment]
No problems @Hwesta :) I've updated the Wiki TOC to help make this clearer, hopefully easier to find.

**Comment by Hwesta** [comment]
Thanks!  That's much easier to find.
