### ISSUE TITLE
Long code lines truncated in slide

### ISSUE THREAD

**Issue by elect86** [gitpitch/gitpitch#282]
As titled, I have quite a long lines which gets truncated at the end on the right side

Eg:

```kotlin code-reveal-fast
fun createShader(shader: Int, source: String) {
  GL20C.glShaderSource(shader, source)
  GL20C.glCompileShader(shader)
  val compileStatus = GL20C.glGetShaderi(name, GL20C.GL_COMPILE_STATUS) // Int
  if(compileStatus == GL20C.GL_FALSE) {
	val infoLogLenght = GL20C.glGetShaderi(shader, GL20C.GL_INFO_LOG_LENGTH) // Int
	val infoLog = GL20C.glGetShaderInfoLog(shader, infoLogLenght) // String
	throw Exception("glShader compile status false: $infoLog")
  }
}
```

What can be done to fix this?

**Comment by gitpitch** [comment]
> What can be done to fix this?

Giuseppe, you have a few options available to you:

1. Activate the [code-wrap property](https://gitpitch.com/docs/code-features/pro-code-power-properties/#code-wrap-property) on your fenced code block or code widget. 

2. Use [code zoom](https://gitpitch.com/docs/code-features/pro-code-zoom/) to zoom-out on your code. By zooming out you can display (fit) more code on your slide.

3. Or reformat the code itself to replace long lines with equivalent but shorter lines.

For example, you could do this:

```
fun createShader(shader: Int, source: String) {
  GL20C.glShaderSource(shader, source)
  GL20C.glCompileShader(shader)
  val compileStatus = GL20C.glGetShaderi(name,
                                  GL20C.GL_COMPILE_STATUS) // Int
  if(compileStatus == GL20C.GL_FALSE) {
	val infoblockLogLenght = GL20C.glGetShaderi(shader,
                                GL20C.GL_INFO_LOG_LENGTH) // Int
	val in foLog = GL20C.glGetShaderInfoLog(shader,
                                infoLogLenght) // String
	throw Exception("glShader compile status false: $infoLog")
  }
}
```

**Comment by elect86** [comment]
Oh damn, I was using `zoom-7` instead of `zoom-07`..

Thanks!

**Comment by gitpitch** [comment]
No problem Giuseppe. Glad you got that working now. It's great to see experimenting with so many different features. If any more questions come up just let me know. Cheers, David.
