### ISSUE TITLE
setting the language of the page

### ISSUE THREAD

**Issue by becka11y** [gitpitch/gitpitch#286]
I looked through the theme settings but I don't see a way to specify the language of the page.  Since I can change the language direction I suspect there is a way to specify the language? Sorry, if I missed it in the docs.

Declaration of the language is required by the Web Content Accessibility Guidelines.

**Comment by gitpitch** [comment]
Hi Becky, can you share a link to the guidelines you mentioned so I can understand exactly what is needed to support language in terms of compliance. Thanks, David.

**Comment by becka11y** [comment]
Here are the Web Content Accessibility Guidelines (WCAG) 2.1:  https://www.w3.org/TR/WCAG21/.   They can be a bit intimidating!  Here is the specific success criterion I am referencing: https://www.w3.org/TR/WCAG21/#language-of-page.

The easiest solution is to add the lang attribute and correct language code onto the HTML element. For example: lang="en"

**Comment by gitpitch** [comment]
Thanks Becky. I will take a look at the spec and update this thread once I have something in place for you to test. Cheers, David.

**Comment by gitpitch** [comment]
I have another update for you here. A new `lang` setting that can activated in the `PITCHME.yaml` for any slide deck. This activates the lang property on the top-level `<html lang="xx">` element for your slide deck. For example:

```
lang : "fr"
```

Again I still need to add these details to the docs by you can go ahead and try out the feature now. This is something best tested online using gitpitch.com. Let me know how it goes.

**Comment by gitpitch** [comment]
This feature has been implemented and [documented here](https://gitpitch.com/docs/settings/lang). Closing RFE.
