### ISSUE TITLE
Cannot access slides from private repo

### ISSUE THREAD

**Issue by joshuajung** [gitpitch/gitpitch#290]
I'm trying to access https://gitpitch.com/dev-jetzt/test-private/master, but receive a "Slideshow Presentation Not Found on Github" message. 

I think all the prerequisites are fulfilled:
* Team pro plan is active for the `dev-jetzt` team
* Oauth has been permitted for private repos
* `published : true` is set
* Repo/team name is correct

Everything seems to work fine as long as the repo is public, but then stops working when set to private. Is there anything else I should check?

Thanks a lot for your help.

**Comment by gitpitch** [comment]
Hi Joshua, I'll look into this now and will be back in touch as soon as I have an update for you. Cheers, David.

**Comment by gitpitch** [comment]
You did everything right Joshua. My mistake here, apologies. You should now be up and running. Can you please test your private deck once again and let me know how it goes. Thanks, David.

**Comment by joshuajung** [comment]
Hey David, thanks a lot for your super quick reaction. Accessing the presentation in the root directory now works exactly as expected. 

However, I'm still facing the same issue when looking at a subdirectory (called "sub" in my case), like:
https://gitpitch.com/dev-jetzt/test-private/master?p=sub

I assume this is the right syntax, as described here: https://gitpitch.com/docs/git/branch-many-slideshows/

**Comment by gitpitch** [comment]
OK. So just before I dig into this can I ask if you have a `PITCHME.yaml` file alongside the `PITCHME.md` file for your deck in your `sub` directory? If not, see the following:

- [Publishing Guide About Section](https://gitpitch.com/docs/pro-features/security)
- [Publishing Guide Access Control Policies](https://gitpitch.com/docs/pro-features/security/#slideshow-access-control-policies)

These sections of the guide provide important background and guidance re. publishing from within private repos. If all that is already in place for your `sub` deck, just let me know and I'll dig deeper.

**Comment by joshuajung** [comment]
I have actually tried both - not having a local `PITCHME.yaml` in the subfolder (this would actually be my preferred version) and adding a YAML file with `published : true`.

The result was the same in both cases ("Slideshow Presentation Not Found").

Thanks again for your help.

**Comment by gitpitch** [comment]
> I have actually tried both - not having a local PITCHME.yaml in the subfolder (this would actually be my preferred version)

OK. So hopefully after reading the docs that I linked to above you understand the purpose and need for an explicit access grant for each individual private deck.
  
>  and adding a YAML file with published : true.

So now that we know a `PITCHME.yaml` file must be present alongside any `PITCHME.md` in a private repo, can I ask you please add that file back to the `sub` directory in your repo. Once present, can you let me know so I can start investigating the issue you reported.

**Comment by joshuajung** [comment]
Thank you - seems to have been a mistake on my side (see my edit above). Glad we got this to work, thanks!

**Comment by gitpitch** [comment]
It seems just as I responded you updated your own post! So, the behavior you are now seeing is the expected behavior. If you first tried to access a private deck within a corresponding `PITCHME.yaml` and then soon thereafter tried again after adding that file to your repo you may have hit a brief caching window in the server that temporarily denied access. 

Hopefully now that you know what's needed in terms of access grants, it should be smooth sailing from here. But let me know anytime if you need further help. Cheers, David.
