### ISSUE TITLE
question: How to add additional highlight.js distributions?

### ISSUE THREAD

**Issue by graphadvantage** [gitpitch/gitpitch#292]
Hi

I'd like to include this highlight.js in gitpitch desktop pro

https://github.com/highlightjs/highlightjs-cypher

Per the highlight team this highlighter will not be included in the main highlight.js...

https://github.com/highlightjs/highlight.js/pull/2426

Is there a way to accomplish this? I get the CORS issue, but perhaps locally by mounting a docker volume for extra js?  or as dialog in the template customizer?

Thanks!

**Comment by gitpitch** [comment]
Hi Michael,

I do not support the activation of custom JS within GitPitch slide decks. Primarily to ensure presentation authors do not end up using *gitpitch.com* to distribute malicious code either intentionally or accidentally. So today there is no way for you to activate support for `cypher` code syntax highlighting as it appears to be delivered as a JavaScript file, *cypher.min.js*.

You may want to consider activating an alternative code language hint for `cypher` code blocks on your slides. For example, I quickly tried a few different language hints and found that the `css` hint delivers a pretty nice looking `cypher` code slide:

![cypher-as-css-highlighting-shadow](https://user-images.githubusercontent.com/19169584/76457981-5e398800-639f-11ea-99b5-b4f9df51c7cb.png)

You could experiment with other values for the [language hint](https://gitpitch.com/docs/code-features/fenced-blocks/#code-language-hints-quick-reference-table) on your code blocks to see if another language hint might suit you better.

More long term I will need to consider how to best to accommodate the new policy re. merging 3rd party language as indicated on the *highlight.js* issue thread that you shared. Today, the best solution I have for you is to adopt the workaround outlined above and choose an alternate [language hint](https://gitpitch.com/docs/code-features/fenced-blocks/#code-language-hints-quick-reference-table) for your *cypher* code blocks.

If you have any questions or want to discuss further just let me know. Cheers, David.

**Comment by graphadvantage** [comment]
Thanks David - works for me!
