### ISSUE TITLE
not easy to remove background on challenge

### ISSUE THREAD

**Issue by timveil** [gitpitch/gitpitch#293]
I do not want an image as the background to my challenge screen but rather a plain color.  since a default image is inserted into the elements style definition, i cannot override it with css.

```
<div id="pro-background" class="background-image-holder" style="background:  url(&quot;/assets/images/audience.jpg&quot;); opacity: 1;">
   <img alt="background" src="/assets/images/audience.jpg">
</div>
```

how do i specify no background image in either the `.yaml` file or in css.  the following does not work...

```
#pro-background {
    background-color: #37A806;
    background-image: none;
}
```

**Comment by timveil** [comment]
for example something like this would be useful in the `.yaml`.

```
pro-background : none
```

**Comment by timveil** [comment]
i worked around this issue by just creating a simple 1x1 px image (http://www.1x1px.me/) with the solid color i wanted.  this works for now but maybe worth coming up with a cleaner solution.

**Comment by gitpitch** [comment]
I have pushed some experimental new support to give you better control over the background rendered by the [GitPitch Publishing Confidential Mode](https://gitpitch.com/docs/pro-features/security#confidential-mode) challenge screen.

The default challenge screen renders as shown here:

![confidential-1](https://user-images.githubusercontent.com/19169584/80275616-642ec280-86da-11ea-95bf-2504872c26f2.png)


Per your suggestion you can now specify `none` on the `pro-background` setting:

```yaml
pro-background : none
```

When `none` is set on this property the default background image is hidden as shown here:

![confidential-2](https://user-images.githubusercontent.com/19169584/80275617-685ae000-86da-11ea-97a1-1bdcd448c4a5.png)

As you can see the default background color is `black`. A new setting `pro-background-color` is now provided that gives you a quick and easy way to activate a custom background color. For example:

```yaml
pro-background : none
pro-background-color : "#3686E4"
```

These sample settings render as shown here:

![confidential-3](https://user-images.githubusercontent.com/19169584/80275622-7577cf00-86da-11ea-97c6-df57da1871b6.png)


The new `pro-background-color` setting can also be used to activate a background color gradient using any valid CSS [linear-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) value, for example:

```yaml"
pro-background : none
pro-background-color : "linear-gradient(to right top, #051937, #004d7a, #008793);"
```

These sample settings render as shown here:

![confidential-6](https://user-images.githubusercontent.com/19169584/80275627-7ad51980-86da-11ea-842a-b2d93f2efd3d.png)

This support has been added to [GitPitch Desktop](https://gitpitch.com/docs/work-offline/desktop-faq) so you can test there using the special `http://localhost:9000/gitpitch/confidential` url in your browser. This also can be tested live on gitpitch.com.

As this needs real world testing so I will await your feedback before moving ahead with formal docs. Thanks, David.

**Comment by timveil** [comment]
changes look great locally!

**Comment by gitpitch** [comment]
This feature has been implemented and [documented here](https://gitpitch.com/docs/pro-features/security#confidential-mode-customization). Closing RFE.
