### ISSUE TITLE
favicon support

### ISSUE THREAD

**Issue by timveil** [gitpitch/gitpitch#294]
would be great to support the addition of a custom favicon in `PITCHME.yaml`

**Comment by gitpitch** [comment]
I've just added a `favicon` setting that can be used in the `PITCHME.yaml` for any slide deck. The settings takes a relative path to your favicon image file, for example:

```
favicon : assets/img/favicon.png
```
I still need to write the docs for this but you can go ahead and try out the feature now. First you'll need to download the [latest version of the Desktop](https://gitpitch.com/docs/work-offline/desktop-faq). This feature is also now live on gitpitch.com. Let me now how it goes.

**Comment by timveil** [comment]
thats awesome @gitpitch.  will give it a try asap!

**Comment by timveil** [comment]
@gitpitch looks great!!!

**Comment by gitpitch** [comment]
This feature has been implemented and [documented here](https://gitpitch.com/docs/settings/favicon/). Closing RFE.
