### ISSUE TITLE
A better slide management experience in the desktop app

### ISSUE THREAD

**Issue by smwilson1230** [gitpitch/gitpitch#298]
Currently when you start up the desktop container it scans the root directory. If you have many PITCHME.md files or several levels of content it becomes very hard to navigate. I am proposing to have a tag in the PITCHME.yaml that allows to override the default behavior of the file path and have a user defined link text. I would also like to see it moved to a list view vs. in the 1/3 widget on the right hand side as well. Maybe a toggle between content development and content delivery. These are very distinct use cases.

**Comment by gitpitch** [comment]
With the release of [GitPitch 4.0](https://twitter.com/gitpitch/status/1310868554296815618) the desktop app has been redesigned. Part of that redesign includes a new slide deck manager that provides a proper list of decks found in your working directory. This list can be scrolled making it simple to find specific decks. If you want to provide more detail describing what you have in mind when you say `Maybe a toggle between content development and content delivery` please update the thread. For now I'm closing this RFE as implemented.
