### ISSUE TITLE
Slide content alignment types

### ISSUE THREAD

**Issue by mike-ward** [gitpitch/gitpitch#3]
Slides are currently centered.

Is there a way to get the classic:

```
slide title
----------
- item 1
- item 2
```
Again. look to jdan/cleaver for inspiration on how they do this.

**Comment by gitpitch** [comment]
Hi @mike-ward changing alignment on slides is not currently supported but a broader feature that will permit overriding default styling (including things like alignment) is planned and should be available as early as next week. I'll update this thread once that feature goes live.

**Comment by gitpitch** [comment]
Check out the new Wiki documentation on [Slideshow Custom CSS](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) for GitPitch presentations. This new feature gives you a lot of power to customize the look and feel of your slideshows, including the ability to customize the alignment of content on your slides.

**Comment by gitpitch** [comment]
Left aligned slide content now supported by [Slideshow Custom CSS](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS). Issue resolved, closing.
