### ISSUE TITLE
External links in a presentation should open in a new tab

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#30]
The first slide in [this presentation](https://gitpitch.com/Georgetown-University-Libraries/BarcodeInventory/master?grs=github&t=white) has an external link.  

In Firefox, Chrome, and Safari, if I click it, I see a bunch of icons in the slide viewer, but the link does not open.

In IE, I see an error message "This content cannot be displayed in a frame".  If I click the link in the error dialog, a new tab opens.

**Comment by gitpitch** [comment]
There is a simple workaround to give you the behavior you want when people click on you links. You can replace implicit Markdown links in your `PITCHME.md` with HTML anchor syntax that uses a `_blank` target.

For example, based on the sample presentation you provided, replace this markdown in your `PITCHME.md`:

```
- https://github.com/terrywbrady/info

```

With this:

```
<a target="_blank" href="https://github.com/terrywbrady/info">- https://github.com/terrywbrady/info</a>
```

Note, this general approach is also mentioned in the [HTML Slides](HTML-Slides) page in the Wiki.

**Comment by terrywbrady** [comment]
This works as you describe.  I had presumed I would need to rewrite the whole slide with the HTML syntax.  This works well.  I have updated my presentations.

**Comment by augnustin** [comment]
I don't consider the suggested workaround as acceptable. Changing a URL to a full `<a>` tag removes all the markdown readability.

I'd be in favor of having the following script executed in gitpitch:

```
Array.from(document.getElementByTagName('a')).forEach($link => {
  if ($link.hostname !== window.location.hostname) {
    $link.setAttribute('target', '_blank');
  }
});
```

And if you need more arguments, here are my reasons: https://augustin-riedinger.fr/en/resources/thoughts-on-target-blank/

**Comment by gitpitch** [comment]
Just fyi, I've updated GitPitch to auto-translate all anchors within a slideshow to target `_blank` per suggestion. In fact the 1.x branch already did this but for some reason I pruned this code when releasing 2.x. Anyway, from now on regular Markdown link syntax is all you need.

**Comment by augnustin** [comment]
Great! Thanks for taking feedback into consideration!
