### ISSUE TITLE
GitPitch Desktop version?

### ISSUE THREAD

**Issue by timveil** [gitpitch/gitpitch#300]
Would it be possible to log the version of the the desktop tool on either the interface or in the container log.  for example i see the following but not much else useful info.  In addition it would be nice to know when a new container/version is published so that i'm sure to get the latest.  this in addition to release notes i mentioned earlier ( #297) would be helpful. as i collaborate with other team members i want to make sure we are developing against the same version.

```
[info] c.g.s.DesktopService - GitPitch Desktop Pro Edition started.
```

**Comment by gitpitch** [comment]
I've just updated the Desktop so it now logs the build date in the console on start up. For example:

```shell
$ docker run -it -v /repo/test:/repo -p 9000:9000 gitpitch/desktop:pro
[info] c.g.s.DesktopService - GitPitch Desktop Pro Edition started.
[info] c.g.s.DesktopService - BUILD Fri Apr 24 17:13:20 UTC 2020
[info] c.g.s.RefreshService - SWEEP directory watcher detected 32 files in 12 ms.
[info] c.g.s.RefreshService - SWEEP directory watcher using default interval 250 ms.
[info] c.g.s.DesktopService - EXPORT ( PDF / PPTX ) service is enabled.
[info] play.api.Play - Application started (Prod)
[info] p.c.s.NettyServer - Listening for HTTP on /0.0.0.0:9000
```

See **BUILD** in the output shown above. To try this out you will need to download the [latest version of the Desktop](https://gitpitch.com/docs/work-offline/desktop-faq). This should help when collaborating with other team members when you want to make sure we are developing against the same version.

The separate issue of knowing when a new container/version is published is something I'll need to consider. I agree it would be helpful. And it's something I will look into.

**Comment by timveil** [comment]
thanks @gitpitch this is very useful!
