### ISSUE TITLE
Code indentation is broken

### ISSUE THREAD

**Issue by EvgenyOrekhov** [gitpitch/gitpitch#301]
GitPitch rendering:

![image](https://user-images.githubusercontent.com/8045060/80279868-d1f1e300-8708-11ea-9068-8d4cb4cbbce2.png)

GitHub Markdown rendering:

![image](https://user-images.githubusercontent.com/8045060/80279883-edf58480-8708-11ea-852e-2bfe25d87319.png)

Slide: https://gitpitch.com/EvgenyOrekhov/talks?p=why-so-functional#/5/6

Source: https://github.com/EvgenyOrekhov/talks/blob/master/why-so-functional/PITCHME.md#v10 (you'll have to scroll down a bit to find the slide)

Some slides are broken, some slides are fine.

Another broken example in a different presentation: https://gitpitch.com/EvgenyOrekhov/talks?p=can-we-live-without-this#/7/2.

**Comment by gitpitch** [comment]
Hi Evgeny. Can you tell me if this is a recent regression in the rendering of your deck? For example, have you viewed your sample deck anytime recently when these rendering problems did not occur on your slides? I'm just trying to understand if this problem is something new. Thanks, David.

**Comment by EvgenyOrekhov** [comment]
I noticed this regression on September 29th, 2019. Here is the first reference: https://github.com/gitpitch/gitpitch/issues/272#issuecomment-536296118. The last time I know for sure the slides were working perfectly was in July 2017.

**Comment by gitpitch** [comment]
@EvgenyOrekhov I have just pushed a patch that is now live on gitpitch.com. This patch should resolve the code indentation issues you reported. Can you please test each of the issues within your slide decks and let me know how your testing goes. Thanks, David.

**Comment by EvgenyOrekhov** [comment]
I checked all slides, everything works now! Thank you! Feel free to close this issue.

**Comment by gitpitch** [comment]
OK, good. Thanks for reporting the issue and testing the fix.
