### ISSUE TITLE
better alignment options

### ISSUE THREAD

**Issue by timveil** [gitpitch/gitpitch#302]
I know we have `@snap` for high level layouts but i'm finding that insufficient is some cases.  For example i prefer a more traditional slide layout where text is left aligned.  I've found a number of cases where i want to center `@uml` or other content directly below the text.  If i use `@snap` and `midpoint` to "center" the diagram or image it essentially uses absolute positioning and doesn't flow with the text directly above it.  you can see this in the linked image.

<img width="1439" alt="2020-04-27_11-29-06" src="https://user-images.githubusercontent.com/3260845/80390586-9d059d80-887a-11ea-8fe6-a148e8b50277.png">

the following code is used:

```
@title[Cluster]
## Cluster
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet massa vitae tortor condimentum. Fermentum dui faucibus in ornare quam. Pellentesque pulvinar pellentesque habitant morbi. Donec et odio pellentesque diam volutpat commodo sed. Aliquam malesuada bibendum arcu vitae elementum curabitur. Dapibus ultrices in iaculis nunc sed augue lacus viverra vitae. Ut etiam sit amet nisl purus in. Rhoncus aenean vel elit scelerisque. Morbi non arcu risus quis varius quam quisque. Non curabitur gravida arcu ac tortor. Commodo elit at imperdiet dui accumsan sit.
@snap[midpoint span-100]
@uml[](assets/uml/nodes-healthy-three.puml)
@snapend
```

what about a `@align` concept or other mechanism to wrap certain content

**Comment by gitpitch** [comment]
> I know we have @snap for high level layouts but i'm finding that insufficient is some cases...

One solution is to treat your title, text, and image as a single block using snap tags. Activating your preferred *master* alignment for the block. And then activating a targeted custom alignment for the image within the block. Doing so you can end up with a slide that looks something like this:

![gitpitch-custom-layout-example-shadow](https://user-images.githubusercontent.com/19169584/80403028-c8a67900-88b6-11ea-86af-98212dd6f28f.png)

I didn't have access to your sample image or uml diagram but I believe my slide design matches what you had in mind. Right? 

The **PITCHME.md** markdown used to create this slide design is shown here:

```markdown
@snap[midpoint span-100 text-left]
### Cluster
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsu    m has been the industry's standard dummy text ever since the 1500s, when an unknown p    rinter took a galley of type and scrambled it to make a type specimen book.
@div[centered push-20]
![width=500px, height=250px, centered](assets/img/colors.jpg)
@divend
@snapend
```

Note the `text-left` alignment has been activated as the *master* alignment for the block on the opening `@snap` tag. And the custom CSS style rule `centered` is used to ensure the content inside the `@div` is centered within the parent (which is the snap block). And as a final tip I have also used a custom `push-20` style rule to control the vertical space between the text and the image. The complete custom CSS I used is shown here:

```css
div.centered { margin: auto; }
div.push-20 { padding-top: 20px; }
```

If I have understood your intended design correctly I believe this approach will give you what you need. But let me know once you've had a chance to look this over. Thanks, David.

**Comment by timveil** [comment]
that would work well.  is `@div` available today?  i had not seen that in the docs.

**Comment by gitpitch** [comment]
Yes, `@div` is fully supported. And yes it is indeed missing from the docs. My bad. The syntax follows that of all standard markdown widgets:

```
@div[props...]
your content goes here
@divend
```

Where `props...` can be any [built-in style](https://gitpitch.com/docs/themes/css-utility-styles/), any [custom style](https://gitpitch.com/docs/themes/custom), or [fragment behavior](https://gitpitch.com/docs/markdown-features/fragments/).

**Comment by timveil** [comment]
haha!  any other hidden features?

**Comment by gitpitch** [comment]
> haha! any other hidden features?

Sure! But I can't tell you about them or they wouldn't be hidden :-)
