### ISSUE TITLE
MathJax formatting doesn't work inside of snaps

### ISSUE THREAD

**Issue by droberts-ada** [gitpitch/gitpitch#303]
## Setup
```yaml
# PITCHME.yaml

# Turn on MathJax plugin
mathjax : TeX-MML-AM_HTMLorMML-full
```

```md
<!-- PITCHME.md -->
@snap[midpoint]
`\[O(1)\]`
@snapend
```

## Expected Behavior

Renders `O(1)` in italics like it's a LaTeX math formula

This is what happens without the snap

## Observed Behavior

Renders `[O(1)]` as an inline code block. Seems like MathJax formatting pass is getting skipped entirely.

**Comment by gitpitch** [comment]
Hi Dan, check out the [MathJax By Example within Snap Layouts](https://gitpitch.com/docs/math-features/math-formulas/#learn-by-example-within-snap-layouts) section within the MathJax Formulas Guide. You'll see that you need to use `@math` and `@mathend` tags to wrap your standard MathJax syntax when working within snap tags. Give it a try and let me know how it goes. Cheers, David.

**Comment by droberts-ada** [comment]
Works like a charm - thanks David! Sorry for the false alarm.

**Comment by gitpitch** [comment]
Great. And no problem at all. Cheers, David.
