### ISSUE TITLE
Audio in @note portions of audio deck not working

### ISSUE THREAD

**Issue by scarey9** [gitpitch/gitpitch#304]
The slide list fragment audio works with the @note[](path) notation in GitPitch Desktop but is not working once deployed. 

Refrenced functionality: https://gitpitch.com/docs/pro-features/audio/#add-slide-list-fragment-audio

Repo: https://gitlab.com/SeanCarey/practicum-2-carey

URL: https://gitpitch.com/SeanCarey/practicum-2-carey/master?grs=gitlab#/

Slide 2 and slide 11 are both having the same issue, not audio for the list items

**Comment by scarey9** [comment]
I found a workaround to using the note notation.  My repo no longer matches what the problem was showing.  Closing the Issue.

**Comment by gitpitch** [comment]
Hi Sean, thanks for reporting this issue. I will look into it over the coming days and update this thread once I know more. Cheers, David.

**Comment by gitpitch** [comment]
A patch to fix [list fragment audio](https://gitpitch.com/docs/pro-features/audio/#add-slide-list-fragment-audio) is now live on gitpitch.com. @scarey9 you can verify this patch by viewing the version of your slide deck at the time when you reported the issue. The URL for that version of your deck is here:

[https://gitpitch.com/SeanCarey/practicum-2-carey/f1923876?grs=gitlab](https://gitpitch.com/SeanCarey/practicum-2-carey/f1923876?grs=gitlab)

David

**Comment by scarey9** [comment]
Thank you. I reverted my got repo to use the my original presentation. Much appreciated.  This fixes my problem
