### ISSUE TITLE
Best pattern for slide element vertical alignment 

### ISSUE THREAD

**Issue by bwplotka** [gitpitch/gitpitch#306]
`span-xxx` works great in terms of width, however, the `snap`'s  `north, east` etc positioning is not enough. I wish there is some custom control of vertical positioning inside a `snap` itself.

Currently to achieve nice positioning I have to hack it with multiple `snaps` or/and `<br/>` which is not tedious and very portable across resolutions I believe ): For example see: https://github.com/bwplotka/my/blob/optimizing-clouds/slides/common/whoami-go/PITCHME.md

Is there any better approach for this?

The best TBH would be if nested `snap` would work :heart: Then I would be able to specify `north` inside of `east` and have clean positioning. Would that be considered in the future? :hugs: 

Thanks!

**Comment by gitpitch** [comment]
> I wish there is some custom control of vertical positioning inside a snap itself.

As a general note, you can control the vertical spacing between elements inside and outside of snap regions by customising [the theme](https://gitpitch.com/docs/themes/template/) for your slide deck. The simplest way to do that is to use the [Theme Builder](https://gitpitch.com/docs/themes/default). As you will see each of the major component types (headline, byline, etc) can have it's own custom **padding** value. But it is important to note that those settings are global to your entire deck, not local to individual snap regions.

> Currently to achieve nice positioning I have to hack it with multiple snaps or/and <br/> which is not tedious and very portable across resolutions I believe ): For example see: https://github.com/bwplotka/my/blob/optimizing-clouds/slides/common/whoami-go/PITCHME.md
> Is there any better approach for this?

I think in place of `<br>` a cleaner approach is to use custom classes that define custom `padding` in order to control the positioning of your content. For example, here is a snippet of your current markdown:

```
@snap[east higher span-48 text-06 text-left]
###### Principal Software Engineer [@ Red Hat](https://http://redhat.com/)
<br/><br/><br/><br/><br/>
@snapend
```

Using a custom class to position this content could look like this:

```css
.pad-bottom-190 {
  padding-bottom: 190px !important;
}
```

And then the markdown could look like this:

```
@snap[east higher span-48 text-06 text-left pad-bottom-190]
###### Principal Software Engineer [@ Red Hat](https://http://redhat.com/)
@snapend
```

Both approaches will deliver the same slide. Personally I prefer the approach that takes advantage of custom styles. Cleaner markdown. And will render more consistently across browsers.

> The best TBH would be if nested snap would work ❤️ Then I would be able to specify north inside of east and have clean positioning. Would that be considered in the future? 🤗

Nested snaps, no. But something much much better, yes :-) A brand new layout system for GitPitch is already in progress. Not ready to share details here today but it is something that is coming down the pipeline...

**Comment by gitpitch** [comment]
Btw, I looked again at the markdown for the sample slide that you shared and I noticed that most of your *work* was spent creating the east snap region. So I recreated your slide myself to try and simplify the approach a little bit. Here is your original markdown using two different *east* snap regions:

```
@snap[east higher span-48 text-06 text-left]
###### Principal Software Engineer [@ Red Hat](https://http://redhat.com/)
<br/><br/><br/><br/><br/>
@snapend

@snap[east span-48 text-04 text-left]
@css[0.8em](_Team Leader, OpenShift Observability Team_) 
<br/>
@ul[list-spaced-bullets list-square-bullets text-065](false)
* Co-founder of Open Source [Thanos](https://thanos.io) project.
* [CNCF SIG Observability](https://github.com/cncf/sig-observability) Tech Leader.
* Maintainer of various OSS: [Prometheus](https://prometheus.io), [configuration.fyi](https://configuration.fyi), [prometheus/client_golang](https://github.com/prometheus/client_golang), [bingo](https://github.com/bwplotka/bingo), [go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware), [prometheus grpc middlewares](https://github.com/grpc-ecosystem/go-grpc-prometheus), [Demo Navigator](https://github.com/bwplotka/demo-nav) and more... 
* Still active as an SRE (on-call fun @emoji[pager] @emoji[bell])
@ulend
@snapend
```

And this is what I came up with using just a single *snap* region:

```
@snap[east span-48 text-left text-06]
@css[text-05](_Team Leader, OpenShift Observability Team_) 
###### Principal Software Engineer [@ Red Hat](https://http://redhat.com/)
@ul[list-spaced-bullets list-square-bullets text-065](false)
* Co-founder of Open Source [Thanos](https://thanos.io) project.
* [CNCF SIG Observability](https://github.com/cncf/sig-observability) Tech Leader.
* Maintainer of various OSS: [Prometheus](https://prometheus.io), [configuration.fyi](https://configuration.fyi), [prometheus/client_golang](https://github.com/prometheus/client_golang), [bingo](https://github.com/bwplotka/bingo), [go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware), [prometheus grpc middlewares](https://github.com/grpc-ecosystem/go-grpc-prometheus), [Demo Navigator](https://github.com/bwplotka/demo-nav) and more... 
* Still active as an SRE (on-call fun @emoji[pager] @emoji[bell])
@ulend
@snapend

```

My version of your slide renders as follows:

<img width="1194" alt="Screenshot 2020-06-14 at 21 07 28" src="https://user-images.githubusercontent.com/19169584/84603022-2d2b9080-ae83-11ea-8bd1-f7b529ca5f38.png">

This seems very close to your original slide with a reasonably significant reduction in complexity in the markdown to deliver the slide. Just sharing this as food for thought.

Note, I did have to define one custom style rule to make this work:

```
.text-065 { font-size: 0.65em !important; }
```

This style rule was activated on your list content to size it similar to your original slide.

**Comment by bwplotka** [comment]
Thanks for so many good tips :+1: Some CSS generics would be nice ;p so I can template `padding-bottom-${var}` =D 

I think however that we can do a bit better here - still, it feels like CSS game is must-have to craft nice slides in gitpitch. It's 1000x better than what we tried to achieve with mdx with @kakkoyun https://github.com/kakkoyun/are-you-testing-your-observability/ (we wanted to die.. + it was never working well with different resolutions)

> Nested snaps, no. But something much much better, yes :-) A brand new layout system for GitPitch is already in progress. Not ready to share details here today but it is something that is coming down the pipeline...

Awesome to hear! I am happy to test it out if you have something, even if it's not yet perfect! :muscle: 

I feel like `snap` might be quite confusing:

1. snap blocks do not interact, which is sometimes nice, but mostly it means you have to craft `<br/>` and CSS to make sure things are not overlapping or are not too far away. Maybe something div based would mitigate the heavy need for custom CSS? This is actually how markdown works - all is controlled by content really.
1. We can specify position of snap, but it's... actually not listening to the position - if I will add more data it grows in height, which is hard to control. Sometimes I wish to have `west` snap block that just cover south-west`, instead I have to make very high `south-east`
1. Lack of nested control

So, yea if you have something better, please share, happy to test it out (: 

---
Thanks for looking into my slides! I simplified based on your tips, but still I ended up with second `snap` to make sure I don't have too much space between Header and words in italics (just looks better ^^), so instead of:

![image](https://user-images.githubusercontent.com/6950331/84638675-381c0a80-aeef-11ea-92a2-19375e6950bc.png)

it's:

![image](https://user-images.githubusercontent.com/6950331/84639013-afea3500-aeef-11ea-9e36-e3889ba54150.png)

at the end:

```
@snap[east higher span-48 text-06 text-left]
###### Principal Software Engineer [@ Red Hat](https://http://redhat.com/)
<br/><br/><br/><br/><br/>
@snapend

@snap[east span-48 text-04 text-left]
_Team Leader, OpenShift Observability Team_ 
<br/>
@ul[list-spaced-bullets list-square-bullets text-10](false)
* Co-founder of Open Source [Thanos](https://thanos.io) project.
* [CNCF SIG Observability](https://github.com/cncf/sig-observability) Tech Leader.
* Maintainer of various OSS: [Prometheus](https://prometheus.io), [configuration.fyi](https://configuration.fyi), [prometheus/client_golang](https://github.com/prometheus/client_golang), [bingo](https://github.com/bwplotka/bingo), [go-grpc-middleware](https://github.com/grpc-ecosystem/go-grpc-middleware), [prometheus grpc middlewares](https://github.com/grpc-ecosystem/go-grpc-prometheus), [Demo Navigator](https://github.com/bwplotka/demo-nav) and more... 
* Still active as an SRE (on-call fun @emoji[pager] @emoji[bell])
@ulend
@snapend
```
Thanks for helping so far!

---
On separate note, I don't really get what `h1,2,3,5` give in gitpitch. Looks like `text-xx` normalizes the size of everything to single font size, right? so headers and normal text has same size :thinking: I use headers only for different color really :facepalm: 

Also, interesting thing I found is that `text-10` is huge usually. But when used in nested context (like in my example above, in list), `text-10` is small if used nested with `text-05` as it's relative ;p I mean it's fine, just surprising I guess :shrug: 

Overall I feel like there is no much markdown left (: Maybe that's ok.

**Comment by gitpitch** [comment]
> I feel like snap might be quite confusing:
>
> 1. snap blocks do not interact, which is sometimes nice, but mostly it means you have to craft `<br/>` and CSS to make sure things are not overlapping or are not too far away. Maybe something
> 2. div based would mitigate the heavy need for custom CSS? This is actually how markdown works - all is controlled by content really. We can specify position of snap, but it's... actually not listening to the position - if I will add more data it grows in height, which is hard to control. Sometimes I wish to have west snap block that just cover south-west, instead I have to make very high south-east`
> 3. Lack of nested control

Thanks for this feedback. What snap layouts lets you do well is layout *blocks* of markdown content on your slides. The snap layouts 3x3 grid determines the level of layout granularity you can control with ease. The [Snap Layout Guide](https://gitpitch.com/docs/layout-features/snap-layouts) provides numerous examples that adopt this *markdown-as-block* approach.

When you start thinking about slide designs the way you might think about *drag-and-drop* layout tools (I want content X positioned n pixels above content Y within snap Z etc.) you quickly start to run into its limitations. 

So my advice for today advice is to try and work (where you can) with these limitations in mind when you are designing your slides. That may require you to rethink what your slide might look like. But it will likely be a lot more enjoyable experience when you work with snap layouts in mind.

> So, yea if you have something better, please share, happy to test it out (:

Coming soon. Probably within the next month or so if all goes well. I will bump this thread when that happens.

> On separate note, I don't really get what h1,2,3,5 give in gitpitch. Looks like text-xx normalizes the size of everything to single font size, right? 

No, that doesn't sound right. It simply scales the font size across all content types: headline, byline, plain text, etc. That property should probably have been named `font-xx` not `text-xx` but the effect is the same. For example this markdown snippet:

```
@snap[midpoint span-100]
# Hello
## Hello
### Hello
### Hello
#### Hello
@snapend
```

Renders as follows:

<img width="1232" alt="font-size" src="https://user-images.githubusercontent.com/19169584/84671864-c60fe980-af1f-11ea-889e-c6ddfdfe3346.png">

While this markdown snippet that activates the `text-06` property on the same snapped content:

```
@snap[midpoint span-100 text-06]
# Hello
## Hello
### Hello
### Hello
#### Hello
@snapend
```

Renders like this:

<img width="1232" alt="font-size-text-xx" src="https://user-images.githubusercontent.com/19169584/84671974-e770d580-af1f-11ea-8828-55d37edd4308.png">

As you can see the relative size of content changes...in this case each font size is *60%* of its original size. But the size of headline, byline, plain text etc has not been normalized to a single size.


> so headers and normal text has same size 🤔 I use headers only for different color really 🤦

Nope. Hopefully the example above makes this clear. Remember, per the [theme template](https://gitpitch.com/docs/themes/template) headline content is h1 and h2, byline content is h3 and h4 and plain text is just regular text. 

> Overall I feel like there is no much markdown left (: Maybe that's ok.

Maybe :) My point above about embracing the constraints of the current layout system (snap layouts) will help you get closer to wrapping regular markdown inside *snap* tags. But if what you have now works for you, then I'd be inclined to think...that's perfectly OK too.

**Comment by gitpitch** [comment]
With the release of [GitPitch 4.0](https://twitter.com/gitpitch/status/1310868554296815618) the new [grid-layouts system](https://docs.gitpitch.com/#/grid-layouts/) gives you complete control over horizontal and vertical positioning and sizing of content on your slides. Closing this RFE as implemented.
