### ISSUE TITLE
Enhancement: Better animation control on single slide.

### ISSUE THREAD

**Issue by bwplotka** [gitpitch/gitpitch#308]
Definitely not rush, but while creating slide I found it a little bit limiting to create more advanced animations.

Let's consider the following:

1. 4 snap elements, some images etc
1. I want to add another snap with image can use `fragment`
1. I want now another snap with image, can use `fragment`
1. Now I want to remove snaps with 2 & 3 and add different snap with image. I have to copy whole slide.
1. Now I want to give opacity 70% of element from 4 and add another snap - again, I have to copy whole slide..

It would be nice to do all those operations using some kind of control, similar to @[...](..) on live coding. It would hard to reference those, but still. Some idea to think about (:

**Comment by bwplotka** [comment]
Also sometimes I want to add two fragments at once (:

**Comment by gitpitch** [comment]
Thanks for the feedback and ideas. I'll keep this open as an RFE and see if the thread attracts upvotes and/or additional suggestions regarding these types of animations.

**Comment by gitpitch** [comment]
With the release of [GitPitch 4.0](https://twitter.com/gitpitch/status/1310868554296815618) you can now use [grid synchronization](https://docs.gitpitch.com/#/grid-layouts/synchronization) to display individual fragments or multiple-fragments simultaneously on any slide. To display multiple-fragments simultaneously specify a matching integer value on the `sync=` property for one or more layout blocks. For example:

```markdown
[drag=50 100, drop=left, sync=1]
# Hello

[drag=50 100, drop=right, sync=1]
# World
```

One request on this thread was to remove content that had already been rendered on your slide. This is not supported directly. Although  you could create a step that overlays empty layout blocks on top of the content you want to disappear. Simply activate a [color background](https://docs.gitpitch.com/#/grid-layouts/backgrounds) for the empty blocks that matches the background color of your slide.

Closing this RFE as implemented.

**Comment by bwplotka** [comment]
This is amazing!

**Comment by gitpitch** [comment]
Glad you like it. If you do try out 4.0 I'll be very interested in any feedback you have to share. Drop me an email anytime or you can DM me on [Twitter](https://twitter.com/gitpitch). Cheers, David.
