### ISSUE TITLE
Wrong display of special characters rendering title text associated with code delimiter.

### ISSUE THREAD

**Issue by veroandreo** [gitpitch/gitpitch#309]
When using the `?code=filename&lang=langname&title=something with a special character` syntax to present code within a slide, any special character in the title is displayed as a question mark

![image](https://user-images.githubusercontent.com/20075188/86930642-82338d00-c137-11ea-8c33-b57a93f77b8d.png)

To reproduce, try for example with accented characters from Spanish:

```
+++?code=code/05_temporal_code.sh&lang=bash&title=Gráfico temporal: LST vs tiempo
```

Using this solves the problem for now, but I will have to change a lot of slides:

```
---
Gráfico temporal: LST vs tiempo
@code[bash](code/05_temporal_code.sh)
```

Ideally, both types of syntax should handle special characters properly.

**Browser:**
 - Firefox

**Operating System:**
 - Linux: Fedora 32

**Comment by gitpitch** [comment]
Thanks Vero. I have just updated the title on this issue. I'm also sharing the workaround here for everyone to see. Simply replace the original [code delimiter syntax](https://gitpitch.com/docs/code-features/source-files/#introducing-the-source-code-delimiter):

```
---?code=code/05_temporal_code.sh&lang=bash&title=Gráfico temporal: LST vs tiempo
```

With the the following [code widget syntax](https://gitpitch.com/docs/code-features/pro-code-widgets/):

```
---
Gráfico temporal: LST vs tiempo
@code[bash](code/05_temporal_code.sh)
```

This change will deliver the same slide content while solving the character encoding problem associated with the `title` parameter on the code delimiter.

**Comment by gitpitch** [comment]
I believe the workaround works as documented. As code delimiters are a deprecated feature and a simple workaround is available I'm closing this issue as resolved. Please feel free to update this thread or even re-open the thread if needed, Cheers, David.
