### ISSUE TITLE
GitPitch 4.0 - deprecated syntax -> "Upgrade Guide" link is broken

### ISSUE THREAD

**Issue by MarkusTiede** [gitpitch/gitpitch#310]
**Describe the bug**
The link describing deprecated syntax / "upgrade guide" is broken : https://docs.gitpitch.com/#/upgrading-to-40

--> Page Not Found

**To Reproduce**
Try opening "https://gitpitch.com/markustiede/about/master?p=slides/intro" -> click "GitPitch 4.0 Upgrade Guide" link

**Expected behavior**
Clear migration path is shown.

**Browser (please complete the following information):**
 - Safari

**Operating System (please complete the following information):**
 - MacOS

**Additional context**
It's quite sad that (IMHO) instantly all of my presentations broke (due to unknown / unclear reasons); without being able to fix them.

**Comment by gitpitch** [comment]
Hi Markus,

First, thanks for reporting this problem. Just FYI I announced I was testing new software on gitpitch.com yesterday on Twitter, see [here](https://twitter.com/gitpitch/status/1303314758498648066). 

The fact that your slide deck is being blocked today is a bug in that new software. It is not intentional. And now that you have brought this to my attention I will investigate. Also that link is to docs that have not yet been published.

Anyway, once I understand the reason your deck is not rendering I will update this thread. Thanks for your patience. 

David

**Comment by gitpitch** [comment]
Btw, you mentioned that all your presentation broke. Can you provide links to one or two more examples of broken presentations so I can use them for testing. Thanks.

**Comment by MarkusTiede** [comment]
Hi David - thanks for the instant feedback and the reference: I've missed that.

Sure - what I've noticed so far: 
- broken: https://gitpitch.com/baloise/open-source/master?p=docs/slides/baloise-open-day
- major difference in rendering: https://gitpitch.com/dinacon/awards/master?p=2020/slides/kickoff

**Comment by gitpitch** [comment]
Thanks for the additional links. I'll update here when I know more.

**Comment by MarkusTiede** [comment]
Some more broken ones: 
- https://gitpitch.com/baloise/open-source/master?p=docs/slides/ch-open-obl-2020-02
- https://gitpitch.com/baloise/open-source/master?p=docs/slides/ch-open-obl-2020-08

**Comment by gitpitch** [comment]
OK, I've just looked over all the same decks that you shared and they all have one thing in common...none of them are using a `PITCHME.yaml` file for custom settings. I now have the problem in focus. I will patch, test, and then push a fix and then bump this thread one more time when you can test. More news from me when that's all in place.

**Comment by gitpitch** [comment]
OK. A patch is now live on gitpitch.com. Markus can you please re-test your slide decks and let me know how it goes. Cheers, David.

**Comment by MarkusTiede** [comment]
Thanks @gitpitch  - impressive: looks way better / working again: however the font's size is still quite small compared to before.

E.g. this is a screenshot from my intro slide from before:

![AD676C15-EC3B-4679-A5F4-3E5444693AFF](https://user-images.githubusercontent.com/1764012/92648859-69d42000-f2ea-11ea-8b90-8b1a3cc27979.jpeg)

<--> https://gitpitch.com/markustiede/about/master?p=slides/intro

**Comment by MarkusTiede** [comment]
I guess this problem is no longer covering the broken link :-) - thanks for addressing anyway!

**Comment by gitpitch** [comment]
I'll keep this issue thread open and look into the font issue next. Realistically, probably sometime tomorrow or Friday before I can get to this.

**Comment by gitpitch** [comment]
@MarkusTiede another update for you here. A further patch has been pushed to gitpitch.com. Can you please test your slide decks one more time and let me know if all issues are now resolved. Thanks, David.

**Comment by gitpitch** [comment]
I believe both of the issues reported on this thread (1) deck access and (2) font sizes have been fixed. Closing issue as resolved. If you have additional feedback please feel free to update or even re-open the thread if needed. Cheers, David.

**Comment by MarkusTiede** [comment]
Indeed - I can't tell any difference anymore: everything working again as expected 🙏
