### ISSUE TITLE
Shortcut speaker window not working?

### ISSUE THREAD

**Issue by MarcoWeiss** [gitpitch/gitpitch#311]
**Describe the bug**
To present i pressed F for full screen mode.
If i press S the speaker view is not shown
By pressing ? i do not see the short cut.

**To Reproduce**
Have a look at that test repo from gitlab
https://gitpitch.com/marcoweiss/gitpitchtest?grs=gitlab#/

**Expected behavior**
Pressing F and S should open the speaker window

**Browser (please complete the following information):**
 - Chrome 84.0.4147.89
 - Firefox 78.0.1

**Operating System (please complete the following information):**
 - Linux

**Comment by gitpitch** [comment]
Hi Marco, it looks like you opened this issue thread when I was right in the middle of testing the new [GitPitch 4.0](https://twitter.com/gitpitch/status/1310868554296815618) release on gitpitch.com. This new release (now live) has introduced lots of changes, including great new features plus changes to the set of [free v paid features](https://docs.gitpitch.com/#/trial-v-paid). One change that you will see is that online speaker support is no longer available on the free plan. You can follow that link I shared for further details.

I encourage you to try out the new GitPitch 4.0. You can download the 4.0 desktop app [here](https://docs.gitpitch.com/#/free-trial).

**Comment by MarcoWeiss** [comment]
Hey thanks for your response. I see it is now in the paid features. Noticed :)
