### ISSUE TITLE
"gitpitch : 3.0" setting does not allow 3.0 decks to be viewed in new desktop app

### ISSUE THREAD

**Issue by fonnesbeck** [gitpitch/gitpitch#313]
**Describe the bug**
Following the "Deprecated decks" instructions in the docs, I've added `gitpitch : 3.0` to the PITCHME.yaml file of a project that I wrote a year or so ago. However, when I fire up `gpd` and open the app in my browser, I get the error message: 

Detected a GitPitch 3.0 slide deck
attempting to use 4.0 syntax.

According to the docs, this should allow me to view and edit legacy decks, correct?

**Browser (please complete the following information):**
 - Chrome

**Operating System (please complete the following information):**
 - Linux

**Comment by gitpitch** [comment]
Hi Chris, 

> According to the docs, this should allow me to view and edit legacy decks, correct?

Yes, correct. You took the right steps by activating that property so I'll need to investigate. 

Is your 3.0 deck available in a public repo somewhere I can access it for testing? If not can you at least share the `PITCHME.md` with me here as an attachment to this thread or email it to me if neither of the other options suit. 

Cheers, David.

**Comment by fonnesbeck** [comment]
Thanks, David. Here is the project I was attempting to resuscitate: https://github.com/fonnesbeck/neurips_2018_talk

**Comment by gitpitch** [comment]
OK, so I just cloned your repo, activated the `gitpitch : 3.0` setting in the `PITCHME.yaml` for the default deck and then opened it in the new Desktop 4.0 app. And it all seems to work as expected. Here's a screenshot of what I'm seeing here:

<img width="1337" alt="chris-30-deck" src="https://user-images.githubusercontent.com/19169584/95790889-264d4700-0cd8-11eb-81d1-f393729e571a.png">

Can you send me the updated `PITCHME.yaml` file that you are using to test with the new 4.0 desktop app?

**Comment by fonnesbeck** [comment]
I'm just using the yaml file in the repo, with `gitpitch : 3.0` at the top. I get the following when I attempt to open the markdown file from the app running at localhost:9000

![image](https://user-images.githubusercontent.com/81476/95791476-0e110400-0ca7-11eb-8cb9-9a20fa7521b0.png)

[Here's the modified file](https://drive.google.com/file/d/119ijenKhMZNPATpFya1YZNlXc7ERShDB/view?usp=sharing)

**Comment by gitpitch** [comment]
Hmm, I just used your `PITCHME.yaml` file here and again it worked as expected. Can you show me the console output in your shell where you launched the deskop app. It will show me what services are running and also the exact build date of the image you are using. Thanks.

**Comment by gitpitch** [comment]
Chris, I think I might understand what the issue is here. By any chance are you using the Desktop 4.0 trial edition software??? That software is for testing out 4.0 functionality. You can not use the 4.0 trial app to work on old 3.0 decks.

To view and edit legacy decks you'll need the fully featured Desktop 4.0 app. Available [here](https://gitpitch.com/pricing). Tomorrow I'll take a look at updating the message displayed in the trial edition to make this clearer.

**Comment by gitpitch** [comment]
> Yes, that's exactly it. I was just taking it for a spin to see if I want to subscribe. Thanks.

Got it. As you can see from the screenshot I shared above if you do purchase or subscribe you can use the new desktop app to maintain existing 3.0 decks. If you've any further questions just let me know.
