### ISSUE TITLE
The desktop app serves some URLs as localhost even when accessed remotely.

### ISSUE THREAD

**Issue by curtcox** [gitpitch/gitpitch#314]
**Describe the bug**
The desktop app serves some URLs as localhost even when accessed remotely.
![Screen Shot 2020-10-15 at 3 11 07 PM](https://user-images.githubusercontent.com/353568/96183453-7efd2980-0efc-11eb-8f73-e56efaff430a.png)

**To Reproduce**
1) Use the desktop app to deploy https://github.com/curtcox/practical-graphviz
2) Note the IP address of the machine running the desktop app. Let's say: 192.168.0.105
3) Access the presentation from another machine on the local network http://192.168.0.105:9000/gitpitch/desktop/live#/

**Expected behavior**
The presentation should work like it does from localhost.

**Browser (please complete the following information):**
 - Chrome

**Operating System (please complete the following information):**
 - MacOS

**Additional context**
I think using the desktop app this way is fine by all involved, so I intend to add workarounds to this issue. I just wanted to state this explicitly to give you the chance to object, if doing so would violate the license agreement.

**Comment by gitpitch** [comment]
Issue moved to support.
