### ISSUE TITLE
GitPitch 4.0 Tutorials?

### ISSUE THREAD

**Issue by fonnesbeck** [gitpitch/gitpitch#315]
Are there additional tutorials or examples of the 4.0 features, particularly the grid layout details? I've been thorough the one in the docs but am still not able to reliably control the layout of my slides, particularly for text. I'm sure I just need to see more examples.

**Comment by gitpitch** [comment]
Hi Chris, the set of [grid-layouts guides](https://docs.gitpitch.com/#/grid-layouts/) are the full set of docs/tutorials/samples at the moment.

If you can tell me the kinds of slides and/or layouts you are trying to create I can help. Best if you can share a link to a sample deck with your efforts so far and describe the difficulties you are having on specific slides.

**Comment by gitpitch** [comment]
A quick bump for this thread. I just added an important update to 4.0. Check out the new [Grid Layouts Alignment Guide](https://docs.gitpitch.com/#/grid-layouts/alignment). It provides a simple solution to control the alignment [ `left`, `center`, `right` ] of content inside any layout block. Including text content, so this *might* be relevant on this thread.

To use this new functionality you will need to pull the latest desktop app image. Download instructions are found [here](https://docs.gitpitch.com/#/desktop/download).

@fonnesbeck I'm still interested in understanding specifics about the types of slides you found difficult to create. So if you have a sample deck you can share I'm happy to take a look.

**Comment by fonnesbeck** [comment]
Here's a simple example of where I'm getting confused. I have a title page with a title, subtitle and my name. Here is a simple slide:

```
[drag=100, drop=left]
# **Title**

## **Subtitle**

#### **Chris Fonnesbeck**
```
What I would have expected is a title that starts at coordinate 0, 0 and has 100% of the slide to work with. Instead, all three are centered:

![image](https://user-images.githubusercontent.com/81476/96464508-83bc2900-11ed-11eb-86ec-6a6d2ff0762d.png)

(BTW, also see the footnote at the bottom of the slide, which I deleted from the markdown document, but still appears on the slide -- that's another issue).

So, I then try:

```
[drag=100, drop=left]
# **Title**

## **Subtitle**

#### **Chris Fonnesbeck**
```

thinking this would surely left-align everything, but all the text is still centered. So its clear that I am just not understanding what needs to be done here.

Thanks in advance. I will check out your new grid layouts alignment guide.

**Comment by fonnesbeck** [comment]
For context, I am coming from Deckset as my main presentation tool. I found its layout syntax very easy to use and control. It seems like GitPitch offers even more fine-grained control, but I'm finding the learning curve very steep.

**Comment by gitpitch** [comment]
Chris, you seem to be missing the fundamentals of the drag and drag layout system:

1. You drag to size `[drag=width height]` a layout block.
2. You then drop to pin that layout block at an `[drop=x y]` position on your slide.

The `drop` property seems to be what you're not understanding clearly. The `drop` property **does not control alignment within a block**.

> You can see the [grid alignment guide](https://docs.gitpitch.com/#/grid-layouts/alignment) I just linked to earlier to understand how to override the default `center` alignment within a block.

I recommend you go back and read through the [Grid Layouts Drag-and-Drop Guide](https://docs.gitpitch.com/#/grid-layouts/drag-and-drop) one more time. In particular I'd pay careful attention to the use of  the `drop` property in the examples on that page.

In the examples you shared you are using `drag=100` which means your layout block is the full size of the slide. You should try sample values on `drag` smaller than `100` and then try to `dropping` your sample blocks around the slide. Once you "see it" I think you'll get it.

> BTW, also see the footnote at the bottom of the slide, which I deleted from the markdown document, but still appears on the slide -- that's another issue

Are you sure that this text is not activated by a [footnote](https://docs.gitpitch.com/#/settings/footnote) setting in the PITCHME.yaml for your slide deck?

**Comment by gitpitch** [comment]
Hi Chris, just checking in to see if you had a chance review the layout and new alignment guide and if so have you made any progress?

**Comment by fonnesbeck** [comment]
I have not yet, no. I'm on a bit of time pressure with my current slide deck, so I am using DeckSet since I am more familiar with it. I will take the time and try to learn the syntax better for my next one.

**Comment by gitpitch** [comment]
Ok, no problem. I'm going to close out this thread as it seems to have run it's course. For support questions you can email directly anytime. And good luck with your upcoming presentation. Cheers, David.
