### ISSUE TITLE
@ul[list-fade-bullets]: Support for showing all list items as faded but only the current one highlighted

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#316]
**Is your enhancement suggestion related to a problem? Please describe.**
Using `@ul[list-fade-bullets]` it hides any future list entries and fades any previous entries (good). In some cases I'd like to show all list entries and then highlight only the active one. 

For example suppose I have a list such as:

```
- one
- two
- three
```

Upon start of the slide all 3 items would be displayed where only `one` would be "highlighted` and `two` and `three` would be greyed out. Then when I move to `two`, `one` and `three` are greyed out.

**Comment by gitpitch** [comment]
Fragment behavior in general including fragment behavior of the [list widget](https://docs.gitpitch.com/#/lists/widget) precludes showing "future" items before they are presented. So this RFE can not be supported as described.

But you can approximate what you describe using one static list and one dynamic list as follows:

```markdown
[drag=100, drop=center]
@ul[opacity=0.25](false)
- One
- Two
- Three
@ul

[drag=100, drop=center]
@ul[list-hide-fragments]
- One
- Two
- Three
@ul
```

This markdown snippet works as follows:

1. Both lists must be *dropped* at the exact same location on the grid.
2. The first list is static and uses the `opacity` property to fade all of the list items.
3. The second list is dynamic (default behavior) meaning you can step through it
4. Using the `list-hide-fragments` to show one and only one item at any one time.
5. The single item in-focus is highlighted while all other visible list items are faded.

I believe this combination will get you as close as you can get to what you want. If you try it out let me how it goes.

**Comment by gitpitch** [comment]
If you have additional questions or feedback feel free to re-open this thread. Workaround provided. Closing RFE.
