### ISSUE TITLE
Gitpitch Cloud issue after 4.0 upgrade

### ISSUE THREAD

**Issue by martindsouza** [gitpitch/gitpitch#317]
**Describe the bug**
I've upgraded my slides from 3 to 4.0. 

Repo URL: https://github.com/martindsouza/pres-apex-social-login

When I go to https://gitpitch.com/martindsouza/pres-apex-social-login/master#/ then I get the upgrade notice.

Note that I have this presentation working on Gitpitch desktop.

**Comment by gitpitch** [comment]
To publish a 4.0 slide deck within a public repository you will need to follow the publishing guidelines that are detailed in the [Publish Public Slide Decks Guide](https://docs.gitpitch.com/#/cloud/public-slide-decks).

**Comment by martindsouza** [comment]
Perfect. Issue was missing `gitpitch : 4.0` reference in `PITCHME.yaml`
