### ISSUE TITLE
Allow embed of a user's Google Analytics Code into a Presentation

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#32]
If possible, this would be really useful for tracking.

**Comment by gitpitch** [comment]
Hi @terrywbrady I've just added experimental support that should give you the ability to use your own Google Analytics account to track your GitPitch presentations. All you need to do is add a new `gatoken` property to the `PITCHME.yaml` for your presentation. For example:

```
gatoken : 1A2B3C4D5E
```

Where `1A2B3C4D5E` should be replaced with your own GA token code. Once this token is made available GitPitch will use it to register with GA when rendering your presentation. Typically it takes a day or so for GA to start displaying initial viewing statistics. 

This functionality is now live. Can you please let me know if everything works as described.

**Comment by terrywbrady** [comment]
@gitpitch , I can now see the events in the GA console.  This is looking good to me!

**Comment by gitpitch** [comment]
Excellent. GA support is now [documented on the Wiki](https://github.com/gitpitch/gitpitch/wiki/Google-Analytics).

**Comment by terrywbrady** [comment]
@gitpitch , thank you for generating the documentation.  I am going to reference this in my yaml files to make it clear that cloners should update the id.

I have a couple suggestions for the wiki page.

In your example, consider making your example code look like a GA code.  "UA-1111111-1".

Provide instructions for setting up a property in GA.
* Log into Google Analytics
* Create a new property
* Provide "https://gitpitch.com" as a URL
* Add the generated tracking id to your PITCHME.yaml

**Comment by gitpitch** [comment]
Thank you @terrywbrady great suggestion. The [Wiki](https://github.com/gitpitch/gitpitch/wiki/Google-Analytics) has been updated.

**Comment by terrywbrady** [comment]
@gitpitch , I am seeing the following warning in GA.  I wonder if some additional refinement is needed.

The default URL https://gitpitch.com, for property UA-89672351-2 has no tracking code for this property, although it does have tracking codes for other properties:
UA-80973712-1
If your Tracking ID and your Default URL setting are out of sync, you don't get valid data in your Analytics account for the Default URL.

Either update the tracking code to use the Tracking ID for property Git Pitch Presentations, or open the Property Settings to update the Default URL for property Git Pitch Presentations to be https://gitpitch.com.

**Comment by gitpitch** [comment]
@terrywbrady not sure what steps need to be taken if any. That's the GitPitch tracking code and having looked at that GA account there is no indication of any problem and the daily analytics numbers seem to be active and current.

Are you still getting accurate analytics on your own presentations?

**Comment by terrywbrady** [comment]
@gitpitch , using inspect mode in Chrome for my presentation and searching for "UA-", I actually see evidence of 3 different tracking codes:

UA-80973712-1
UA-89672351-2
UA-1244922-8

I seem to be getting valid analytics in spite of the issue.

**Comment by gitpitch** [comment]
@terrywbrady just fyi, that's the GitPitch token, your token, and a token used by the [Share feature](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Sharing) plugin so this all looks correct.
