### ISSUE TITLE
mchem for MathJax

### ISSUE THREAD

**Issue by 0187773933** [gitpitch/gitpitch#321]
would it be possible to add mchem https://mhchem.github.io/MathJax-mhchem/ into the @math blocks?

**Comment by gitpitch** [comment]
This is not possible today and unlikely to be available anytime soon. Loading these kinds of extensions are not a clean fit for current MathJax support within GitPitch. If I ever upgrade to MathJax 3.x I will look again to see if support for extensions like `mhchem` could be incorporated.  For now, if you used Mathjax/mhchem externally and could export your equations as image files that would probably be the only way to display these types of formulas on your slides.
