### ISSUE TITLE
Can't view downloaded html decks.

### ISSUE THREAD

**Issue by sogaoh** [gitpitch/gitpitch#326]
**Describe the bug**
Can't view downloaded html decks.

**To Reproduce**
1. open http://localhost:9000/gitpitch/offline/publishing?p=my-branch#/ on browser.
2. Do `Generate HTML`. -> Download PITCHME.zip
3. Extract PITCHME.zip and open PITCHME/index.html on browser.

**Expected behavior**
Show my-branch deck.

**Screenshots**
<img width="720" alt="スクリーンショット 2020-12-01 19 18 56" src="https://user-images.githubusercontent.com/2090887/100728382-d737ae80-340a-11eb-9f6b-b630e6ea53c2.png">

**Browser (please complete the following information):**
 - Chrome

**Operating System (please complete the following information):**
 - MacOS

**Additional context**
None

**Comment by gitpitch** [comment]
Hi Hisashi,

It looks like you are trying to open the `index.html` file directly. What you need to do is open the `index.html` file _under a local web server_. You can find details for how to do that in the documentation.

See the following sections in the **Desktop Offline Publishing Guide** for details:

1. [Preview HTML](https://docs.gitpitch.com/#/desktop/publishing?id=preview-html)
2. [Deploy HTML](https://docs.gitpitch.com/#/desktop/publishing?id=deploy-html)

If you try this let me know how it goes.

**Comment by sogaoh** [comment]
Thanks for telling me. I understand.
I'll try to think of a way to do an effect like gitpitch.com.
