### ISSUE TITLE
GitPitch Is Shutting Down on March 1, 2021

### ISSUE THREAD

**Issue by RoyiAvital** [gitpitch/gitpitch#328]
Hello,

The documentation says:

> GitPitch is shutting down on March 1, 2021. The trial software is no longer available for download.

What does it mean? Is it about the desktop or the online service?

**Comment by gitpitch** [comment]
Hi Royi,

> What does it mean?

I'm shutting down the business on March 1, 2021. That means the end. No more service or software.

**Comment by RoyiAvital** [comment]
So both the online and the desktop application won't be available anymore, right?

Too bad, it is a great service!

**Comment by gitpitch** [comment]
> So both the online and the desktop application won't be available anymore, right?

Exactly right.

Cheers, David.
