### ISSUE TITLE
Allow per-slide custom CSS?

### ISSUE THREAD

**Issue by hq6** [gitpitch/gitpitch#34]
Currently, if I want to have a custom style for all `<h1>` tags *on a particular slide*, I must use inline-HTML for all `<h1>` tags, such as the following.

```
<h1 style="text-transform:none;">This is one place where I want h1 without text-transforms.</h1>
<h1 style="text-transform:none;">This is another place where I want h1 without text-transforms.</h1>
```

I tried the following, but it appears to do nothing.

    <style>
    h1 {
    text-transform:none;
    }
    </style>
    #This is one place where I want h1 without text-transforms
    #This is another place where I want h1 without text-transforms

Is there some other syntax that allows me to specify style in a general way?

If so, I'd love to know what it is.
If not, I'd like to make that a feature request.

I have seen [this page](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) but it appears to be changes across the entire slideshow rather than an individual slide.

**Comment by gitpitch** [comment]
Using the [custom css](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) feature provided by GitPitch gives you the ability provide a custom style that applies to all slides presentation wide. As discussed in #35 the key to custom styling is to ensure that your custom CSS targets the elements correctly.

If you want to use a custom style on a specific slide that differs from your presentation wide styling, you will need to use inline-styling on [individual HTML elements](https://github.com/gitpitch/gitpitch/wiki/HTML-Slides).
