### ISSUE TITLE
theme-override not working?

### ISSUE THREAD

**Issue by hq6** [gitpitch/gitpitch#35]
For [my repository](https://github.com/hq6/Thesis_Proposal), it appears that [custom CSS](https://github.com/hq6/Thesis_Proposal/blob/master/assets/css/style.css) is being entirely ignored.

I followed in the instructions in the Wiki to the letter, as far as I could tell.

Based on the rendered HTML, reproduced below, it looks like there are many opportunities for Javascript to change the style after it is included, so my best guess is that this is a bug.

```
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport">
    <title>[ GitPitch ] hq6/Thesis_Proposal/master</title>
    <meta content="Markdown Presentation powered by GitPitch." name="description">
    <meta content="GitHub, GitLab, Bitbucket, Markdown, Slideshow, Presentation, Developers, PITCHME" name="keywords">
    <link rel="icon" href="https://d1z75bzl1vljy2.cloudfront.net/img/favicon.ico">
    <link href="https://d1z75bzl1vljy2.cloudfront.net/reveal.js/3.3.1/css/reveal.css" rel="stylesheet" type="text/css">
    <link href="https://d1z75bzl1vljy2.cloudfront.net/reveal.js/3.3.1/css/theme/white.css" rel="stylesheet" type="text/css">
    
    <link href="https://d1z75bzl1vljy2.cloudfront.net/highlight.js/9.6.0/hybrid.css" rel="stylesheet" type="text/css">
    <link href="https://d1z75bzl1vljy2.cloudfront.net/octicons/3.5.0/octicons.css" rel="stylesheet" type="text/css">
    <link href="https://d1z75bzl1vljy2.cloudfront.net/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <style>
        .reveal .speaker-notes {
            background-color: #2a76dd;
            opacity : 0.7;
        }
        .centered {
            display: flex;
            justify-content: center;
            align-items: center;
            font-size:1.3em;
            font-weight: bold;
        }
    </style>

    
    <style>
    h1, h2, h3, h4, h5 {
    text-transform: none;
}

    </style><script type="text/javascript" src="https://d1z75bzl1vljy2.cloudfront.net/reveal.js/3.3.1/plugin/markdown/marked.js"></script><script type="text/javascript" src="https://d1z75bzl1vljy2.cloudfront.net/reveal.js/3.3.1/plugin/markdown/markdown.js"></script><script type="text/javascript" src="https://d1z75bzl1vljy2.cloudfront.net/reveal.js/3.3.1/plugin/highlight/highlight.js"></script>
```

**Comment by gitpitch** [comment]
Hi @hq6 your custom CSS needs to override the default style for the specific elements you are interested in changing. So for example, here is a snapshot of dev tools inspecting your current slideshow:

![style](https://cloud.githubusercontent.com/assets/19169584/21707300/d8f4c99c-d400-11e6-9a65-6ce7c7214f32.png)

Note on the right hand panel the `Styles` tab indicates that the `<h1>` has a CSS class of `.reveal`. So to override the style on this element you must identify it accurately within your custom CSS file. For example:

```
.reveal h1 {
    text-transform: none;
}
```

This should give you the effect you want.

**Comment by hq6** [comment]
Thanks! I wasn't too familiar with reveal.js and didn't realize it was adding CSS classes to my elements in JS.
