### ISSUE TITLE
For code snippets, consider binding an event that will select all of the text within the code box

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#36]
I have a presentation with lots of code samples that I will be copying and pasting into an IDE.

It would be cool if I could easily add the code blocks to my clipboard in presentation mode.

Perhaps this behavior could be bound to a focus, click, or double-click event on the pre element.

**Comment by gitpitch** [comment]
@terrywbrady experimental support for selecting code within code blocks is now live.

The `s` key (`s` for `select`) has been bound for slides. If you press `s` on a slide that is displaying a [code block](https://github.com/gitpitch/gitpitch/wiki/Code-Slides) the text of that code block will be auto-selected in your browser. You can then use the standard keys `Ctrl-C` or `Cmd-C` to copy the selected text to your clipboard and then paste it wherever it needs to go.

Note, to deselect the code in your code block click anywhere outside of the code block on your slide. Deselecting should reactivate the syntax highlighting of your code block.

I've tested this on my local versions of Firefox, Chrome and Safari and it works but your feedback following your own testing appreciated. This feature is live on [gitpitch.com](https://gitpitch.com) but is pending feedback before being merged into `master`.

**Comment by terrywbrady** [comment]
@gitpitch , this works great.  Thank you!  

Fyi, the keyboard shortcut is not yet on the shortcut help menu.

I tested in Chrome, IE, and Firefox on Windows and in Safari on MacOS.

**Comment by gitpitch** [comment]
@terrywbrady  Quick update to this old thread. Due to the recent introduction of the new [Speaker Notes](https://github.com/gitpitch/gitpitch/wiki/Speaker-Notes-Window) feature the key binding to select code within code blocks on a slide has been changed from the 's' key to the 'x' key. The new speaker notes feature has taken over the 's' key. Just fyi.

**Comment by terrywbrady** [comment]
@gitpitch , thanks for the alert.  Could you update the on-screen help info for keyboard shortcuts to reflect this change?  I still see the old documentation for the "s" key.

**Comment by gitpitch** [comment]
Re-opening this issue as a reminder to myself that the on-screen help needs to be updated to reflect speaker-note and copy-code key changes.

**Comment by gitpitch** [comment]
Quick update. GitPitch has just been updated to use reveal.js 3.5.0 (from 3.3.x) as the default dependency for presentation rendering. As part of this change I have updated the in-presentation Help (?) screen to include:

- PgUp and PageDown keys for previous and next navigations
- Shift key navigations to skip slide fragments
- X key to select source within code blocks 

If you are currently overriding the default `revealjs` version in your `PITCHME.yaml` for existing presentations and now want to avail of this latest update, please remove that override property for existing presentations. Naturally, all new presentations will use the new default by default :)

Now closing this issue as resolved.

**Comment by terrywbrady** [comment]
@gitpitch , thank you for fixing this and for the reminder to update my PITCHME.yaml files.  I continue to find the service very useful!
