### ISSUE TITLE
Fullscreen option is not working in IE

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#38]
I was testing a separate issue in multiple browsers and I noticed that the fullscreen "f" keyboard shortcut is not working in IE 11.  It works fine in Chrome, Safari, and Firefox.

I am running IE 11.0.9... on Windows 7 Enterprise.

The other keyboard shortcuts seem to work in IE.

I see the following error in my IE Console when loading a presentation.

> SCRIPT5007: Unable to get property 'style' of undefined or null reference
File: reveal.js, Line: 1, Column: 9353

**Comment by gitpitch** [comment]
@terrywbrady have you been using the fullscreen `f` keyboard shortcut successfully on IE 11.0.9 prior to  the latest patch being pushed to adds support for code block selection? I'm trying to understand if this is a new problem somehow introduced by that latest patch.

**Comment by terrywbrady** [comment]
@gitpitch , sorry that I missed your question. I do not use IE regularly, so I cannot tell if it is a new issue or not.  Let me know if you have something you need me to test out further.

**Comment by gitpitch** [comment]
Hi @terrywbrady as I don't use or have access to IE myself it would be very helpful if you could run some quick tests on IE.

1. Can you clear cache on IE and again test and verify that the problem you reported occurs.

2. Can you clear cache again and then try opening your test presentation in IE using my `staging server` in place of `gitpitch.com`:

```
http://212.47.246.121/your-git-username/your-git-repo/your-git-repo-branch
``` 

The staging server is running a slightly older version of the GitPitch server without the latest patch for `s` for code block selection. I'd like to know whether you still see the script error in your javascript console on this server. Based on your results it will help identify if this is a longstanding problem on IE or a new problem on IE introduced by the new patch that gave us code block selection.

Thanks.

**Comment by terrywbrady** [comment]
@gitpitch , I gave it a try and the "f" button does not work.

I do not get the console error listed above when I run it off of your server.

I see some warning messages about a style attribute.

    <a href="#popupTheme" role="button" data-toggle="modal-popover" data-placement="top"><i
                                class="fa fa-paint-brush" aria-hidden="true"> <span style="font-family: Helvetica Neue"
                                                                                    ,Helvetica,Arial,sans-serif;">Theme</span>

**Comment by gitpitch** [comment]
@terrywbrady it looks like you may have hit upon a number of problems under IE. None of which I'm in a position to debug or fix at this time. If you want to submit a patch yourself please feel free to do so. For now, as a simple workaround exists (install and use an alternate browser like Chrome), I'm going to close this issue as will-not-fix.
