### ISSUE TITLE
Add Python 3 snippet to Slideshow Offline wiki page

### ISSUE THREAD

**Issue by nnadeau** [gitpitch/gitpitch#39]
- Wiki page: https://github.com/gitpitch/gitpitch/wiki/Slideshow-Offline
- Python 3 snippet: `python3 -m http.server`

**Comment by gitpitch** [comment]
Note added to [Slideshow Offline](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Offline) page per your recommendation. Thanks.
