### ISSUE TITLE
pdf math conversion error

### ISSUE THREAD

**Issue by lwdye** [gitpitch/gitpitch#40]
Great project!  Converting kitchen-sink example to pdf fails to render math example correctly.

**Comment by gitpitch** [comment]
Hi @lwdye thanks for reporting this problem. I believe the impact of async loading multiple videos within the `kitchen-sink` sample presentation may be interfering with font loading during PDF generation.

If you use [math formulas](https://github.com/gitpitch/gitpitch/wiki/Math-Notation-Setting) in your own presentation I believe they will print just fine. For example, here's a demo presentation on [gitpitch.com](https://gitpitch.com/gitpitch/feature-demo/mathjax) that you should be able to view and print:
 
```
https://gitpitch.com/gitpitch/feature-demo/mathjax
```

If you try this out, please let me know how you get on.
