### ISSUE TITLE
gitlab etc support not clearly documented and possible improvement

### ISSUE THREAD

**Issue by lwdye** [gitpitch/gitpitch#41]
Given me/foo on gitlab with PITCHME.md and me/* on github fails to find project.   The following works

https://gitpitch.com/user/project/branch?grs=gitlab

It appears you first check github.  If you fail perhaps continue to gitlab etc.  If me/foo on both gitlab and github perhaps this should be an error and force explicit call.

**Comment by gitpitch** [comment]
I've added a new [Supported Git Services](https://github.com/gitpitch/gitpitch/wiki/Supported-Git-Services) page to the Wiki that explains how GitPitch is capable of talking to a number of Git services and how you as a user have two choices for how you can can tell GitPitch which service you want it to talk to.
