### ISSUE TITLE
Should Arrow Keys Advance Slides Containing Transitions?

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#42]
I have a presentation with several HSLIDES and VSLIDES.

I have also added bullet transitions to several of these slides.

I notice that the arrow keys always trigger the bullet transitions.

Would it make more sense for the arrow keys to always advance to the next/prev slide disregarding any active bullet transitions on a page?

**Comment by gitpitch** [comment]
If the primary navigation keys (arrow keys) didn't trigger [slide fragments](https://github.com/gitpitch/gitpitch/wiki/Fragment-Slides) how would they be triggered?

What is the nature of the problem you are facing? Are you concerns related to speed of navigation? You can easily drop into [overiew mode](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Overview-Mode) and rapidly navigate to any slide in your presentation. Or is it something else?

**Comment by terrywbrady** [comment]
@gitpitch , My thinking was spacebar for primary advance (slide or bullet) and the arrow keys for a full slide advance.

I am testing a presentation with several bullet transitions, which brought the question to my mind.

The overview mode works great for me.  This is definitely not a necessity, just an idea to bounce off of you.

**Comment by gitpitch** [comment]
Thanks @terrywbrady for the clear use case. I like this idea. Although I would probably prefer adding new keyboard controls for this functionality, something like `Shift-Left` and `Shift-Right` to skip over fragments to the next slide. In theory this would allow us to add new behavior while preserving existing behavior.

First look suggests this would require a fork of the underlying `reveal.js` library as I do not see the public event hooks I would need in the current API. I'll try and see if there are any alternative approaches and will let you know if I find anything that might give us what you need. For now, the best/only option is overview mode.

**Comment by gitpitch** [comment]
Hi @terrywbrady as part of a larger upgrade for GitPitch I've included a patch that should give you a way to enjoy faster navigation by skipping over fragments on slides. Once you activate this upgrade you should be able to press `Shift-Left` or `Shift-Right` to skip over fragments on a slide when navigating. Simply using the `Left` and `Right` keys without the `Shift` key still gives you the current behavior.

To apply the upgrade and activate the patch you will need to add one new property to the `PITCHME.yaml` for your presentation:

```
revealjs-version : 3.4.1
```

Adding this property will do two things:

1. It will update the [reveal.js](https://github.com/hakimel/reveal.js) library dependency for your presentations so you are using the latest and greatest including many rendering bug fixes
2. It will pick up a patch I've added that supports the new `faster-navigation` feature described above.
3. The `Help` menu activated by pressing `?` has been updated to reflect these new navigations.

P.S. I'm working towards making reveal.js 3.4.1 the new default for GitPitch presentations but for now you need to activate it as described above. When it eventually becomes the new default I will provide a `PITCHME.yaml` option that lets you revert to the original 3.3.1 release if for any reason you experience problems with the updated release.

As always, your feedback is very much appreciated.

**Comment by terrywbrady** [comment]
@gitpitch , the shift left and right work beautifully for me.  Thank you for making this change.

Shift down arrow also works for me.  The shift up arrow does not seem to advance a full slide as the shift down does.

To complete testing, I also tried using the h, j, k, l and shift h, j, k, l keys.  I think that this enhancement may have broken the behavior of the j key when 3.4.1 is active.

**Comment by gitpitch** [comment]
Thanks @terrywbrady for your testing and feedback. I've just pushed a small patch that will hopefully resolve each of the issues you raised:

1. `Shift-Up` now advances over slide fragments.
2. The `j` key behavior is fixed.

 Let me know how it goes.

**Comment by terrywbrady** [comment]
@gitpitch , I did a quick test and this is working as expected.  Thank you
