### ISSUE TITLE
https://gitpitch.com/user/repo/branch/file.md so i can have more slideshows in one repo

### ISSUE THREAD

**Issue by freddi301** [gitpitch/gitpitch#52]

**Comment by gitpitch** [comment]
Hi @freddi301 see the [Asset Sharing](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing) page in the Wiki to learn how you can work with multiple slideshows in a single repo.

**Comment by freddi301** [comment]
Consider to mention this in the section of usage in main page.
Thank you :smile:

**Comment by gitpitch** [comment]
Great suggestion, thanks @freddi301. I've just added a note to the [main page in the Wiki](wiki#gitpitch-bonus-feature) highlighting feature support for sharing assets (css, images, etc) across multiple presentations in a single git repo.
