### ISSUE TITLE
Custom logo div should have a "logo" class for custom styling

### ISSUE THREAD

**Issue by sammoorhouse** [gitpitch/gitpitch#53]
I'd like to specify "logo: my_project_logo.png" in my PITCHME.yaml, then be able to style the logo. Currently this is difficult because there's no id or class associated with the image.

I have a simple change building locally if you'd like me to push it somewhere.

**Comment by gitpitch** [comment]
Hi @sammoorhouse I've just pushed a patch 6b578c94f9fd4d14811fadbb9a05c76e1b8594a5 so the logo div now has an id named `gp-logo`, as follows:

```
<div id="gp-logo" style="...">
    <img src="..."/>
</div>
```

You can target this new id with your custom css. Patch is live on [gitpitch.com](https://gitpitch.com).

**Comment by sammoorhouse** [comment]
Thanks @gitpitch! I'll take a look.
