### ISSUE TITLE
Don't make expand src when inside ```

### ISSUE THREAD

**Issue by dukedave** [gitpitch/gitpitch#55]
Don't expand `src` attribute path to absolute path, when it occurs in side ` ``` `.

It seems that the path for a `src` is being expanded to include `https://raw.githubusercontent.com/...` even when it occurs inside a ` ``` ` block.

This means my sample code showing:

```
<img src="myfile.png">
```

Actually gets expanded to this when displayed in a slide:

```
<img src="https://raw.githubusercontent.com/dukedave/my-repo/master/myfile.png">
```

**Comment by gitpitch** [comment]
Hi @dukedave thanks for reporting this issue.

I have a simple workaround for you. Just add a single space (or tab) before your HTML <img/> tag in your code block. For example, here is what you currently have:

```html
<vue-webcam ref='webcam'></vue-webcam>
<img src="photo">
<button type="button" @click="take_photo">Take Photo</button>
```
And here is the same content but each line in your code block has been slightly modified. An extra space character added at to the start of each line:

```html
 <vue-webcam ref='webcam'></vue-webcam>
 <img src="photo">
 <button type="button" @click="take_photo">Take Photo</button>
```
Your code block should now appear as expected, rendering in your presentation as follows:

![html-tags](https://cloud.githubusercontent.com/assets/19169584/24892980/8ae3ae4a-1eaa-11e7-9f66-6d8748ef22d4.png)

If you try this out let me know how it goes.

**Comment by dukedave** [comment]
@gitpitch great, that works, thanks for the quick reply.
