### ISSUE TITLE
Enter Full-screen using mouse, too

### ISSUE THREAD

**Issue by light2yellow** [gitpitch/gitpitch#57]
I use Vimium (this is a browser plugin) and it maps `f` to a particular task. Thus, there's no way for me to go full-screen without disabling this plugin. I suggest making the `[ Fullscreen:  Press F ]` text a clickable button.

**Comment by VictorTomaili** [comment]
Same issue, Shortcuts must be usable with a mouse too. I use vimium too.

**Comment by gitpitch** [comment]
Thanks for the feedback. I'll need to give this some thought to decide how best to deliver this kind of support but I do understand the issue. I'll update this thread when I know more.

**Comment by bernardobelchior1** [comment]
I support this issue. 
Your slides are beautiful on a phone, but there is no way to make them full screen. 
A fullscreen button would not only be great for Vimium, but for smartphones as well.

**Comment by gitpitch** [comment]
I've been thinking about this and would like to request some additional feedback from everyone.

Vimium users, imagine I provided a link or menu to allow you enable Fullscreen mode. How would you then exit from a full screen mode if you are navigating solely by mouse? Keep in mind that in Fullscreen mode there can be no links or menus to help you exit Fullscreen mode. So basically, how would you expect to mimic the hitting of the Escape key using only your mouse? I haven't used Vimium so I may well be missing something simple but I'd like to know if we go down this path that it is not a cul-de-sac.

Same question for smartphone users. What is the equivalent of hitting the Escape key when viewing on a smartphone? Again keep in mind that in Fullscreen mode, by definition there can be no links or menus to help you exit Fullscreen mode.  So I'm trying to understand how you might exit from Fullscreen mode if I provided a way to enter that mode on mobile.

In a traditional desktop browser, exiting Fullscreen mode is always availble using the Escape key.

**Comment by VictorTomaili** [comment]
How about html5 full-screen feature? Its works with links and on mobile phone too

**Comment by light2yellow** [comment]
With Vimium one exits fullscreen with Esc. Phones are the whole other story, this issue is not about them, it's about desktop keymap being the only way to do things.

You might also consider another clickable element in fullscreen mode to appear when the mouse activity is registered.

**Comment by VictorTomaili** [comment]
Mobile phones will be in this case because links are clickable on phones too. Also, mobile phones never stucks in fullscreen mode. Back button always works as esc key.  In this case, we need only fullscreen link on shortcut label. It's will be ok for all of us. There are too many websites uses fullscreen feature on mobile phones and web browsers. And they also have a link for fullscreen. 

Besides, I think it's possible to handle enter-exit fullscreen when double tapped on screen with mouse or touch.

**Comment by gitpitch** [comment]
Keyboard shortcuts: fullscreen, overview, and blackout are now all exposed as links in the main presentation window. Open any presentation and the links should appear in the bottom-left corner of the window.

While I have been able to test this in my own browser I have not been able to test with a mouse or using Vimium. So I would appreciate feedback from everybody once you have had a chance to test out this new functionality. Thanks.

**Comment by light2yellow** [comment]
`Fullscreen - Overview - Blackout` trio now works, however it'd nice if `Help` in the right bottom corner is made clickable too.

Otherwise, I consider this to be worked out and you can close the issue anytime.
