### ISSUE TITLE
Clicking right then pressing left on kitchen sink.

### ISSUE THREAD

**Issue by Y-Less** [gitpitch/gitpitch#58]
I was going through the kitchen sink example, clicking the right button all the way to the end.  When I got to the final page I instead pressed the left arrow key to go back and it didn't work.  If I press the right key from the penultimate page, the left key works.  If I click right on to any page not the last one then press left, the key works.  It is only clicking on to the final page then pressing off it that doesn't work.

I did some more testing, and this actually seems to happen on the final slides in any direction, and with any direction shortcut.

**Comment by gitpitch** [comment]
Hi @Y-Less thanks for the feedback. I just tried this in Chrome (57), Firefox (52), and Safari (10.1) and in all cases the navigation worked just fine.

To be clear, I used my touchpad mouse to click on the next-slide navigation icon moving right all the way to the final slide. Then when viewing the final slide, I used the keyboard left-arrow key to navigate back one slide to the penultimate slide. And it worked, no problem.

What browser were you testing in? If you tested in only one browser type, can you please try another browser and let me know what you find.

**Comment by gitpitch** [comment]
Closing as no further information provided and not reproducible.
