### ISSUE TITLE
Displaying images in GitPitch

### ISSUE THREAD

**Issue by koffisani** [gitpitch/gitpitch#6]
Please, can somebody let me know how to display successfully images in gitPitch ? Take a look at this PITCHME.md https://gitpitch.com/koffisani/github-rep-for-iai/pitchme

**Comment by gitpitch** [comment]
Hi @koffisani if you want to display an image on any slide and that images lives in the `img` directory within your git repo, you can just use a relative path to the image when you declare your image in your PITCHME.md markdown file. For example:

```
![Image](img/git.png)
```

I can see from your sample PITCHME.md that you are using absolute URLs to the blob. Try changing your markdown to use relative paths as indicated above.

See more details on working with image slides in the [GitPitch Wiki](https://github.com/gitpitch/gitpitch/wiki/Image-Slides).

**Comment by koffisani** [comment]
Thanks, @gitpitch. Right.
