### ISSUE TITLE
Improved syntax for fragments

### ISSUE THREAD

**Issue by larsbrinkhoff** [gitpitch/gitpitch#61]
There could possily be a more convenient syntax for fragments.

If you make heavy use of fragments in most slides, the markdown becomes bulky, e.g.:

    # Numbers
    - 1 
    - 2 
    - 3 

    ---

    # Letters
    - A 
    - B 
    - C 

    ---

    # Metavariables
    - Foo 
    - Bar 
    - Baz

**Comment by larsbrinkhoff** [comment]
A real-world example:

https://gitpitch.com/larsbrinkhoff/lbForth/pitch

**Comment by gitpitch** [comment]
Hi @larsbrinkhoff thanks for your feedback. You're absolutely right. So I've gone ahead and implemented a fragment syntax shortcut which should help. See the updated [Fragment Slides](https://github.com/gitpitch/gitpitch/wiki/Fragment-Slides) page in the Wiki. 

I've also prepared a fragment feature demo presentation so you can see this new syntax live, just open the following link in your browser:

```
https://gitpitch.com/gitpitch/feature-demo/frag-shortcut-syntax
```

As you will see, the new syntax for your sample presentation is now simply this:

```
# Numbers

- 1 |
- 2 |
- 3 |

---

# Letters
- A |
- B |
- C |

---

# Metavariables

- Foo |
- Bar |
- Baz |
``` 

Which is much more concise. And hopefully what you're looking for.

**Comment by larsbrinkhoff** [comment]
That's great, thanks!

**Comment by missmatsuko** [comment]
Is all the fragment syntax documented somewhere? I could only find [this page on markdown fragments](https://gitpitch.com/docs/markdown-features/fragments/), but it seems like it only works for lists.

**Comment by gitpitch** [comment]
You can turn almost any element on your slide into a fragment, using the `fragment` class. The doc you linked to only covers lists. But you are not limited using fragments with lists.

For example, see the *Markdown Fragments* [series of slides](https://gitpitch.com/gitpitch/kitchen-sink#/10) in the *Kitchen Sink*. It provides examples of using the `fragment` class with lists, images, and even table data. Check out the markdown for the *Kitchen Sink* presentation for details.

You can also apply the `fragment`  class on GitPitch [markdown shortcuts](xxx) like the `@fa` shortcut for Font Awesome icons, for example:

```
---

# Big smile...

@fa[smile-o fa-5x fragment]

```

This markdown snippet would cause the smiling icon to be treated as a fragment, appearing only after you step into the the slide.


Perhaps more importantly, you can also use the `fragment` class on any *snap-region* if you are using [snap layouts](https://gitpitch.com/docs/layout-features/snap-position-layouts/). For example:

```
---

@snap[west]
# Hello
@snapend

@snap[east fragment]
![](assets/img/world.png)
@snapend

```

This markdown snippet would cause the *world.png* image in the *east* snap-region to be treated as a fragment, appearing only after you step into the the slide.

It is a great feature and I definitely need to improve the docs to highlight it's flexibility and usefulness. And I will. Once I have something in place I will bump this thread to let you know.

**Comment by gitpitch** [comment]
Bump. The [Markdown Features](https://gitpitch.com/docs/markdown-features) guides have been updated. The newly revised doc includes comprehensive guides for working with *slide fragments* for list and non-list content. Plus details of exciting new **@box** and **@img** shortcut features. Enjoy.

**Comment by missmatsuko** [comment]
@gitpitch Thanks! I guess there's a lot of ways to do it!

I didn't see these other formats in the updated docs, are they valid too?

- The HTML comment format in the initial issue, `<!-- .element: class="fragment" -->`
- Pipe (|) as shown in [an earlier comment](https://github.com/gitpitch/gitpitch/issues/61#issuecomment-298177188)

**Comment by gitpitch** [comment]
> I didn't see these other formats in the updated docs, are they valid too?

The recommended formats are those documented [here](https://gitpitch.com/docs/markdown-features/fragments/) and [here](https://gitpitch.com/docs/markdown-features/list-fragments/). The pipe (|) and the HTML comment formats still work today, but have been deprecated.

**Comment by missmatsuko** [comment]
@gitpitch Thanks! Very helpful!
