### ISSUE TITLE
Is GitPitch for you? Sadly no..

### ISSUE THREAD

**Issue by mvdkleijn** [gitpitch/gitpitch#62]
The readme asks "Is GitPitch for you?". It then proceeds with the answer, the first part of which is "...To colleagues, clients or customers..."

I don't know how to put this differently, but most of my colleagues and clients use in-house hosted repositories. Usually gitlab or bitbucket server (non-saas) with non-public repositories due to legal or pci compliancy requirements.

Would it be possible to add support for:

- private repositories
- bitbucket on-premise (slightly different api unfortunately)

I'd love to introduce this to my colleagues and get them away from PowerPoint!

**Comment by gitpitch** [comment]
Hi @mvdkleijn I do not see GitPitch supporting private repos anytime soon. However if your colleagues, clients, or customers are using GitLab CE internally then they are in luck. They do not need to use the service on [gitpitch.com](https://gitpitch.com), I simply provide that service as a gift to the open source community.

Instead, they can host their own GitPitch server in-house and use that server to access presentations that only exist on their internal GitLab repos. Those presentations still have to live in public repos but those repos are in-house so not public-public.

The [documentation on the Wiki](https://github.com/gitpitch/gitpitch/wiki/Server-Deploy-Instructions) explains how to build, configure and deploy a private GitPitch server to communicate with a private GitLab CE server.

Based on prior communications there are already a number of private servers being used in-house by various organizations for exactly the reasons you have described.

I'm not familiar with what API changes are involved with the Bitbucket on-premise offering. If you can provide me with details on how it differs from the API on their public service then I may be able to look into adding support for that too.

**Comment by gitpitch** [comment]
Closing this issue for now as resolved.

**Comment by gitpitch** [comment]
A quick update on this thread regarding GitPitch private repository support. I've just announced GitPitch Pro. Coming soon. A subscription service that unlocks Git private repos to deliver public, private, and password-protected presentations and much, much, more. Read the following GitPitch [blog post for details](https://medium.com/@gitpitch/gitpitch-pro-coming-soon-bda8c71ca9ea).
