### ISSUE TITLE
How to generate offline files offline?

### ISSUE THREAD

**Issue by hu6360567** [gitpitch/gitpitch#63]
Hi,
   This project is amazing. I'd love to upload md to github repos, but I'd like to make every commit meaningful. Is there any way to generate web page before committing to github? So that, I would use gitpitch as a publish platform and keep git repo clean.

**Comment by gitpitch** [comment]
Hi @hu6360567 I'm glad you're enjoying GitPitch. I have two options for you.

#### Option 1: Develop GitPitch presentation content in a feature branch

Simply create a feature-branch and do all of your `busy` work in that branch. Then when you are happy with your final presentation `PITCHME.md` and associated assets, merge your feature-branch back into your master making sure to use a `squash` on the merge as follows:

```
git checkout -b presentation-dev-branch
#
# Now develop your presentation content in this branch, committing as often as you want
# Then when you are finished, do the following:
#
git checkout master
git merge --squash presentation-dev-branch
git add -A
git commit -m "Completed GitPitch presentation."
git push
```

This approach will keep your `master` log history clean, you will end up with only a single commit comment in your master log history for you presentation. And if you really want to you can always delete the feature branch you used for dev when you are satisfied you no longer need it. Just fyi, this is how I typically work with GitPitch.

#### Option 2: Use the GitPitch Offline Bundle as a Dev/Preview Environment

I've just created detailed instructions for this approach and added them to the GitPitch Wiki, [see here](https://github.com/gitpitch/gitpitch/wiki/Creating-Testing-Locally).

**Comment by hu6360567** [comment]
Great! Thanks!

**Comment by gitpitch** [comment]
Just fyi, I've also just added a [Clean Commit History](https://github.com/gitpitch/gitpitch/wiki/Clean-Commit-History) page to the GitPitch Wiki as it may be useful to others.
