### ISSUE TITLE
Support for task lists?

### ISSUE THREAD

**Issue by zombiefungus** [gitpitch/gitpitch#67]
Hi, It seems to be that

- [ ] checklists 

aren't showing as in github in gitpitch

Is there any plan to integrate them? (Is there any way for me to help with that?)

Thanks!

**Comment by gitpitch** [comment]
Hi @zombiefungus thanks for getting in touch. So GitHub task lists are not a feature of GitHub Flavored Markdown (GFM) they are a feature of the GitHub service itself. GitPitch renders GFM. So GitPitch will render lists and checkboxes just fine but you can not click on them like an interactive task list on GitHub. The syntax you are trying to use will appear in a presentation as follows:

![task-lists](https://cloud.githubusercontent.com/assets/19169584/25732635/09ef6628-317c-11e7-93e9-51c2a68660a2.png)

Some background here if you're interested. GitPitch uses [reveal.js](https://github.com/hakimel/reveal.js/) which in turn uses the [marked library](https://github.com/chjj/marked) for markdown rendering. To understand more you can look over [this issue](https://github.com/chjj/marked/issues/107) which has been opened to discuss adding GitHub task list support within marked. The thread explains the reasons it is not supported by a rendering library.

I do not feel there is a compelling case here to consider diverging from the core dependencies to support this feature in GitPitch. So I'm going to close this issue as will-not-fix.
