### ISSUE TITLE
Multiple presentations in one repo?

### ISSUE THREAD

**Issue by larsbrinkhoff** [gitpitch/gitpitch#69]
Is is possible to have more than one presentation in a repository, without branching?

**Comment by gitpitch** [comment]
Hi @larsbrinkhoff absolutely, take a look at the [Asset Sharing](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing) and [Modular Markdown](https://github.com/gitpitch/gitpitch/wiki/Modular-Markdown) pages on the GitPitch Wiki for details.

**Comment by larsbrinkhoff** [comment]
Great, thanks!
