### ISSUE TITLE
Latex subscripts with longer strings don't work as expected

### ISSUE THREAD

**Issue by rpappu** [gitpitch/gitpitch#70]
When we use longer strings in subscripts, rendering is incorrect. 

For example, 

$$ P_t = P_d + P_s + P_l$$

renders as intended, whereas

$$P_{total} = P_{dynamic} + P_{sc} + P_{leak}$$

Both of them render correctly in an online Latex previewer like http://quicklatex.com/.

**Comment by gitpitch** [comment]
Hi, do you have a sample presentation you can share that demonstrates the problem you've described?

**Comment by rpappu** [comment]
Here's the link to a sample presentation. 

https://gitpitch.com/rpappu/GitPitchTest

Slide 1 renders correctly, while Slide 2 does not.

Source is here.

https://github.com/rpappu/GitPitchTest

**Comment by gitpitch** [comment]
Hi @rpappu the issue is the use of underscores within your formula and its interaction with the Markdown preprocessor. Basically, you need to escape the underscores by changing:

```
$$P_{total} = P_{dynamic} + P_{sc} + P_{leak}$$
```
To this:

```
$$P\_{total} = P\_{dynamic} + P\_{sc} + P\_{leak}$$
```

Please try this out in your presentation and let me know how it goes.

**Comment by rpappu** [comment]
Yep...that works. Wasn't aware of the \-escape....I'll close this issue now. Thanks!
