### ISSUE TITLE
Offline PITCHME.zip file does not appear to include repo subdirectories

### ISSUE THREAD

**Issue by dougtoppin** [gitpitch/gitpitch#72]
In my repo I created an assets directory to hold images contained in the presentation. When I select Offline the PITCHME.zip file generated and downloaded does not appear to include my assets subdirectory and content. Should it be in there as well?

**Comment by gitpitch** [comment]
@dougtoppin can you provide a link to your presentation?

Any image dependencies that GitPitch finds within your presentation markdown should appear within the `assets/md/assets` directory when you expand the offline zip archive for your presentation.

If those assets are missing then you presentation would not render as expected. Is your presentation no rendering as expected offline?

**Comment by dougtoppin** [comment]
Repo is https://github.com/dougtoppin/presentation-splunk-docker
I checked the download and can see the PITCHME/assets/md/assets/ directory but nothing is in it.

**Comment by gitpitch** [comment]
I've just used gitpitch.com to down your presentation. When I expanded the offline bundle I could see the following files:

![archive-assets](https://cloud.githubusercontent.com/assets/19169584/26477397/9e9d8a92-41ef-11e7-8230-34472e971782.png)

The image assets dependencies for your presentation are clearly there. And the presentation itself renders as expected:
![presentation-offline](https://cloud.githubusercontent.com/assets/19169584/26477417/c3fe9588-41ef-11e7-8f26-a764a11b70ff.png)

As do the speaker notes:
![speaker-notes](https://cloud.githubusercontent.com/assets/19169584/26477423/cd3071da-41ef-11e7-9f2a-e5c307fbddfa.png)

It is hard to imagine what might be happening to prevent you seeing these same results. Can you tell me what is the exact size (bytes) of the offline bundle zip file you are seeing after a download?

Here is what I'm seeing for your presentation. We should be seeing the same.

```
 ls -slrt PITCHME.zip
8224 -rw-r--r--@ 1 david  david  4210670 May 26 08:39 PITCHME.zip
```

Can you try to download the offline bundle one more time and compare both the size and contents to what I've shown here. Then please let me know what you find.

**Comment by dougtoppin** [comment]
This is strange, I downloaded the offline pitch zip file maybe 3 times today and each time none of the assets files were in it. I just did it again a few minutes ago and they appeared. I do not have any explanation for it.
Sorry about the false report. Not sure what could cause it.

**Comment by gitpitch** [comment]
No problem @dougtoppin if you encounter anything unexpected please feel free to let me know anytime.
