### ISSUE TITLE
Vertical slide breaks the `data-background-transition=none` comment fragment

### ISSUE THREAD

**Issue by EvgenyOrekhov** [gitpitch/gitpitch#77]
Adding a vertical slide below the one that has a `data-background-transition=none` comment fragment makes GitPitch ignore that comment fragment.

Example presentation: https://gitpitch.com/EvgenyOrekhov/talks/gitpitch-transition-bug
Presentation's repo: https://github.com/EvgenyOrekhov/talks/tree/gitpitch-transition-bug

Browser: Google Chrome 59.0.3071.86
OS: Lubuntu 17.04

**Comment by gitpitch** [comment]
Hi @EvgenyOrekhov 

I need some additional clarification from you. 

### 1. Use PITCHME.yaml For Global Presentation Settings

I see you are using a  `PITCHME.yaml` where you are attempting to set a global `transition` property for your presentation. However, the syntax used in your `yaml` file doesn't look right, you appear to be using `json-object` syntax, not yaml syntax. The correct way to set the `transition` setting in your `PITCHME.md` is simply as follows:

```
transition : none
```

### 2. Use data-background-transition For Individual Presentation Slides

if you are using `PITCHME.md` to set the global `transition` setting for your presentation then it does not make sense to also add an explicit `data-background-transition=none` on an individual slide. Currently both settings (global and slide specific) in your current presentation are identical using `none`.

### 3. pressing -> should not cause a transition

If you do not want `transition=none` from your first slide to your second slide then you need to specify the `data-background-transition=none` **on your first slide**. That setting applies to the slide where it is defined. So currently your presentation behaves correctly as you have added the `data-background-transition=none` setting on your second slide.

**Comment by EvgenyOrekhov** [comment]
@gitpitch 

1. [YAML 1.2](http://www.yaml.org/spec/1.2/spec.html) is a superset of JSON, so any valid JSON is also a valid YAML. Changing JSON to YAML doesn't affect the bug: [presentation](https://gitpitch.com/EvgenyOrekhov/talks/gitpitch-transition-bug-1) ([repo](https://github.com/EvgenyOrekhov/talks/tree/gitpitch-transition-bug-1)).

2. The global `transition=none` doesn't affect image slides as you can see here: [presentation](https://gitpitch.com/EvgenyOrekhov/talks/gitpitch-transition-bug-2) ([repo](https://github.com/EvgenyOrekhov/talks/tree/gitpitch-transition-bug-2)). I guess a separate issue should be opened for this bug.

3. I did as you suggested, but it didn't help: [presentation](https://gitpitch.com/EvgenyOrekhov/talks/gitpitch-transition-bug-3) ([repo](https://github.com/EvgenyOrekhov/talks/tree/gitpitch-transition-bug-3))

**Comment by gitpitch** [comment]
@EvgenyOrekhov thanks for the additional details and test cases. 

1. Good to know. Not something I've ever tested before.

I'll look into issues 1, 2, and 3 and then update this thread once I know more.

**Comment by gitpitch** [comment]
@EvgenyOrekhov the transition setting was not being applied to slides with image backgrounds which explains the problems you reported. That has been fixed b677b3b4313be5826166f8d60ab0d4970fd1a57f and this patch is already live.

When you have a chance can you please test, verify and close issue if satisfied.

**Comment by EvgenyOrekhov** [comment]
@gitpitch All cases are fixed! Thanks!
