### ISSUE TITLE
Document PgUp and PgDown keys

### ISSUE THREAD

**Issue by cbenz** [gitpitch/gitpitch#78]
Hi @gitpitch 

Thanks again for this wonderful tool!

I noticed completely by chance, that pressing PgUp and PgDown would navigate to the next slide, taking into account the 2 dimensions. It will correspond either to DownArrow key, or RightArrow, depending on the availability of a down slide.

The help screen does not mention it:
![image](https://user-images.githubusercontent.com/12686/27077008-0dfde4ca-502f-11e7-9919-cfcf46c942ba.png)

Would it be possible to add it?

**Comment by gitpitch** [comment]
Thanks for this suggestion @cbenz , it's a good idea. I'm just adding this note for myself that this change should be made in tandem with a fix for issue #36 which also needs to update the in-presentation help.

**Comment by gitpitch** [comment]
Quick update. GitPitch has just been updated to use reveal.js 3.5.0 (from 3.3.x) as the default dependency for presentation rendering. As part of this change I have updated the in-presentation Help (?) screen to include:

- PgUp and PageDown keys for previous and next navigations
- Shift key navigations to skip slide fragments
- X key to select source within code blocks

If you are currently overriding the default revealjs version in your PITCHME.yaml for existing presentations and now want to avail of this latest update, please remove that override property for existing presentations. Naturally, all new presentations will use the new default by default :)

Now closing this issue as resolved.
