### ISSUE TITLE
Embedding multiple presentations on the same page.

### ISSUE THREAD

**Issue by James-DBA-Anderson** [gitpitch/gitpitch#79]
I embedded two presentations on a single page. When using the arrow keys to navigate the slide of one of the presentations I found that the controls did a round robin of the two presentations.

Clicking the right arrow would move presentation 1 to slide 2. Clicking it again would move presentation 2 to slide 2 and clicking it again would move presentation 1 to slide 3.

Is there a way to focus the controls to one presentation when multiple presentations are embedded into a page?

**Comment by gitpitch** [comment]
Hi @James-DBA-Anderson there is no auto-magic way for this to happen but I've just implemented something that should give you the building blocks you need to do this easily.

So I've just added support for a new API on presentations, exposing two functions `enableEvents()` and `disableEvents()`.

Assuming you are embedding two or more presentations using iframes [per the Wiki](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Embedding), then you should be able to implement simple logic on your page that lets you control which presentations respond to events (`enabledEvents`), and which presentations do not (`disableEvents`).

You will need to get the `iframe` reference for a given embedded presentation and then do something along these lines to disable events on presentation:

```
gitpitch_iframe_X_ref.contentWindow.disableEvents();
```

Conversely, you can enabled keyboard events on any presentation within an iframe in a similar manner:

```
gitpitch_iframe_Y_ref.contentWindow.enableEvents();
```

I do not have a test setup that replicates the page you are building but I have tested the new functions on the API and they work as expected. 

Hopefully this will give you what you need to build the kind of _focus-on_ and _focus-off_ solution you are looking for.

Out of curiosity, what are you building that embeds two or more GitPitch presentations in a single page? I've not come across this before and I'm always interested in how people are using GitPitch.

**Comment by gitpitch** [comment]
@James-DBA-Anderson did you get a chance to try out these new APIs to control which of your multiple embedded presentations on-a-page received keyboard focus?
