### ISSUE TITLE
Set vertical-center per slide

### ISSUE THREAD

**Issue by borismod** [gitpitch/gitpitch#85]
Hello 

I would like to set vertical align for a specific slide to off, but for the rest to on. 

How can I do it?

**Comment by gitpitch** [comment]
Hi @borismod thanks for getting in touch. You can not turn vertical-center alignment off on a slide-by-slide basis as you might hope. But you can turn vertical-center alignment off for your entire presentation and then you can turn vertical-center alignment on, on a slide-by-slide basis. 

The end result is you get exactly what you want: some slides will use vertical-center alignment, and some will not. This is probably best understood by following a step-by-step example:

### Step 1. Disable vertical-center alignment for entire presentation

Disable the `vertical-center` setting in your `PITCHME.yaml` file as follows:

```
vertical-center : false
```

### Step 2. Enable vertical-center alignment on a slide-by-slide basis

To activate vertical-center alignment on a slide-by-slide basis you can add the following `html-comment` snippet at the start of any slide where you want vertical-center alignment (directly following the slide delimiter):

```
<!-- .slide: class="center" -->
```

### Step 3. Learn By Example

Assuming the `vertical-center` property has been disabled in the `PITCHME.md` for this presentation the presentation content shown below describes how text will be rendered on each slide:

```
<!-- .slide: class="center" -->
# Slide A Text Vertically-Centered

Lorem ipsum dolor sit amet...

---

# Slide B Text Not-Vertically-Centered

Lorem ipsum dolor sit amet...

---
<!-- .slide: class="center" -->
# Slide C Text Vertically-Centered

Lorem ipsum dolor sit amet...

```

If you have a chance to try this out, let me know how it goes.

**Comment by borismod** [comment]
@gitpitch hello and thank you for quick reply.

I tried it and it does not work for me: all the slides are vertically centered.

Moreover, the markdown file looks cluttered with multiple "slide" directives. 

Is there any chance it vertical alignment will be enabled per slide?

**Comment by gitpitch** [comment]
@borismod can you provide me with a link to your presentation so I can investigate. Thanks.

**Comment by gitpitch** [comment]
Hi @borismod while I await a link to your presentation to investigate the problem you reported you can take a quick look at the following sample presentation that I just created to demonstrate this feature working as described.

You can view [the sample presentation here](https://gitpitch.com/gitpitch/feature-demo/per-slide-alignment).

As to your question:
> Is there any chance it vertical alignment will be enabled per slide?

This is the default setting within the underlying reveal.js library. All slides have vertical-center alignment by default. But if you want to mix-and-match alignments (toggling this on/off per slide), right now the only way I can see to do that is to disable this default setting and then activate vertical-center alignment on a slide-by-slide basis.

**Comment by gitpitch** [comment]
Closing issue for now as solution provided in thread. Issue can be opened again if example presentation that can demonstrate issue is provided.
