### ISSUE TITLE
Code presenting problem

### ISSUE THREAD

**Issue by Kjwon15** [gitpitch/gitpitch#86]
If there are more than 1 code block in a slide, code presenting is malfunctioning.

example: 

````markdown
# slide
```c
int main() {
  int a = 10;
  int b = 20;
}
```
@[2-3](set a, b as 10, 20)
```c
int main() {
  int c = 30;
  int d = 40;
}
```
@[2-3](set c, d as 30, 40)
````

All of code fragment is highlighting first code block.
The second one should be highlight second block.

**Comment by gitpitch** [comment]
Hi @Kjwon15 code-presenting only supports a single code-block per slide. So you will need to:

1. Create a single code block:

```c
int main() {
  int a = 10;
  int b = 20;
}

int main() {
  int c = 30;
  int d = 40;
}
```

And then create a set of code-delimiter markers under this single code-block, like this:

```
@[2-3](set a, b as 10, 20)
@[7-8](set a, b as 30, 40)
```

2. Or you will need to split your two code samples onto two different slides.
