### ISSUE TITLE
Highlighting multiple separate code lines

### ISSUE THREAD

**Issue by fkromer** [gitpitch/gitpitch#89]
Could you add support for highlighting multiple separate lines (no line range). (The code-fragment marker syntax seems not to support that yet. E.g. `@[5,9]` could be suitable...)

**Comment by justsml** [comment]
I tried to find this in the code base... Can anyone point me in the right direction? (For first PR)

Idk, maybe I'm just rusty on my Java...

**Comment by gitpitch** [comment]
I'm travelling for the rest of the month so I won't have time to look at this until early August. Highlighting for the code presenting feature is implemented in JS within the following file:

```
libs/highlight.js/9.6.0/reveal-code-focus-1.0.0-mod.js
```

If you have a PR for me please go ahead and submit it and I'll review it when time permits. If not, I'll try and look at what's involved to support this feature when I'm home.

**Comment by gitpitch** [comment]
I've just pushed a patch that adds support for multiple-slices of code to be represented within a single code-fragment marker. This will allow you highlight multiple non-contiguous blocks of code using a single marker. For example, the following marker `@[7, 11-14]` renders as follows:

<img width="953" alt="cp-multi-frag" src="https://user-images.githubusercontent.com/19169584/30091930-5ff401b6-92e6-11e7-9723-c39043102f24.png">

By way of further example, each of the following are now valid code-fragment markers:

```
@[1]
@[3-6]
@[2, 4-8]
@[3,4,6]
@[3-5, 7]
```

As you can see the new code-fragment marker syntax is very flexible and should cover most if not all imaginable use cases. The [Code Presenting](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting) page on the GitPitch Wiki has been updated to document this new feature.

This patch is live on `gitpitch.com`. If you try it out please let me know how you get on so we can update or close this issue. Thanks.

**Comment by fkromer** [comment]
@gitpitch Great. Thanks a lot.
