### ISSUE TITLE
Background images are not in offline export

### ISSUE THREAD

**Issue by jroper** [gitpitch/gitpitch#9]
See the offline export of http://gitpitch.com/jroper/microservices-architecture as an example.

**Comment by gitpitch** [comment]
Thanks for reporting this issue. A subtle caching bug was causing intermittent problems which resulted in offline slideshows sometimes failing to render background images. This issue has been resolved by commit b294a7c. And this change has been pushed live to [GitPitch.com](https://gitpitch.com).

@jroper [here is a link to your slideshow](https://gitpitch.com/jroper/microservices-architecture/8b7d3f74725cd1219dffa14432af6c871e33223a) where you left off working. Click it to see if this fix resolves this issue.
