### ISSUE TITLE
Open private slides on local server

### ISSUE THREAD

**Issue by fkromer** [gitpitch/gitpitch#91]
Is it possible to open slides from a private github repository on a local gitpitch server? (It would be helpful to edit slides locally before making them public.)

**Comment by gitpitch** [comment]
Hi @fkromer. No, only `PITCHME.md` found within public repositories are supported. You may want to consider using a dedicated feature branch (not master) to develop your presentations. Obviously using a dedicated branch would not keep your presentation content private, but using branches can keep your presentation content somewhat out of the public eye until you are ready to publish on master.

**Comment by fkromer** [comment]
Yes. That's better than having them on the master branch.

However beeing able to completely hide incomplete slides would be great. Is it planned to add support for private repos or cloned slide repos on the local file system?

**Comment by gitpitch** [comment]
You do have the option to develop the slides for your presentation offline. See the [Developing / Testing Locally](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally) page on the Wiki. This allows you to develop your entire presentation content offline, which means the content remains private.

Once you are ready to go public you can then commit and push the offline files to your git repo and share your presentation in public.

**Comment by fkromer** [comment]
Ok. I will try the workaround with symlinks which could make handling the development and versioning workflow even easier... Thanks.
