### ISSUE TITLE
Embed Rendered webpage in slide

### ISSUE THREAD

**Issue by jayvdb** [gitpitch/gitpitch#92]
I would like to embed a webpage inside a slide.

An example of the webpage I would like to embed is http://tinyurl.com/y92cnd9r , which is actually `https://query.wikidata.org/#SELECT %3Fisland %3FislandLabel %0AWHERE {%0A %3Fisland wdt%3AP31%2Fwdt%3AP279* wd%3AQ23442.%0A%0A %0A %0A %0A %0A %0A %0A SERVICE wikibase%3Alabel { bd%3AserviceParam wikibase%3Alanguage "id%2Cen". }%0A}` , and the rendered webpage shows the query that the slide will be about.

I would not mind if these are rendered once and embedded as an image.  Ideally the UI has a clickable link somewhere to go to the live webpage.

Ideally the images are permanently cached, and not re-rendered without a manual preview to confirm the result is still correct.

(Also it would be great if gitpitch was on gitter or some other chat channel where I could reach other community members who can help me with teething problems; I couldnt find one mentioned anywhere)

**Comment by jayvdb** [comment]
https://slides.com supports this with an iframe (with http only; no https) : https://slides.com/jayvdb/deck/live#/0/1

**Comment by gitpitch** [comment]
Hi @jayvdb apologies for the delay in getting to this, I've been busy elsewhere. So you should be able to embed your iframe directly into any GitPitch slide, just drop an `iframe` into your `PITCHME.md` markdown as follows:

```
---

<iframe class="stretch" data-src="https://tinyurl.com/y92cnd9r"></iframe>

---
```

Please note the following:

#### 1. Mixed Content Browser Security Protection

All GitPitch presentations on `gitpitch.com` are loaded over HTTPS. One consequence of this is that all requested resources on that page must also be secure, so loaded over HTTPS and not HTTP. Insecure resource requests, those over HTTP, will be blocked.

So the use of the **http://tinyurl.com/y92cnd9r** you provided will not work as it is an insecure resource. Either use **https://tinyurl.com/y92cnd9r** or use the original _non-tiny_ query.wikidata.org url directly which itself is already over HTTPS.

#### 2. Iframe Stretch

For `iframe` content to make full/best use of the space available on your slides you need to apply the `stretch` class to the iframe as shown in the snippet above.

If you test this out please let me know how you get on so we can update or close this issue. Thanks.

**Comment by paddytobias** [comment]
Ive tried adding numerous `https://` addresses following the syntax above but these are still not showing. Any ideas why?

**Comment by gitpitch** [comment]
The most likely reason is that the site you are trying to load into your ifame has an `X-FRAME-OPTIONS` header set to `DENY`.

You can easily test this theory on your command line:

 `curl -i the-url-you-are-using-in-your-iframe-src` 

And see what comes back in the HTTP headers.

**Comment by paddytobias** [comment]
I am trying to present a google doc and `x-frame-options` has `SAMEORIGIN`

thanks for your help
