### ISSUE TITLE
Profile list of presentations

### ISSUE THREAD

**Issue by jayvdb** [gitpitch/gitpitch#93]
It would be nice if https://gitpitch.com/gitpitch showed a list of presentations by user/org `gitpitch`

**Comment by gitpitch** [comment]
Hi @jayvdb thanks for this feedback. Agreed, this is a nice idea and I've considered implementing this feature in the past. For a number of reasons, primarily related to _time-and-scope_, this is not something I plan to add in the near to medium term so, for now, I'm going to close this RFE as will-not-implement.
