### ISSUE TITLE
Gitpitch frame / menus do not appear for component presentation

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#94]
I am using the modular markup / asset sharing feature described in the Wiki.

The following modular presentation displays for me, but the page does not display the gitpitch frame and menus around the presentation.

https://gitpitch.com/terrywbrady/dspaceUserMeeting?grs=github&t=white&p=schedule

The gitpitch frame does appear when I open the main presentation for the repo.

https://gitpitch.com/terrywbrady/dspaceUserMeeting?grs=github&t=white

**Comment by gitpitch** [comment]
Hi @terrywbrady I just opened the link you provided and this is what I see:

<img width="1344" alt="terry" src="https://user-images.githubusercontent.com/19169584/28853759-b4bffc36-772a-11e7-8c62-10a904778c4f.png">

This is what I would expect to see. What am I missing?

**Comment by terrywbrady** [comment]
Thanks. I will close this issue.

I had created the following link in my markdown:  [Schedule](?p=schedule)

That created a link that pointed to 

https://gitpitch.com/pitchme/slideshow/github/terrywbrady/dspaceUserMeeting/master?p=schedule#/

Rather than to 

https://gitpitch.com/terrywbrady/dspaceUserMeeting?grs=github&t=white&p=schedule

I was attempting to write my url references in a manner that would preserve any branch references from the source presentation.
