### ISSUE TITLE
Images not showing in offline mode

### ISSUE THREAD

**Issue by jerdog** [gitpitch/gitpitch#96]
When I add an image to a slide, I am using:
`![Logo](images/opensource_logo.png)`

Which works when viewing online. But when I download and attempt to view it locally
`python -m http.server`

It displays the alt-text (in this case "Logo") instead of the image. It's trying to pull it from `http://localhost:8000/assets/opensource_logo.png` which in the offline.zip is relative to the pitchme.md file in the /md/assets/ folder and the file is there... All very strange

**Comment by gitpitch** [comment]
Hi @jerdog can you please point me at your presentation repo so I can try reproduce and investigate the issue you have reported. Thanks.

**Comment by jerdog** [comment]
https://gitpitch.com/jerdog/gitpitch-wowza/dev?grs=gitlab

**Comment by gitpitch** [comment]
Ok, so I just took your sample presentation offline. Based on the`PITCHME.md` source I see just two images in use. When opened under a local HTTP server I see both of them, as shown here:

<img width="1353" alt="img-one" src="https://user-images.githubusercontent.com/19169584/29177351-b4f33340-7e18-11e7-8e14-c32a1b40dd89.png">

<img width="1353" alt="img-two" src="https://user-images.githubusercontent.com/19169584/29177365-bcd2d2a0-7e18-11e7-90f7-ca6aba7ea881.png">

You can see both are shown `Offline` in the bottom-right corner of the slideshow window.

Given this, I do not appear to be able to reproduce the problem you have reported here. So a few further questions for you:

1. Which of the two images is not showing up in your offline presentation?
2. What operating system are you using locally to open your presentation?
3. What if any errors are showing up in your developer console for your presentation?

**Comment by gitpitch** [comment]
@jerdog  as a side note, the size of your second image is not a perfect fit for the slideshow aspect ratio so you might want to consider using the [Image Sizing and Scaling](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#slide-image-sizing--scaling) feature to have that rendered more nicely on the slide.

For example, replace your original markdown:

```
+++
![OSD](images/opensource_definition.png)

---
```

With this:

```
+++?image=images/opensource_definition.png&size=auto 90%

---
```

Not required of course, but it may render more nicely for you when you are using a tall-and-narrow image to fill a wide-and-short slide as in this case.

**Comment by jerdog** [comment]
1. Neither are showing in offline
2. Ubuntu Gnome 17.04
3. No real valuable errors (Firefox and Chrome both say the file is not found for the images)

I am using the python 3 http.server - what about you?

And yeah - was planning on making that image a slide image

**Comment by gitpitch** [comment]
My testing has been on OSX. I have tried both Python 2.7.x and Python 3 HTTP servers using:

```
python -m SimpleHttpServer
```

and

```
python3 -m http.server
```

respectively.

In both cases, both of your images were rendered without any problems.

**Comment by gitpitch** [comment]
@jerdog if you haven't already you might want to verify that the image assets are available on disk as the expected location and loadable by your HTTP server. The expected URLs are as follows:

```
http://localhost:8000/assets/md/assets/opensource_definition.png
```

```
http://localhost:8000/assets/md/assets/opensource_logo.png
```

Both of these URLs should open and display the respective images in your browser. And if they don't, we have new clues to investigate.

**Comment by jerdog** [comment]
Yeah - they open with direct links - but they don't open in offline gitpitch for me. 

When you look at the code output, it is showing the following locations:
http://localhost:8000/assets/opensource_logo.png
http://localhost:8000/images/opensource_definition.png

**Comment by gitpitch** [comment]
@jerdog can you put the `PITCHME.zip` bundle that you generated taking your presentation offline somewhere public so I can download exactly what you are looking at.

Also, can you please try download the bundle again and verify that the latest bundle is also exhibiting the problems you described. I asked for this having noted above that the offline bundle I have tested here has worked perfectly.

**Comment by jerdog** [comment]
So I feel stupid... Just removed my local and recreated it from the offline and now it works. No idea what happened/changed/etc. Thanks for your patience.

My guess is it had something to do with multiple changes made to my presentation/code between when I downloaded the original offline copy and when I was just attempting to copy in my changed PITCHME.md file

**Comment by gitpitch** [comment]
No problem @jerdog just glad to hear you are back up and running with your GitPitch presentation. If you have any further questions don't be afraid to get in touch.

**Comment by dbuteau** [comment]
Hello i've encountered the same problem and find out why.
When you change the docker port, for example -p 80:9000 (or in the case of jerdog :8000)
The slide appear but the app continue to include the default port :9000 in the images urls so they don't appear on the slide.
restarting the docker with the default port 9000 fix the problem.

**Comment by gitpitch** [comment]
@dbuteau this issue thread is for an old offline feature that is no longer supported. I know you are using GitPitch Desktop. To set a custom port for the Desktop you need to make two changes on your launch command:

1. Update the -p port mapping and
1. Add a matching PORT environment variable

For example:

```
docker run -it -v {WORKINGDIR}:/repo -p 80:80 -e PORT=80 gitpitch/desktop:pro
```

See the Desktop FAQ for [details](https://gitpitch.com/docs/pro-features/desktop-faq#how-can-i-change-the-default-9000-port-used-by-desktop-pro). The documented steps should solve your problem. Let me know how it goes. Cheers, David.
