### ISSUE TITLE
Can't specify contents of a fragment in MD

### ISSUE THREAD

**Issue by Chovin** [gitpitch/gitpitch#97]
when trying to style fragments, things start to break down

```md
- [links](blah.md)  |
- **bold** is fine but *em*?  |
```
Image from [example slides](https://gitpitch.com/Chovin/gitpitch/multi-object-fragments
)
![image](https://user-images.githubusercontent.com/17536161/29454052-1c6f44e6-844f-11e7-870b-d4735385749e.png)

sorry I tried to put the source in the slides as well but couldn't figure out how to render markdown source

**Comment by gitpitch** [comment]
Hi @Chovin you will need to use a HTML html `span` element that wraps the content for each bullet-point. And that span element must have `class="fragment"` as shown here:

```
- <span class="fragment">![kitten](https://s-media-cache-ak0.pinimg.com/236x/a4/30/d9/a430d949eb0da1204c6cbe2958d7a188--iphone-c-cases-case-for-iphone.jpg)</span>
- <span class="fragment">**Get** the *word* out</span>
- <span class="fragment">This works fine though</span>
- <span class="fragment">This [link](https://www.google.com)</span>
- <span class="fragment"><span style="color:red">this</span>?</span>
```

**Comment by mklemm2** [comment]
That's very counter–intuitive and should be improved. Maybe put everything between “|(” and matching “)" into one fragment?

**Comment by gitpitch** [comment]
I looked at this again thanks to prompt from @mklemm2  and the simplest way to render multi-object fragments using currently available support is as follows:

```
<ul>
<li class="fragment">![kitten](https://s-media-cache-ak0.pinimg.com/236x/a4/30/d9/a430d949eb0da1204c6cbe2958d7a188--iphone-c-cases-case-for-iphone.jpg)</li>
<li class="fragment">**Get** the *word* out</li>
<li class="fragment">This works fine though</li>
<li class="fragment">This [link](https://www.google.com)</li>
<li class="fragment"><span style="color:red">this</span>?</li>
</ul>
```

This is standard HTML unordered list syntax that wraps Markdown content for each bullet point. Hopefully this is simple and intuitive for users.

The request to add new shortcut syntax is reasonable but unworkable as described given how the single-pass Markdown preprocessor currently works. The best approximation of how this could potentially be supported would look as follows:

```
<ul>
- ![kitten](https://s-media-cache-ak0.pinimg.com/236x/a4/30/d9/a430d949eb0da1204c6cbe2958d7a188--iphone-c-cases-case-for-iphone.jpg)  |
- **Get** the *word* out  |
- This works fine though  |
- This [link](https://www.google.com)  |
- <span style="color:red">this</span>?  |
</ul>
```

The only change here from currently existing support for single-object fragments is that you would be required to add the opening `<ul>` and closing `</ul>` respectively. 

Is the existing HTML unordered list solution (as shown above) sufficient or is there real demand for the possible extension?

**Comment by gitpitch** [comment]
Updated [Fragment Slides](https://github.com/gitpitch/gitpitch/wiki/Fragment-Slides) page on the GitPitch Wiki to clearly document the use of fragment lists using simple v rich markdown.

**Comment by mklemm2** [comment]
Well, in the end, it's up to you. But for me the point of using markdown is to *not* having to write HTML whenever possible. I just thought that maybe it is easy to implement.

By the way, I held a very successful presentation, today, thanks to GitPitch. So thank you very much for this great tool!

**Comment by gitpitch** [comment]
@mklemm2 glad to hear you are enjoying using GitPitch and great to hear your presentation went well.

Agreed, using markdown whenever possible is the overall goal here. In this case, avoiding HTML entirely for _fragment-lists-using-rich-markdown-content_ is not possible currently or even if the proposed new syntax was adopted.

Given this, I'm not going to add support for syntax changes at this time. I will update this thread if that changes.

**Comment by gitpitch** [comment]
Bump. New (much) simplified fragment list syntax now available. See #166 for details.
