### ISSUE TITLE
Unable to put link in footnotes

### ISSUE THREAD

**Issue by themantalope** [gitpitch/gitpitch#98]
I would request that in addition to plain text, the footnote can contain a link.

For instance, I would like to be able to have a footnote with a link that can take me back to "contents" slide in a presentation or some other useful location within the presentation.

It looks like the footnote that is specified in the `PITCHME.yaml` file is always rendered as plain text.

**Comment by gitpitch** [comment]
Hi @themantalope I've just added support for arbitrary HTML fragments to be used when specifying your custom footnotes. This will allow you to add links as requested.

For example, in your `PITCHME.yaml` file add the following:

```
footnote : "<a href='#/3'>Presentation Menu</a>"
```
This should create a link in the footer location that when clicked should automatically take you to the third slide in the presentation.

Given you are injecting custom HTML you are responsible for styling it. By default, HTML anchors are rendered using the traditional blue font color. Which doesn't look great alongside the GitPitch presentation themes. So I recommend that you add a little style of your own.

For example, assuming you are using one of the dark themes then making your footnote-link white helps it stand out:

```
footnote : "<a style='text-decoration:none; color: white;' href='#/3'>Presentation Menu</a>"
```

Alternatively, if you are planning on using one of the light themes then making your footnote-link black is probably the way to go:

```
footnote : "<a style='text-decoration:none; color: black;' href='#/8'>Presentation Menu</a>"
```

Note, I've also disabled the `text-decoration` style on this link as I think it looks better on the slide but of course this is of optional.

As a final note. As an alternative to adding styling directly within your footnote HTML you could simply define a class on your HTML footnote anchor and then use GitPitch [custom css](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Custom-CSS) to apply whatever styling changes you want for this link. Which approach you take is entirely up to you.

If you try this out let me know how it goes so we can update this issue. Good luck.

**Comment by gitpitch** [comment]
Note, the GitPitch [Wiki has been updated](https://github.com/gitpitch/gitpitch/wiki/Footnote-Setting) to reflect this new support for HTML fragments within footnotes.

**Comment by themantalope** [comment]
Beautiful! Thanks!
