### ISSUE TITLE
Support for branches with odd characters in names

### ISSUE THREAD

**Issue by shalomb** [gitpitch/gitpitch#99]
We have begun evaluation of gitpitch internally in our gitlab-based organization and this has our engineers/management quite enthused. :) 

A bit of a blocker for adoption is that our org. uses gitflow and branch names have slashes in them of the form `feature/foo` or `bugfix/bar`, etc which gitpitch does not seem to work with.

e.g.
```
https://gitpitch.com/user/repo/branch          # works
https://gitpitch.com/user/repo/feature/branch  # does not
```

Please would you add support for these?

**Comment by gitpitch** [comment]
Hi @shalomb thanks for getting in touch, and nice to hear your organization is interested in using GitPitch. 

To help me fully evaluate this feature-request it would be helpful if I could look at the GitLab documentation that describes the branch-naming conventions that you are using internally. Do you have a link for that? Thanks.

**Comment by shalomb** [comment]
Hi @gitpitch 

So the git workflow we have is something along the lines of [A successful Git branching model » nvie.com](http://nvie.com/posts/a-successful-git-branching-model/) using `git flow` from [nvie/gitflow](https://github.com/nvie/gitflow).

This is how various branches take prefixes under nvie's `git flow`
```
    | *branch type* | *merge-base*   | *prefix* | *example branch names*
    | master        | N/A            | N/A      |
    | develop       | master         | N/A      |
    | feature       | develop        | feature/ | feature/revamp-login-ui
    | bugfix        | develop        | bugfix/  | bugfix/broken-reset-workflow
    | hotfix        | master,develop | hotfix/  | hotfix/OPS-32--n+1-in-sales-relations
    | release       | develop        | release/ | release/S22
```

I have seen other org's use dashes instead of slashes for the prefixes - but nvie's gitflow doesn't do this (by default atleast)

Our use of `PITCHME.md`'s would likely only be at the `feature/` branch-levels for engineers to showcase feature proposals, design mockups, articulate ideas/workflows, etc. I expect on rare occasion we may want to present from a `bugfix/`

I presume gitpitch does now know how to handle the slashes in the branch names.
e.g.
* [kitchen-sink/PITCHME.md at master](https://github.com/shalomb/kitchen-sink/blob/master/PITCHME.md) - works [just fine](https://gitpitch.com/shalomb/kitchen-sink/master)
*[kitchen-sink/PITCHME.md at feature/new-sales-screen](https://github.com/shalomb/kitchen-sink/blob/feature/new-sales-screen/PITCHME.md) - returns a [HTTP 303](https://gitpitch.com/shalomb/kitchen-sink/feature/new-sales-screen) presumably because the additional "component" in the URI is something unhandled?

**Comment by shalomb** [comment]
It's probably another topic of discussion - but a possible solution to this may also kill another bird.

A question was asked why we were tied to `PITCHME.md` as the base of a presentation - as if a developer wanted to present an alternative he would either have to create another branch or present the alternative in amongst the only presentation for the branch - but then the presentation may _not tell the story_ about what lies in the branch.

It'd be nice if under some circumstances to point gitpitch at another `.md` file that is not `GITPITCH.md` for the base of a presentation.

e.g.
* A missing filename (e.g. [org/repo](https://gitpitch.com/org/repo/master)) defaults to using https://github.com/org/repo/blob/master//PITCHME.md
* A named file (e.g. https://gitpitch.com/org/repo/master/spec-42.md)  uses  https://github.com/org/repo/blob/master/spec-42.md for the presentation (instead of and disregarding `GITPITCH.md`)
* A named file for a feature branch (e.g. https://gitpitch.com/org/repo/feature/new-sales-screen/spec-42.md) ends up using https://github.com/org/repo/blob/feature/new-sales-screen/spec-42.md

**Comment by gitpitch** [comment]
Hi @shalomb 

Thanks for the links and additional info. Some quick clarifications that may be helpful for you.

### 1. Branch Names with Slashes

Currently there are just two valid GitPitch presentation URIs:

```
https://gitpitch.com/$user/$repo
https://gitpitch.com/$user/$repo/$branch
```

So using a branch name that itself contains a slash has the effect of creating an entirely new presentation URI that, when generalized, would look something like this:

```
https://gitpitch.com/$user/$repo/$branch-prefix/$branch-postfix
```

While this is still a valid URI pattern, this URI pattern is _not a valid GitPitch presentation URI_. 

That information is just FYI to help you clearly understand why your _branch-names-with-slashes_ are an issue. If you were following the convention of using _branch-names-with-dashes_ for example, this is supported today.

Anyway, once I have time to look into what is involved to support _branch-names-with-slashes_ I will update this thread. 

### 2. PITCHME.md Alternate Locations

> if a developer wanted to present an alternative he would either have to create another branch or present the alternative in amongst the only presentation for the branch

Some good news for you is that this is not the case. GitPitch has two simple conventions:

1. GitPitch presentation markdown lives in a file called **PITCHME.md** 
2. That markdown file is found in the **root directory** of your repo.

And while presentation markdown must always be provided in a file called **PITCHME.md**, the **root directory** convention can be overridden. 

This means a single branch in your repo can support multiple presentations. See the [Single Branch - Multiple Presentations](https://github.com/gitpitch/gitpitch/wiki/Asset-Sharing) page on the GitPitch Wiki for details.

> It'd be nice if under some circumstances to point gitpitch at another .md file that is not GITPITCH.md for the base of a presentation.

Once you read the Wiki page linked above, you should be able to see that you can do that right now:

e.g.

- PITCHME.md Default Location
   - https://gitpitch.com/org/repo
- PITCHME.md Custom Location
   - https://gitpitch.com/org/repo?p=spec-42
- PITCHME.md Custom Location in Feature Branch
   - https://gitpitch.com/org/repo/branch?p=spec-42

**Comment by gitpitch** [comment]
Hi @shalomb I have just pushed experimental support for branches following the default _nvie gitflow_ naming conventions, such as `feature/x` or `bugfix/y`.

The approach I have taken aims to preserve full backward compatibility while introducing a new convention for these types of _compound_ branch names.

#### How does it work?

Assuming you have a branch named `feature/revamp-login-ui` then you can open the presentation on this branch as follows:

```
https://gitpitch.com/user/repo/feature~revamp-login-ui
```

The default convention is simple: replace the `/` in a compound branch name with a `~` as shown above.

Given you indicated that you are a GitLab based organization then the complete URL would be as follows:

```
https://gitpitch.com/user/repo/feature~revamp-login-ui?grs=gitlab
```

As noted this feature is experimental so has not yet been merged back into the GitPitch master branch. But this feature is now live on _gitpitch.com_. I have made this live so you can test and evaluate this new feature. Can you please update this thread with your feedback. Thanks.

**Comment by shalomb** [comment]
Hi @gitpitch,

Many thanks for this. 👍 

Unfortunately our GitLab instance is an on-prem one behind a firewall that gitpitch.com cannot access (as you might imagine, we have to run a gitpitch instance internally too)

However, I have tested this against github and forked the [kitchen-sink](https://github.com/gitpitch/kitchen-sink) and made a few test [branches](https://github.com/shalomb/kitchen-sink/branches) that seem to be [working just fine](https://gitpitch.com/shalomb/kitchen-sink/feature~new-sales-screen). I should imagine this will work against GitLab too.

We look forward to their being merged into _master_ as we can deploy this internally too.

Many thanks again!!

**Comment by gitpitch** [comment]
Hi @shalomb I have tested this patch myself against GitLab and it works just fine.

These changes are now merged into `master` so you can spin-up your on-prem GitLab instance and check it out. Many people are using GitPitch alongside their own private GitLab instances so you should have no problems. But if you do, let me know.

**Comment by gitpitch** [comment]
Closing issue as resolved.

**Comment by ialidzhikov** [comment]
@gitpitch , the section about `1. Branch Names with Slashes` is not longer working. I cannot reference branch containing a slash (`/`).

**Comment by gitpitch** [comment]
@ialidzhikov can you share a link to a sample repo (slide deck) that can be used to demonstrate and test the problem you are reporting?

**Comment by ialidzhikov** [comment]
https://gitpitch.com/shalomb/kitchen-sink/feature~new-sales-screen

**Comment by ialidzhikov** [comment]
@gitpitch , are you able to reproduce?

**Comment by gitpitch** [comment]
Thanks for that. I believe I know what is causing this regression. I'll try to look into it over the next day (or two) and will update this thread once I have something to share. Thanks again for bringing this to my attention. Cheers, David.

**Comment by gitpitch** [comment]
@ialidzhikov a new patch has just gone live on gitpitch.com. This should fix the issue handling `Branch Names with Slashes`. When your time permits can you please test and verify. Thanks, David.

**Comment by ialidzhikov** [comment]
It works again, David. Thank you for the fast reaction! 🚀

**Comment by gitpitch** [comment]
Thanks for testing the patch :clap: Glad to hear it is working again. Cheers, David.
